### ISSUE TITLE
Vertical fog occlusion

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1020]
The terrain above and below the player is always rendered, but on low render distances it's never seen.

It would be nice to add vertical fog occlusion to reduce useless load on complex maps.

Alternatively, there should be an option to not display fog below and above the player.

**Comment by Eiion** [comment]
Agreeing with the "option to not display fog below and above the player".
I regularly fly way up in the sky with render distance set to a very high number to get a good overview of a large area. With the vertical fog and also with all those massive ruptures added due to the new world generation and large caves (no matter if at world bottom or all around the highest possible mountains - I hope they are going to make some hefty adjustments to how that currently works) that make huge holes into the surface the vertical fog certainly is an issue.

**Comment by jellysquid3** [comment]
This was completed in Sodium 0.5.0 in order to mimic vanilla behavior.
