### ISSUE TITLE
sodium 1.18 has bad framerate compared to optifabric 1.18

### ISSUE THREAD

**Issue by vivaan98** [jellysquid3/Sodium#1037]
sodium fps averaging at 10-5 fps but optifabric fps at 20-40 fps

**Comment by Drakkar666** [comment]
Glad to see I'm not the only one having this issue, at the moment I get roughly half of FPS I can get with OptiFabric. Hopefully this gets better as 1.18 branch progresses!

**Comment by Felix14-v2** [comment]
Optifine also uses some internal server improvements, which can reduce CPU overload. Maybe you should also use other optimisation mods like Starlight and FerriteCore.
But yes, at this moment optifine is showing itself to be more effective on some extra old PCs.

**Comment by Endstarky** [comment]
in rendering optifabric smoothen outs tall grass, grass which sodium doesnt at all which decreases frame rates in sodium and also a very bad visual impact.

**Comment by jellysquid3** [comment]
> Glad to see I'm not the only one having this issue, at the moment I get roughly...

Sodium 0.4 is alpha software. We have many further optimizations to add. In the interest of allowing players to at least use Sodium on MC 1.18 we published an alpha version, which goes against what we usually do. :slightly_smiling_face: It's just a matter of my time to work on implementing those things.

> in rendering optifabric smoothen outs tall grass, grass which sodium doesnt at all which decreases frame rates

OptiFine renders tall grass and other foliage blocks on the same layer as most other blocks as a cheap trick to improve frame rates, but this isn't really relevant in Sodium because draw calls aren't that expensive. Either way we're not changing the game's aesthetic in order to improve performance.

> Optifine also uses some internal server improvements, which can reduce CPU overload

Regrettably, OptiFine's improves for the integrated server are mostly to not tick anything the player can't see... which is the equivalent of just turning off parts of the world. There's not much other server-side optimization it does.

---

If people are seeing such drastic differences in frame rates, you should provide screenshots of ALT+F3 between OptiFine and Sodium so at least have some kind of data point. Saying the game is slower isn't really helpful at all.

**Comment by jellysquid3** [comment]
I suspect the issue here is mostly related to #1044 and will be closing this issue as there hasn't been any additional information in the last month.
