### ISSUE TITLE
firework particles (and probably particles in general) are not made above the maximum height of the world

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#1081]
### Version information

Sodium alpha 6 - 1.18.1

### Expected Behavior

We should see the particles

### Actual Behavior

The particles are not rendered

### Reproduction Steps

Video:

https://user-images.githubusercontent.com/68275908/147370011-3a154743-07e2-455e-9494-23564c57e1fa.mp4

### Java version

Java 17

### CPU

Ryzen 1600

### GPU

GTX 1070

**Comment by bytzo** [comment]
It looks like this behavior is caused by Sodium's particle culling.

https://github.com/CaffeineMC/sodium-fabric/blob/d50338a9a6c01614f5f941bebbcd4b47e61939fd/src/main/java/me/jellysquid/mods/sodium/mixin/features/particle/cull/MixinParticleManager.java#L60-L69

To perform particle culling, Sodium skips rendering any particles that are not in a visible chunk section. However, particles above or below the world height are never in a visible chunk section, causing them to always be culled.

A fix similar to 885222a476b7054ae428031d72c0b47fa579872a would likely resolve this issue.
