### ISSUE TITLE
Loading world

### ISSUE THREAD

**Issue by kittech0** [jellysquid3/Sodium#1138]
### Version information

mc1.18.1-0.4.0-alpha6+build.14

### Reproduction Steps

1. Load into minecrft
2. Single player
3. Create world
4. Wait until 100% and it will crash

### Crash Report file

Actually there is no crash report
full log
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/7882817/latest.log)

### Additional information

I think it can couse errors becuz of C2ME mod and colormatica mod too

**Comment by srnyx** [comment]
I'm getting this crash too: https://paste.srnyx.xyz/purilipiyi.properties
Only recently started happening so I think it has to do with Sodium v0.4.0-alpha6
It also happens when joining multiplayer, which means it's an issue with rendering.

**Confirmed it's because of Colormatic: https://github.com/kvverti/colormatic/issues/74**
