### ISSUE TITLE
many chuncks dont render (bug)

### ISSUE THREAD

**Issue by KlaraChaos** [jellysquid3/Sodium#1139]
### Version information

mc 1.18.1 sodium-fabric-mc1.18-0.4.0-alpha6+build.14

### Expected Behavior

chunks loading

### Actual Behavior

the chucks of some part of my world dont render at all like i can walk on them and everything but i dont see anything ther

modpack im using is another quallity modpack 2 version 1.6

log
[2022-01-16-1.log](https://github.com/CaffeineMC/sodium-fabric/files/7877667/2022-01-16-1.log)
e

### Reproduction Steps

1.start mc
2.load an existing world
3.observe chucks not rendering 

### Java version

java 17

### CPU

intel core i5-9400f

### GPU

Nvidia geforce gtx 1660 ti

**Comment by HoodieRocks** [comment]
Currently experiencing similar symptoms, similar hardware

**Comment by Pectacular** [comment]
This is stated as a known issue in the release notes

**Comment by offbeat-stuff** [comment]
I am experiencing the same issue on well arm64 android-7 honor 6x while baritone moves too fast before the chunk is properly loaded. Is that because of my hardware or this bug

**Comment by offbeat-stuff** [comment]
Looks like its been fixed in IMS212's fork of Iris shader fork of sodium in their latest commit also with support for latest snapshot

**Comment by christofin** [comment]
> This is stated as a known issue in the release notes

Are you talking about this?

"Some parts of the world may not load correctly unless the player exits and loads the world file again"

Because for me it's the same exact chunks every time - doesn't matter whether I exit or reload the world or not, the same chunks render incorrectly. Such as in this video:

https://user-images.githubusercontent.com/43354771/151596014-dc40181c-c364-4eeb-96c9-f861b89ed2fa.mp4

**Comment by MeeniMc** [comment]
Duplicate #872
