### ISSUE TITLE
Caught exception from Minecraft Forge (forge)

### ISSUE THREAD

**Issue by Kotsiface** [jellysquid3/Sodium#1146]
### Version information

mc1.12.2

### Reproduction Steps

Recently Updated the modded pack. It crashes everytime i launch the game, stating "Unknown error"

### Crash Report file

https://pastebin.com/BKvTFmmt

**Comment by EmqsaGit** [comment]
Sodium... is fabric-only?

**Comment by Leo40Git** [comment]
Okay, for one thing, this crash isn't even caused _by_ Sodium, it seems to be being caused by whatever `Essential (forge_1.12.2).jar` is (which is apparently doing some relaunch shenanigans, oh boy).

And Sodium is a Fabric mod! If this crash didn't happen, Forge would've told you "hey, this isn't a Forge mod so I couldn't load it".

**Comment by jellysquid3** [comment]
This user closed their issue moments after opening it, and it's been sitting dead/closed for weeks.

There is no reason why this discussion needs to take place. It's been solved.
