### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by PRRB** [jellysquid3/Sodium#1167]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar

### Reproduction Steps

Just walking around my base and game crashes. No specific action. No other details, sorry :(

### Crash Report file

[hs_err_pid19788.log](https://github.com/CaffeineMC/sodium-fabric/files/8008622/hs_err_pid19788.log)

**Comment by silversquirl** [comment]
Could you send an Alt+F3 screenshot so we can see your system info?

**Comment by 630R63** [comment]
I am getting the same issue. After playing for a while, the game suddenly crashes because a chunk couldn't be rendered or something (part of the stacktrace: me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.executeDrawBatches).

Here is the log attached: [hs_err_pid8804.log](https://github.com/CaffeineMC/sodium-fabric/files/8814714/hs_err_pid8804.log)

Also, since you were asking the other person to provide screenshots, I will do it for my system.
![2022-06-01_16 53 07](https://user-images.githubusercontent.com/6078866/171421286-129b6002-c17e-46b1-84a8-191c899a89e6.png)


Please let me know if there is any other info I can help you with. I really want to get to the bottom of this because the crash happens every time I play.

Thank you!
