### ISSUE TITLE
`sodium-fabric` fails to build on JitPack

### ISSUE THREAD

**Issue by minerva** [jellysquid3/Sodium#1191]
### Version information

mc1.18.1-0.4.0-alpha6

### Expected Behavior

`sodium-fabric` should be available to developers via JitPack.

### Actual Behavior

`sodium-fabric` is currently unavailable on JitPack due to build failures caused by an outdated Java version (`8`).
I've created an issue report on the JitPack repo https://github.com/jitpack/jitpack.io/issues/4991#issue-1146376800.

### Reproduction Steps

Search `sodium-fabric` on JitPack and check out the build log for the latest available tag (https://jitpack.io/com/github/CaffeineMC/sodium-fabric/mc1.18.1-0.4.0-alpha6/build.log).
Assumedly this causes `sodium-fabric` to be unavailable as a Fabric mod dependency.

### Java version

17

### CPU

i7-8700k

### GPU

AMD RX 5700XT

**Comment by FlashyReese** [comment]
An alternative option is using [Modrinth Maven](https://docs.modrinth.com/docs/tutorials/maven/).

**Comment by jellysquid3** [comment]
We don't support using JitPack, and will probably remove the manifest file from our repository soon. It offers a very poor experience for developers and often messes Gradle up pretty badly. I also don't feel like keeping a bunch of workarounds in the repository to keep it working.

If you need to include a release version of Sodium in your project dependencies, use the Modrinth Maven instead as FlashyReese linked above, as it's much more straightforward.

Otherwise, if you need a specific revision, try using [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to check out the specific version of Sodium next to your project, and then [Gradle Composite Builds](https://docs.gradle.org/current/userguide/composite_builds.html) to include it in the dependency tree as an independent build. This will almost always offer a less buggy experience.
