### ISSUE TITLE
Chunk loading lag.

### ISSUE THREAD

**Issue by AdriankoAgent007** [jellysquid3/Sodium#1228]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

I expected sodium to minimize my lag spikes which it did but it forgot one thing "chunk lag" 

### Actual Behavior

i'm playing on 8 render distance and whenever a new chunk loads i drop from 200-250 to 30-40 and it lasts for atleast 3 seconds i don't know what to do i even tried fixing the issue but nothing seems to work.(sorry for my bad english)

### Java version

Java 17.0.1 64bit

### CPU

I5-2400

### GPU

gtx750 ti

**Comment by hassanaigehazim** [comment]
Yeah, I have the same problem too.

**Comment by Chirynnn** [comment]
If only developers would focus on this several months old issue that's been plaguing this mod.

**Comment by jellysquid3** [comment]
Making passive-aggressive remarks on this issue tracker is not the way to get your problem fixed. We only recently went from being a one-person show to having multiple people available to work on the project. And as of recently, we've started setting up remote machines so that developers can debug hardware/drive-specific issues.

These things take time. We don't ignore things. It's just a lot harder than you think it is.

**Comment by MeeniMc** [comment]
Possibly https://bugs.mojang.com/browse/MC-224578; this is resolved in 1.20.

**Comment by jellysquid3** [comment]
Per changes in policy on our issue tracker, we are closing issues which are general inquiries about performance issues and such. If you are experiencing performance issues and need help, then please use the [Discord server](https://caffeinemc.net/discord).
