### ISSUE TITLE
Stuck at low FPS

### ISSUE THREAD

**Issue by MumChum** [jellysquid3/Sodium#1293]
I have Sodium installed and am using shaders. I haven't played the game for about a week, however the last time I did it worked perfectly fine, high frame rates and all.

Now, though, the FPS counter tells me I'm getting 240FPS, yet I can see that the game itself is running at 60FPS max and there's tearing too. I've tried turning V-Sync on and off, messing with FPS cap settings, even my monitor's refresh rate settings but all to no avail. I've removed all the mods and reinstalled them but still no different. And no, turning off shaders altogether has made no difference either. 

Can anyone help me with this issue? Thanks.

**Comment by openpressure** [comment]
Yes, same thing happens with version 0.4.1 for sodium 1.18.2. Uninstalling all mods and installing sodium from a new .minecraft folder works the same thing. Interestingly, this only works when in 'windowed mode'. Switching from full screen mode to windowed mode gives you smooth fps as short as 2 minutes or as long as 10 minutes, but in the end it locks to 60 fps.
I hope this issue is resolved quickly. :)

**Comment by jellysquid3** [comment]
Per changes in policy on our issue tracker, we are closing issues which are general inquiries about performance issues and such. If you are experiencing performance issues and need help, then please use the [Discord server](https://caffeinemc.net/discord).
