### ISSUE TITLE
Mooshroom cow mushrooms flicker with some resourcepacks

### ISSUE THREAD

**Issue by Dutchlikeme** [jellysquid3/Sodium#1335]
### Version information

mc1.19-0.4.2+build.16

### Expected Behavior

The mooshroom's mushrooms do not flicker.

### Actual Behavior

When using a resourcepack, the mooshroom cow's mushrooms flicker at rapid speed.

### Reproduction Steps

Mods used :
Fabric api 0.55.3 1.19
Modmenu-4.0.0
Sodium fabric mc1.19 0.4.2build.16

Resourcepacks used:
Jicklus+1.19 (needs optifine for varied mobs, but is not neccesary)
Mythic 1.19

Spawn in a mooshroom cow
The mushrooms on top flicker

### Java version

17.0.3 64bit

### CPU

Intel i5-10500H

### GPU

RTX 3060 Laptop GPU

### Additional information

It looks as if the resourcepack has varies of places for the mushrooms to be placed onto a mooshroom cow, but instead of choosing one spot it keeps going through all spots

Think of it as led light bulbs, they're going on and off in an order with the same rhythm

![image](https://user-images.githubusercontent.com/100804523/174095721-d947a00d-4e68-41d5-a90c-929a304ad7d4.png)
![image](https://user-images.githubusercontent.com/100804523/174095840-026f8b4a-6164-4490-b579-02bb11f9ea3e.png)
![image](https://user-images.githubusercontent.com/100804523/174095980-68f315dc-5dca-4e01-bd00-41ac673c965e.png)

**Comment by Dutchlikeme** [comment]
Fixed by installing the mod JMX
Jmx Fabric mc119 1.22.251.jar

**Comment by teenangst** [comment]
> Fixed by installing the mod JMX
> Jmx Fabric mc119 1.22.251.jar

This does not fix it, it simply slows down the switching and the switching happens when they walk as well as showing additional mushroom textures around the mooshroom. I would really appreciate if this issue were to be fixed, I like the resource pack, I like living on mushroom islands, and I like shaders but currently I can't have all 3.

Video with JMX and Sodium: https://cdn.discordapp.com/attachments/378081613331955712/1013819938907103373/javaw_8qmb2B3lQK.mp4

Video without JMX but with Sodium: https://cdn.discordapp.com/attachments/378081613331955712/1013819840018002011/javaw_ePRRkEphHM.mp4

Video with neither (also notice that the mushrooms are only on top of the mooshrooms not around the sides): https://cdn.discordapp.com/attachments/378081613331955712/1013820036651171860/javaw_USqtEaThJ9.mp4

The resource pack I am using is Faithless

Edit: also, JMX turns transparent textures into white when the item has been dropped or are in item frames
