### ISSUE TITLE
Debug chunk boundary rendering does not work

### ISSUE THREAD

**Issue by belak** [jellysquid3/Sodium#134]
### Expected Behavior

When chunk boundary rendering is on, boundaries between chunks should be rendered.

### Actual Behavior

There are no rendered chunk boundaries

### Reproduction Steps

1. Press F3+G to enable chunk boundaries
2. See that chunk boundaries are not rendered

### System Information

- OS: macOS 10.14.6
- Java Version: 1.8.0_74 64bit
- CPU: i7-7820HQ
- GPU: Radeon Pro 660
- Fabric Loader 0.9.0+build.204-1.16.1

**Comment by Miros77** [comment]
it works for me

**Comment by Miros77** [comment]
OpenGL 3.0 renderer, which can be found in Video Settings > Performance.

**Comment by Miros77** [comment]
https://github.com/jellysquid3/sodium-fabric/issues/24

**Comment by LucilleTea** [comment]
Can you see if it works in a fresh world?

**Comment by belak** [comment]
As far as I can tell, it's stuck at `Oneshot (GL 2.0)` for some reason even though macOS *should* support 3.0. Also, I don't see "Video Settings > Performance", though I do see the renderer in "Video Settings > Advanced".

This was originally seen on a server but it also happens in a fresh world as well.

**Comment by jellysquid3** [comment]
I cannot reproduce this issue. There might be some kind of specific weirdness with the OpenGL driver in macOS.

> As far as I can tell, it's stuck at Oneshot (GL 2.0) for some reason even though macOS should support 3.0.

Minecraft still uses parts of the fixed-function pipeline in rendering, which means that in order to use modern OpenGL features, it needs to use a compatibility profile. macOS does not support these compatibility profiles, and generally it also doesn't support any extensions which would otherwise allow us to use these newer features in older versions of OpenGL. 

So, at best, you're stuck with OpenGL 2.1 when playing Minecraft on a Mac computer. We can't do anything about this until Mojang makes the necessary changes in their game, unfortunately.

**Comment by belak** [comment]
So, when using `./gradlew runClient` the chunk boundaries display, but when copying the mod into the mods folder of the current MC profile, it doesn't display.

Is there anything else I could do to help debug this?

**Comment by amnotbananaama** [comment]
Hi @belak, I've spent a few days trying to reproduce this. When that failed, I tried looking for someone with access to your hardware configuration. FemoralArtistry suggested in JellySquid's discord that you may have `reducedDebugInfo` enabled in your personal instance. This would hide the chunk borders (something I was not aware of). This would explain why it works in a dev environment, but not in your personal instance.

Can you try disabling it, and let us know if that fixes the issue? To do so, set `/gamerule reducedDebugInfo false` (if applicable), then check `Options > Chat Settings > Reduced Debug Info`.

**Comment by amnotbananaama** [comment]
Closing after 90 days without response from the reporter

**Comment by nununoisy** [comment]
Bumping this thread to say that the solution above worked for me. I am using Multidraw (GL 4.3) on Windows 10, and chunk borders did not appear until I changed `Options > Chat Settings > Reduced Debug Info` to `OFF`.
