### ISSUE TITLE
Terrain not rendering, everything else is rendering correctly.

### ISSUE THREAD

**Issue by ZedDevStuff** [jellysquid3/Sodium#1345]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16

### Expected Behavior

The terrain should load correctly and be visible

### Actual Behavior

The terrain is invisible and i have extreme framerate issues (1-10 FPS if i move)

### Reproduction Steps

This is probably specific to my computer but i have no way of being sure because Sodium works absolutely fine in 1.16.5.
Just open the game and enter a world, singleplayer or multiplayer.

### Java version

jdk-18.0.1.1

### CPU

Intel Core 2 Duo T7700

### GPU

ATI Radeon HD 2600 Pro (appears as ATI Mobility Radeon 2600 XT on windows)

### Additional information

Using at the time of writing the latest version of Cloth config, fabric API, lambdynamic lights, modmenu, reeses sodium options, sodium extra, starlight and WI zoom. Removing them doesn't change anything.
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/8935502/latest.log)
![2022-06-19_12 23 08](https://user-images.githubusercontent.com/98429642/174480969-8f16ece5-5bef-43e2-af17-7e0ab7483630.png)

**Comment by burgerindividual** [comment]
If you could try to update your drivers, that may fix the problem. If that doesn't work, your GPU may only have up-to-date enough drivers on linux. Technically, sodium 0.4.0 and higher requires OpenGL 3.3 core, but your current drivers report supporting OpenGL 3.2 core.

**Comment by Phoenix-Starlight** [comment]
A modern Linux distribution or Radeon HD 2600 XT Windows driver, version 6.14.10.11251+ will bump up the needed OpenGL support.
It's a bit hard to guess since I don't have AMD, but OpenGL 3.3 came out in 2010. So these drivers for windows will probably provide the needed support. https://www.amd.com/en/support/graphics/amd-radeon-hd/ati-mobility-radeon-hd-2000-series/ati-mobility-radeon-hd-2600-xt
