### ISSUE TITLE
Fetal crash about renderer and possible memory leak

### ISSUE THREAD

**Issue by EGOIST1372** [jellysquid3/Sodium#1355]
### Version information

Sodium mc1.19-0.4.2

### Reproduction Steps

recently I added Atmosfera, Farsight and Illumination mods in 1.19 so IDK whats the problem.
Also I'm using Quilt with 120+ mods and it's the first time it happened so it's probably not Quilt.

### Crash Report file

latest log in Minecraft folder
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/8960628/latest.log)

Crash report from Java runtime
[hs_err_pid33972.log](https://github.com/CaffeineMC/sodium-fabric/files/8960638/hs_err_pid33972.log)

**Comment by Fourmisain** [comment]
The logged errors of Konkrete/FancyMenu caught my eye.
Since FancyMenu is rendering related, maybe the errors are causing some memory to not be freed? Though it surely wouldn't leak _that much_, right?
In any case, I've reported it here https://github.com/Keksuccino/FancyMenu/issues/306.

Farsight seems like the most likely candidate, though at the same time I haven't heard of any conflicts with it, so I'm not sure where the leak is coming from.

**Comment by Keksuccino** [comment]
I'm pretty sure the error caused by Konkrete wasn't causing a memory leak, but just to be sure, please update to Konkrete v1.3.3-3 and see if it still happens.

**Comment by EGOIST1372** [comment]
After updating Illumination (said fixed a crash bug) and konkrete (switching between modes with F3+F4 fix) seems I get no crash so far. I will update this issue if any crash happened again. thank you both for helping <3

**Comment by Fourmisain** [comment]
I should have asked this much earlier but what did you set your max heap space (`-Xmx` JVM argument) to?
I think the vanilla launcher sets it to only 2GB, which I'd expect to be too little when using a mod like Farsight, try increasing it to something like 4GB.
Maybe there is/was no memory leak afterall and you just ran out of heap space.

**Comment by EGOIST1372** [comment]
I actually have set it to 6GB long time ago. And I have 32GB ram so I can
increase it to 8GB but I think that's unnecessary.

**Comment by Fourmisain** [comment]
Oh yeah, 6GB is hard to fill with fabric/quilt mods, memory leak it is.

Did you travel through nether portals a lot?
There's currently PR #1259 that fixes a memory leak related to that - and Farsight would make it worse I believe.

**Comment by EGOIST1372** [comment]
In that session of game I don't recall to going to nether at all. But I was
switching a lot between creative and survival and I tp to a swamp that
after exploring a bit in there game starts to drop fps significantly and
eventually when it was under 60 fps, crashed the game. It was like something
building up and making it worse.

**Comment by burgerindividual** [comment]
Your graphics card seems to be running out of VRAM. Can you post your computer specs?

**Comment by EGOIST1372** [comment]
Core i7 6700hq
GeForce GTX 980m 8GB DDR5x
32GB ram
4K display
Basically my old laptop in a nutshell

**Comment by Fourmisain** [comment]
I may have just randomly stumbled upon the solution to this issue while browsing mods.
You have [ForgetMeChunk](https://www.curseforge.com/minecraft/mc-mods/forgetmechunk) installed and its description states:
> ForgetMeChunk is a simple client side mod that prevents light map unloads on the client, this eliminates the fps drops caused by crossing certain chunk borders
>
> However **this casues a memory leak**, this memory leak is reset by changing dimension or leaving the server/world, **So use at your own risk**

This fits the bill since you didn't change dimensions and Farsight most likely accelerated this leak because more chunks got unloaded.

P.S.
I remember seeing that mod maybe a few weeks ago and its description read differently, so I checked its history and it was indeed [changed relatively recently](https://github.com/mjwells2002/ForgetMeChunk/commit/3c517345b870752298dcac1aa53bab4dd5f69d3a).
Kinda worrying how many modpacks include the mod.... 😥

**Comment by mjwells2002** [comment]
Just hopping on here to resay what i just said in the sodium discord that yes this issue is most liekly caused by ForgetMeChunk, PhiPro pointed out this small memory leak a while ago and i have been working on a better solution, but yes that is liekly the cause of your problems, especially if your playing at high render distances

**Comment by EGOIST1372** [comment]
it seems the culprit was forgetmechunk and after removing it game was much more stable
