### ISSUE TITLE
Video settings say Max Framerate is 120 but it is 5

### ISSUE THREAD

**Issue by Waseem973** [jellysquid3/Sodium#1365]
### Version information

Sodium 0.4.2 for Minecraft 1.19

### Expected Behavior

Show that the Max Framerate is 5 and not 120 on the Video Settings

### Actual Behavior

When I change my Max Framerate to 5 and close the Video Settings and open it again it says the Max Framerate is 120 but it still is 5.

### Reproduction Steps

1. Press Esc
2. Hit on "Options"
3. Hit on "Video Settings"
4. Change Max Framerate to 5
5. Hit "Apply"
6. Hit "Done" To get out of the Video Settings
7. Go back to Video Settings by pressing "Video Settings"
8. It will say that the Max Framerate is 120 but it actually is still 5.

### Java version

17.0.3

### CPU

AMD Ryzen 5 5500U

### GPU

Integrated Graphics

### Additional information

Mods I use: FerriteCore, Fabric API, Lithium, Phosphor, and Sodium.

**Comment by burgerindividual** [comment]
I have a local fix for this on my machine. To temporarily fix it, you can try messing with the slider more, or modify the options.txt file in minecraft. Because minecraft now verifies inputs for options, and it only allows a minimum framerate of 10, it bugs out when sodium lets you set it to 5. I'll push this when I get the chance.

**Comment by Oyssis** [comment]
Hey I don't think only setting it to 5 is a bug
I tried every number with five in it it reverts it without a five for example if you choose 85 it says 80 and if you choose 95 then its 90 for every number
