### ISSUE TITLE
Some edges of block hitboxes sometimes don't render depending on the viewing angle

### ISSUE THREAD

**Issue by violine1101** [jellysquid3/Sodium#140]
### Expected Behavior
All edges of the block outline should show, just like in vanilla:

![2020-07-22_16 22 23](https://user-images.githubusercontent.com/12451842/88188012-90a19e80-cc37-11ea-82e0-39c63608e196.png)

### Actual Behavior
When looking at a block from certain angles, some edges of the block outline / hitbox don't show:

![2020-07-22_16 03 50](https://user-images.githubusercontent.com/12451842/88188036-99927000-cc37-11ea-8b2d-4488ca434665.png)

### Reproduction Steps
Look at a block from a certain angle if there's another block next to it. Here's a screenshot with the F3 screen open:

![2020-07-22_16 03 54](https://user-images.githubusercontent.com/12451842/88188115-b3cc4e00-cc37-11ea-8138-e40e0779b45f.png)

When switching into third-person mode, the hitbox renders properly, probably due to the different position of the camera.

### Tested versions
The bug doesn't happen in vanilla 1.16.1, but it does happen with Sodium 0.1.0-fabric. Couldn't test newer commits since I didn't manage to get sodium running without crashing.

I'm using fabric version 0.9.0+build.204 (latest) and Minecraft version 1.16.1.

### System Information
- Java Version: 1.8.0_51 *and* 12.0.1
- CPU: Intel Core i7-3770 @ 3.40 GHz
- GPU: GeForce GTX 1050 Ti

**Comment by violine1101** [comment]
Just tested this in 620f5a3669be298244bda70cb20cf2e1df8f53b9 and there the issue doesn't seem to happen.

**Comment by Zirvac** [comment]
The bug seems only present with the 0.1 release from Curseforge and Github (https://github.com/jellysquid3/sodium-fabric/releases).

With https://github.com/jellysquid3/sodium-fabric/commit/885222a476b7054ae428031d72c0b47fa579872a from « Actions » tab or compiled myself (with java 14) there was no problem, neither with some other commit.

Some screen from Github’s release:
![2020-07-25_16 58 17](https://user-images.githubusercontent.com/19183047/88460345-e2e2f980-ce9b-11ea-8821-2e0b7e962942.png)
![2020-07-25_16 58 19](https://user-images.githubusercontent.com/19183047/88460346-e4142680-ce9b-11ea-8b5e-48d2d057ca9d.png)
![2020-07-25_16 58 25](https://user-images.githubusercontent.com/19183047/88460348-e4142680-ce9b-11ea-9e4b-4e344e53138b.png)
![2020-07-25_16 58 29](https://user-images.githubusercontent.com/19183047/88460349-e4acbd00-ce9b-11ea-807d-a4bf3e5cea45.png)
![2020-07-25_16 58 33](https://user-images.githubusercontent.com/19183047/88460350-e5455380-ce9b-11ea-9cab-398eccdff322.png)

**Comment by jellysquid3** [comment]
Merging into #182.
