### ISSUE TITLE
gamma

### ISSUE THREAD

**Issue by RayanAlanazii** [jellysquid3/Sodium#1416]
when i use both sodium and vanilla tweaks gamma resourcepack (fullbright) gamma dont work

**Comment by nhatsun** [comment]
there's a mod call gamma ultils, i think u should try that if it could help ? :)

**Comment by MrGazdag** [comment]
If I understand correctly, you're using the VanillaTweaks Fullbright addon, and trying to set your gamma levels in the settings menu. If you look at the description of the VanillaTweaks addon, you'll see a warning about Sodium.
![image](https://user-images.githubusercontent.com/44264503/184548164-bc53f307-9163-4e43-b993-66ef07cb38f8.png)
This is because the addon uses core shaders, which are overridden by Sodium and Optifine. Sodium does not support vanilla shaders, which is understandable as they're basically overriding the rendering methods used in the game (hopefully they will support core shaders someday, as they give lots of creative freedom). This issue is expected, and probably not Sodium's fault, so a fix is unlikely.
