### ISSUE TITLE
Little FPS boost

### ISSUE THREAD

**Issue by miythyi** [jellysquid3/Sodium#151]
I downloaded in sodium and I have 160 average FPS but in vanilla, I had 120 FPS but in the pictures and videos people have posted they have a 300 to 600 Fps Boost.
I have no mods installed
But when i tried it with phosphor and lithium and sodium together I get 220 Fps still not a big jump.

**Comment by miythyi** [comment]
Oh yeah and I downloaded 55 mods with sodium, phosphor, and lithium it stayed about 190 Fps I'm wondering why are more mods better than without mods

**Comment by amnotbananaama** [comment]
Sodium is not a magic cure-all. The amount of improvement can vary dramatically from system to system depending on hardware, configuration, drivers, and other factors. To help you we would need to know more of these factors. It's probably best if you join [Jellysquid's discord](https://jellysquid.me/discord) so that you can ask and answer questions about your system without spamming the issue tracker.


The information from the issue template would be a good start:
> ### System Information
> You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.
>
> - Java Version: [fill me in]
> - CPU: [fill me in]
> - GPU: [fill me in]

Additionally, a screenshot of the [Profiler Graph](https://minecraft.gamepedia.com/Debug_screen#Profiler_graph) and [Frame Time Graph](https://minecraft.gamepedia.com/Debug_screen#Frame_time_graph) would go a long way to suggesting improvements for you.

**Comment by miythyi** [comment]
i got 300 fps when i got in and 170 when 5 mins past
im playing on an Asus Tuf a15 Gaming laptop
Java version: 8 version 261
CPU: AMD Ryzen 4800H
GPU: RTX 2060
![2020-07-22_20 31 32](https://user-images.githubusercontent.com/68670238/88242173-74fbbf80-cc5a-11ea-8a5a-8dcb7b47eb47.png)
![2020-07-22_20 29 55](https://user-images.githubusercontent.com/68670238/88242177-79c07380-cc5a-11ea-83cd-5a7a09918b82.png)

**Comment by Artoria2e5** [comment]
You should probably update your Java to use some fancy new whatever optimizations the Java people have come up with. See https://gist.github.com/jellysquid3/8a7b21e57f47f5711eb5697e282e502e.

**Comment by Altirix** [comment]
>i got 300 fps when i got in and 170 when 5 mins past
>im playing on an Asus Tuf a15 Gaming laptop

that sounds like thermal throttling

**Comment by jellysquid3** [comment]
This issue is a question, not a bug report. Questions should be asked on the [official Discord server](https://jellysquid.me/discord).
