### ISSUE TITLE
chunks acting like they should be culled

### ISSUE THREAD

**Issue by kinglarry4444** [jellysquid3/Sodium#1527]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Expected Behavior

i expected all the chunks around me to be fully loaded all the time

### Actual Behavior

i have all the culling settings disabled but some times chunks wont load, i have confirmed its sodium causing the issue.

### Reproduction Steps

make a big wall 
look past it 
chunks arnt loaded

### Java version

java 19.0.1 64 bit

### CPU

amd ryzen 2700x

### GPU

1660ti

### Additional information

https://imgur.com/9x0JWgm

**Comment by burgerguy** [comment]
Chunk sections (16x16x16 portions of chunks) will only be loaded on the player's end to be rendered if it passes culling. This is done intentionally because it allows a *lot* of underground chunk sections to skip being rendered while looking the same. The server will still load these chunks, however, and they will still be ticked.

**Comment by burgerindividual** [comment]
My bad, didn't see the image attached at the bottom. This seems like a similar issue to #872 and might be fixed on the 1.19.x/next branch, but I'll need to test it.

**Comment by kinglarry4444** [comment]
> My bad, didn't see the image attached at the bottom. This seems like a similar issue to #872 and might be fixed on the 1.19.x/next branch, but I'll need to test it.

yea i think it is the same issue

**Comment by pajicadvance** [comment]
Marked as duplicate of #872.
