### ISSUE TITLE
Adjust 'safe area' off-screen where objects are not culled

### ISSUE THREAD

**Issue by bonkmaykr** [jellysquid3/Sodium#1553]
**Is your feature request related to a problem? Please describe.**
When using world curvature shaders, blocks near the edge of the screen naturally get pulled closer to the center of the display to create the effect, meaning that highly aggressive frustum culling can create annoying artifacts near the edge of the screen. This happens with not only entire chunks but also individual polygons (usually grouped together on sides of buildings etc.)

**Describe the solution you'd like**
I would like an option that allows some portion of the visuals off-screen to not be culled within a certain distance.

**Describe alternatives you've considered**
No alternatives are available to me.

**Additional context**
Video proof of the problem:
https://files.worlio.com/users/bonkmaykr/media/sodium-curves.mp4

Shaders used: BSL v8.2.01

**Comment by jellysquid3** [comment]
I don't see how we'd implement this. What you're trying to render does not conform to a standard view frustum, so "extending" the frustum won't really fix the problem. You'd just have to disable frustum culling entirely to solve the problem, or implement some specific solution for the shader pack.

**Comment by douira** [comment]
GIven that this is a thing concerning shader packs you are better off asking Iris for something like this, they might actually look into it (shader packs do weird things). However, the solution is likely just to not do frustum culling because communicating the extent of the frustum culling is complicated and weirdly specific. I believe iris already has an option where shader packs can tell it to disable frustum culling for purposes like this and voxelization.
