### ISSUE TITLE
Crash on startup(me.luligabi.noindium.NoIndiumWarningScreen?)

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1588]
### Version information

sodium 0.4.8+build.22

### Reproduction Steps

1. Try to run game
2. Game crashes

### Crash Report file

https://paste.gg/p/anonymous/122e4d38c90c48f3aa59c53216baf1fa

**Comment by GhostIsBeHere** [comment]
Perhaps try removing the "No Indium" mod, that seems to be the problem

**Comment by LucilleTea** [comment]
The "No Indium" mod is bundled by AE2 which requires Indium, so removing it individually isn't an option.
Since you don't have Indium in your mod list you should definitely add it, AE2 needs it, and that may avoid the No Indium warning screen which is crashing.
That said, the issue looks like No Indium not being compatible with the minecraft version you're using, so AE2 including it may also be incompatible, you should make sure you're using the correct mod versions.

Closing since none of this is a sodium issue.
