### ISSUE TITLE
All blocks turn invisible

### ISSUE THREAD

**Issue by 0utl4nder** [jellysquid3/Sodium#1590]
### Version information

mc1.18.2

### Expected Behavior

fps boost, as seen in your modrinth sodium post. 

### Actual Behavior

i have more fps, but nothing except entities render

![image](https://user-images.githubusercontent.com/117042369/215147189-c7e03482-f807-4d1e-9834-cbaff7585675.png)

### Reproduction Steps

I dont know how this happend, just downloaded all your mods, sodium, lithium, phospor, and added sodium extra and reeses sodium options, all the mods in 1.18.2 version with fabric api 0.67 1.18.2. Vanilla launcher.

### Java version

17

### CPU

Intel i7-2670QM (8) @ 3.100GHz 

### GPU

Intel 2nd Generation Core Processor Family 

### Additional information

i play in Linux and always had the bad performance issue, i tried to change the launcher, java version, and now the mods.

i give 4 gb of ram to mc (i have 8).

**Comment by Timolino456** [comment]
Try updating your Intel graphics drivers (use the Intel website, not the Windows update thing).

**Comment by LucasRitossa** [comment]
I am also experiencing this issue running 1.18.2 via prism-launcher on Arch Linux.

**Comment by ovensplit** [comment]
I get a similar issue, but only while using [zink](https://docs.mesa3d.org/drivers/zink.html)

**Comment by IMS212** [comment]
The issue with Zink was [just fixed](https://github.com/CaffeineMC/sodium-fabric/commit/d56ea64da218961b9f89ba586de7731464de7f5e).

**Comment by wilsontulus** [comment]
> Try updating your Intel graphics drivers (use the Intel website, not the Windows update thing).

Maybe try to read better as the issue clearly stated that they're using a Linux distro for playing Minecraft,
Updating the "graphics driver" in Linux works in a different way if you're not using proprietary graphics drivers such as NVIDIA. It is done by updating the Linux kernel and Mesa Graphics Libraries instead, thus making even 10 or 15 year old graphic cards actually maintainable to this day.

For another fact, using the 2nd generation Intel HD Graphics and older to play Minecraft >= 1.17 is a borderline impossible task on Windows, because Intel only gives OpenGL 3.1 to it's Sandy Bridge graphics driver, borderline right before the version 3.2 required by Minecraft itself. Because of that, the only ways to play Minecraft Java Edition later than 1.17 on these old iGPUs, is by using a Linux distro which fortunately supports up to OGL 3.3 on Sandy Bridge Graphics, or if you want to keep using the Microsoft's OS, suffering from software rendering is required.

**Comment by jellysquid3** [comment]
Per our new [hardware support policy](https://github.com/CaffeineMC/sodium-fabric/blob/3f12f36e58d977f417d22ea6e643a9d7aeb4f0ca/README.md#-hardware-compatibility), your graphics card does not meet the required specifications. As such, this issue is being closed as "won't fix."
