### ISSUE TITLE
Insane micro-stutter when exploring new chunks on 1.19.3 with latest NVIDIA driver 528.24

### ISSUE THREAD

**Issue by Shurelia** [jellysquid3/Sodium#1594]
### Version information

sodium-fabric-mc1.19.3-0.4.8+build.22

### Expected Behavior

Exploring new chunks with NVIDIA driver 522.25, stutter only affect in tps
![2023-01-30_08 27 34](https://user-images.githubusercontent.com/33577181/215369182-c2a6891d-3677-4dd4-8d9b-cc29797d19e0.png)

### Actual Behavior

Exploring new chunks with latest NVIDIA driver 528.24, causing stutter in fps
![2023-01-28_23 56 37](https://user-images.githubusercontent.com/33577181/215369031-261691b2-207e-46f7-b811-18af6f7371f2.png)

### Reproduction Steps

1. Create a new singleplayer world
2. Wait for a while till everything loaded
3. Start exploring to generate new chunks

### Java version

OpenJDK 17.0.5

### CPU

i3-10105F

### GPU

GTX 1660 Ti

### Additional information

Threaded Optimization on nvidiacp is already disabled on both versions.
possibly related threads with some more informations
 https://canary.discord.com/channels/602796788608401408/1068945223805325414
 https://canary.discord.com/channels/602796788608401408/1067920269315940403
 https://canary.discord.com/channels/602796788608401408/1067408887420043315

**Comment by Clony1337** [comment]
you fix it?

**Comment by Atirtra** [comment]
This problem exists solely because of this issue: https://github.com/CaffeineMC/sodium-fabric/issues/1486

Basically what is happening is that due to a crash caused by newer NVIDIA's drivers, newer sodium versions hide Minecraft from the drivers to prevent the crash. Side effect of this is that the drivers aren't able to provide proper optimizations for the game anymore resulting in these awful stutters no matter which NVIDIA card you have.

Any driver above 526.47 has this issue and to fix it, we should mass report the problem to NVIDIA with their form for driver issues: https://forms.gle/kJ9Bqcaicvjb82SdA

**Comment by IMS212** [comment]
As said above, related to 1486.
