### ISSUE TITLE
Requesting a No Error Context causes a crash at startup on Wayland 

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#1624]
### Description

If you are using a patched version of GLFW to enable Wayland support, the following error may occur.

```
GLFW error 65543: EGL: Failed to create context: An unrecognized attribute or attribute value was passed in the attribute list.
Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).
```

This is caused by a change in Sodium 0.4.10 which makes it so a _No Error Context_ is requested by default, in order to help reduce CPU overhead when executing draw calls. However, it seems that GLFW cannot properly pass the hint along when using Wayland, or that something else is going wrong in the stack.

We should try to find (or open) a bug report with upstream if we can find the culprit.

### Workaround

The user can disable the use of a _No Error Context_ by modifying the configuration like so:

```json
    "use_no_error_gl_context": false
```

Seeing that users are already replacing system libraries, it seems reasonable enough to me that those users also be asked to edit their configuration file once to workaround the issue. I don't see an obvious way we can detect this problem, and I don't want to disable the use of No Error Contexts by default on Linux.

**Comment by NothingSpecific** [comment]
If this happens reliably on all Wayland systems, you could try querying the `$XDG_SESSION_TYPE` environment variable on *nix systems to determine whether a system is running X11 or Wayland (note: since BSD-based systems can run Wayland, you need to check this on all *nix systems, not just Linux-based systems).

**Comment by RaptaG** [comment]
I can reproduce this issue on Fedora Kinoite 38 with Wayland

**Comment by orowith2os** [comment]
> If this happens reliably on all Wayland systems

Considering you need a patched GLFW to even get Minecraft *starting* on Wayland, it should. So checking `XDG_SESSION_TYPE` should be reliable enough.

**Comment by Scrumplex** [comment]
> This is caused by a change in Sodium 0.4.10

I was only able to reproduce this on 0.4.11 so far

**Comment by rhjdvsgsgks** [comment]
fixed by https://github.com/glfw/glfw/commit/eeeb56eb23c9a23866e8042fb23d7b0b4d96d106 . as a solution before it been tagged, you can use [glfw-git](https://aur.archlinux.org/packages/glfw-git) with env var `XDG_SESSION_TYPE=` (to prevent `NO_ERROR_CONTEXT_UNSUPPORTED` workaround been used) and `DISPLAY=` (to force wayland). or simply set [`MESA_NO_ERROR=1`](https://docs.mesa3d.org/envvars.html#envvar-MESA_NO_ERROR)

**Comment by jellysquid3** [comment]
That's great news. When that changeset has been tagged, we'll update the workaround to check the GLFW version before applying.

**Comment by leo60228** [comment]
(Bumping this issue, GLFW 3.4 was released with that fix in February.)
