### ISSUE TITLE
Sudden and infrequent flashing squares in the sky

### ISSUE THREAD

**Issue by HeyyoCoffeeHere** [jellysquid3/Sodium#1640]
### Version information

mc1.19.3-0.4.9+build.23

### Expected Behavior

The sky not flashing

### Actual Behavior

The sky flashes one or more large blue and white squares when the player moves towards unloaded chunks. Unfortunately, I couldn't get a screenshot of this happening due to their infrequent and sudden nature.

### Reproduction Steps

1. Load into your world.
2. Lower your render distance to 7-12 (I am still unsure if this affects anything)
3. Fly around for a bit, looking up towards the sky.
4. They mostly appear in your peripheral vision so it might take a bit to actually catch them.

### Java version

Java 17.0.3

### CPU

Intel core i3-10105

### GPU

 Intel UHD Graphics 630 (I think)

### Additional information

The flashes seem to become more frequent with Lithium and indium installed.

**Comment by jellysquid3** [comment]
Ensure your graphics drivers are up-to-date by checking the [official Intel website](https://www.intel.com/content/www/us/en/download-center/home.html). We don't believe there is any reason that Sodium itself is causing this, and we've seen similar cases in our Discord server where the problem was just buggy drivers.
