### ISSUE TITLE
High gpu usage in pause menu relating to FPS cap.

### ISSUE THREAD

**Issue by Evo32** [jellysquid3/Sodium#1641]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

The fps when in the pause menu should be limited to the same value as in the game. EG I set 100 fps cap, in game my fps is 100, click 'ESC' my fps is still 100. My gpu usage should be low as the game is paused.

### Actual Behavior

When I set my fps cap to anything over 50ish, the fps shoots into the hundreds in the menus, and my gpu usage reaches 100%. It seems that FPS cap increases the max fps in the menu non-linearly, along with the game rendering minecraft completely while paused, causing high gpu usage only in the menu. 
Looking at F3, it shows minecraft reporting an fps value of 69, while amd's built in fps metrics are reading 169.

### Reproduction Steps

1. Set FPS cap
2. click 'ESC'
3. look at FPS
4. cry

### Java version

Java 19.0.1

### CPU

Ryzen 5 5600

### GPU

RX 6600

### Additional information

The mods I used are the base mods in the Cabricality 0.2.1 modpack, installed from multi-mc (pictured below)
![image](https://user-images.githubusercontent.com/96995161/221171369-06f155cf-c72f-49ec-9b51-910e86e6ca5e.png)

**Comment by pajicadvance** [comment]
Sodium does not change the FPS limit behavior in any way, this is likely caused either by driver settings or another mod.

**Comment by Felix14-v2** [comment]
> Sodium does not change the FPS limit behavior in any way

That's the point, vanilla Minecraft has a weird bug — when you unfocus fullscreen Minecraft, it starts eating extreme GPU resources in background. Moreover, there is an anomaly: if you open alt+F3, minimize and then focus the window, you will see that the FPS in the background has increased several times, and instantly returned to normal values when focusing on the window. Sodium make this even worse. Here's my old screenshots of this bug:
![Vanilla](https://github.com/CaffeineMC/sodium-fabric/assets/75726196/4c9788c6-cbe2-436c-a7b0-8d7ac7c5229a)
![Sodium](https://github.com/CaffeineMC/sodium-fabric/assets/75726196/0b46fb5e-f918-43ac-bbc4-33b0d5e6954a)
(For context, even with Sodium 0.5.0 my GPU can't reach more than 500 FPS in such scenes)

Maybe Evo just incorrectly identified the cause of the bug and started blaming the pause menu? Because when you minimize the window, Minecraft automatically opens it by default.

**Comment by Fnige** [comment]
Try remaking this with just sodium on its own

**Comment by Felix14-v2** [comment]
> Try remaking this with just sodium on its own

These screenshots are from my test instance with only Sodium installed (1st is a clear fabric, no mods at all).

Perhaps this is some strange behavior of Optimus graphics.
