### ISSUE TITLE
Sodium gives even less fps than optifine

### ISSUE THREAD

**Issue by V4N1TY** [jellysquid3/Sodium#1670]
### Version information

sodium-fabric-mc1.16.5-0.2.0+build.4

### Expected Behavior

Fps somewhere around 60-80 at least

### Actual Behavior

less fps than vanilla

### Reproduction Steps

1.Create an map .
2.Press f3 and look somewhere 

### Java version

The one the launcher gives to you?

### CPU

Intel core I3-550 3.20Ghz

### GPU

Intel UHD 630

### Additional information

This one is Sodium
![2023-03-22_21 13 55](https://user-images.githubusercontent.com/128638072/227018556-05de8394-fbe6-49db-a2a8-a5585e8ff206.png)
This one is Optifine
![2023-03-22_21 16 24](https://user-images.githubusercontent.com/128638072/227018561-ec72f59d-45e3-40e8-9943-2b8900f76934.png)
This one is Vanilla
![2023-03-22_21 37 48](https://user-images.githubusercontent.com/128638072/227018563-9fd90799-e152-40c8-8dcc-b516aba43c13.png)

**Comment by jellysquid3** [comment]
You are using a version of Sodium that is multiple years old. We do not provide support for it any longer. Significant optimizations have been made since then.

**Comment by V4N1TY** [comment]
> You are using a version of Sodium that is multiple years old. We do not provide support for it any longer. Significant optimizations have been made since then.
Well , is there any version that is newer and for 1.16.5?

**Comment by jellysquid3** [comment]
No. We haven't updated the version for MC 1.16 in years, and have no plans to.

I'm guessing the reason you are using such an old version is likely that your GPU is just not able to run newer versions. However, this is (mostly) a software problem, rather than a hardware problem.

While Minecraft 1.17 and later requires OpenGL 3.2, it does not actually use any _hardware features_ which OpenGL 3.x gives them. So it's possible with a much newer graphics driver, that you can trick Minecraft (with this [mod](https://modrinth.com/mod/forcegl20)) into thinking it is running on a OpenGL 3.x capable graphics card, and be just fine.

Unfortunately the only way you're going to get a more up-to-date graphics driver is to use an alternative operating system based on Linux, which still actually supports your hardware.

**Comment by V4N1TY** [comment]
I'm grateful for your help .
