### ISSUE TITLE
Random crash while in-game.

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#17]
used this mod with lithium,phosphor,carpet,tweakeroo,fastbench-fabric,fastfurnace-fabric:
mod is compiled and used with zulu java 15 early access.
here is the crash log:
[hs_err_pid5304.log](https://github.com/jellysquid3/sodium-fabric/files/4673039/hs_err_pid5304.log)

**Comment by ghost** [comment]
these aren't all the mods i'm using but the ones that offer performance gain,if the issue is not identified I can post my whole mod list.

**Comment by amnotbananaama** [comment]
I don't necessarily think this issue is caused by Sodium. I sometimes experience this error with no mods installed, just by using Java 14. Specifically, I have jdk-14.0.0.36-hotspot and Intel(R) HD Graphics 5500. The error persists with the Oracle and OpenJ9 builds, which leads me to believe this is a low-level incompatibility issue between Java 14+, Intel drivers, and OpenGL/LWJGL.

**Comment by ghost** [comment]
In the building instructions,
the author talks about a world generation generation crash with java 9+ and a mod to fix it(the voyager mod by @modmuss50) and I'm already using it,so it can't be that.
Also, the logs directly mention sodium(Not an expert so maybe this is unrelated to the problem)

**Comment by jellysquid3** [comment]
> zulu java 15 early access

Please try using Java 8 and see if this issue still occurs.

**Comment by ghost** [comment]
>  zulu java 15 early access
> 
> Please try using Java 8 and see if this issue still occurs.

Thanks for helping,
I will try that and report back.

**Comment by ghost** [comment]
@jellysquid3 
Hello again,
I have compiled and used the mod with java 8,
it all seemed good until it crashed with this report:
[hs_err_pid10208.log](https://github.com/jellysquid3/sodium-fabric/files/4739747/hs_err_pid10208.log)

As I said,if needed I will post my full modlist.
Best wishes.
Nifty-Neutron.

**Comment by jellysquid3** [comment]
It seems then that this isn't some special case of a weird interaction between the Intel drivers and newer versions of Java. Can you please provide the model of your CPU and GPU? You can [use `dxdiag` on Windows](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) in order to find this information.

**Comment by ghost** [comment]
I'm using a low-end laptop 
with:
CPU:Intel Celeron N3060
GPU:intel HD graphics 400

**Comment by jellysquid3** [comment]
I'm unable to reproduce this crash using the only system I have with integrated Intel graphics (a Linux machine running Mesa 20.0.7) regardless of graphics settings. This might be down to the Intel drivers on Windows, since it's not clear to me how Sodium's usage of `glMultiDrawArrays` could be invalid here. Perhaps there's buggy synchronization behavior on the driver's side after we copy buffer memory around?

I would suggest that you make sure your graphics drivers are up-to-date by checking with [Intel's DSA tool](https://www.intel.com/content/www/us/en/support/detect.html). In you still run into the issue even after updating, you should be able to at least workaround this specific crash by disabling Large Chunk Buffers.

**Comment by ghost** [comment]
I noticed there is an update to my driver(I thought I was fully updated,guess I'm not)
Anyways I will try again and report back once I have the chance,
best wishes,
-Nifty-Neutron

**Comment by ghost** [comment]
Issue still occurs after updating to the latest driver,
anyways here is the crash log if it helps
[hs_err_pid7296.log](https://github.com/jellysquid3/sodium-fabric/files/4747874/hs_err_pid7296.log)

Guess I have to disable large chunk buffers.

**Comment by ghost** [comment]
Shall I close the issue?

**Comment by ghost** [comment]
@jellysquid3 
Can you answer please,
should I close the issue?

**Comment by jellysquid3** [comment]
Sorry for the delay. I'd like to keep this issue open so we can track the crash -- it may still be possible to fix.

**Comment by ghost** [comment]
Thank you very much,
don't rush or annoy yourself with the crash,
I can live with it since it doesn't happen very often.

**Comment by Miros77** [comment]
I had this error earlier on 1 14 4

**Comment by ghost** [comment]
Tested with linux,
the issue not present

**Comment by Snivine** [comment]
I have the exact same CPU and iGPU than this guy and I don't get this issue using the latest drivers, could you check if updating your drivers with the intel driver assistant fixes it?

Tested on Windows before, I can use any Java Version without a random crash

**Comment by mrmangohands** [comment]
Closing this as it's incredibly stale and 1.17.x/dev isn't even using the same gl extension
