### ISSUE TITLE
0.4.11 crashing game without any report

### ISSUE THREAD

**Issue by pleepish** [jellysquid3/Sodium#1737]
### Version information

sodium 0.4.11 - 1.19.3

### Reproduction Steps

install sodium 0.4.11 - 1.19.3
launch minecraft
minecraft doesn't open
no crash report provided

### Crash Report file

none available

### Additional information

all of my other mods are up to date and run smoothly. this issue only occurs when i try to update sodium to 0.4.11

**Comment by Poopooracoocoo** [comment]
Are you 100% sure that there is no latest.log or crash report? Check your instance folder. On Minecraft Launcher for Windows, this is in %appdata%/.minecraft

**Comment by KB-Q** [comment]
Facing same issue. Here's my log: https://mclo.gs/lNxpqgy

I assume this is the relevant bit from the logs:
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector sodium$beforeGenerateMipLevels(Lnet/minecraft/class_7764;Lnet/minecraft/class_1011;Lnet/minecraft/class_2960;)V in sodium.mixins.json:features.mipmaps.MixinSpriteContents from mod sodium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.sodium.refmap.json`

**Comment by IMS212** [comment]
Update Iris to fix that issue.

**Comment by pajicadvance** [comment]
> sodium 0.4.11 - 1.19.3

How are you using 0.4.11 on 1.19.3? Is this a typo?

**Comment by pleepish** [comment]
> > sodium 0.4.11 - 1.19.3
> 
> How are you using 0.4.11 on 1.19.3? Is this a typo?

because sodium's mod page had a 0.4.11 download for 1.19.3 available? they've since taken 0.4.11 down, but..

**Comment by Timolino456** [comment]
Yes, there was a 1.19.3 version, but both 0.4.11 versions have been taken down due to them having problems.
If you want to keep playing 1.19.3, use Sodium 0.4.9 again and if you use any other mods that interact with Sodium and tend to break when Sodium updates, use the versions of those mods that depend on Sodium 0.4.9 instead of 0.4.11. Some that updated to support 0.4.11 already might not have updated again yet, so you'll have to test in that case.

**Comment by jellysquid3** [comment]
Sodium 0.4.11 was yanked and is not supported. Downgrade to Sodium 0.4.10 and wait for the next release of Sodium 0.5.
