### ISSUE TITLE
Updated version missing on CurseForge

### ISSUE THREAD

**Issue by alexzander700** [jellysquid3/Sodium#1747]
### Version information

MC 1.19.4

### Expected Behavior

Mod is out of date, please update

### Actual Behavior

Mod is out of date, please update

### Reproduction Steps

uhhh, download the latest version, it's not 1.19.4?

### Java version

Current

### CPU

Intel Core i5

### GPU

Iris Intel Integrated Graphics

### Additional information

Pretty useful to keep the mod up to date, especially for someone who's on integrated graphics...

**Comment by wahfl2** [comment]
Sodium is no longer being updated on Curseforge. See the [description](https://www.curseforge.com/minecraft/mc-mods/sodium).

**Comment by gudenau** [comment]
This is an issue I ran into as well. I shouldn't have to goto individual Github pages to download mods.

**Comment by IMS212** [comment]
@gudenau The updated versions are on [Modrinth](https://modrinth.com/mod/sodium).

**Comment by gudenau** [comment]
> @gudenau The updated versions are on [Modrinth](https://modrinth.com/mod/sodium).

Modrinth banned me, why would I use it?

**Comment by IMS212** [comment]
Then that sounds like a specific unrelated problem. Sodium will not be returning to curseforge, read [this](https://github.com/CaffeineMC/caffeine-meta/issues/8#issuecomment-1553477650) for more information.

**Comment by alexzander700** [comment]
Look if you guys are too immature to realize that the majority of people who use your mods are coming from CurseForge, that's on you. Like the post above mentioned, "We do not gain anything from people using our software", so just keep support for the versions THAT YOU ALREADY POSTED at one point, and just don't update past 1.19.4 if you don't like it. People use it as a core part of their modpacks, ones that would've only been made due to the IMPACT you had on us. Do better and grow up.

**Comment by IMS212** [comment]
The versions were archived, existing modpacks still have Sodium.

**Comment by alexzander700** [comment]
I went to click on the update button for sodium and it downloaded the 1.16 version.

**Comment by alexzander700** [comment]
Either way that's for @jellysquid3 to figure out.

**Comment by alexzander700** [comment]
> The versions were archived, existing modpacks still have Sodium.

That may be true for public Modpacks, but personal modpacks, like mine were affected.

**Comment by jellysquid3** [comment]
I have been more than patient with people. The flaming on this issue tracker will not be tolerated, and users who keep doing so are going to be permanently blocked.

We have explained our position many times at this point. Just because you disagree with us does not make our opinion childish or immature. Like we have said, we know it is inconvenient, but we are going to stand by the decision for the reasons outlined in the linked post above.

> People use it as a core part of their modpacks, ones that would've only been made due to the IMPACT you had on us. Do better and grow up.

For what it's worth, I personally don't care about these so called "modpack authors" you try to represent. If these people want to resort to berating me at the slightest inconvenience, when they predominately rely on our work to make their modpack relevant at all, then they can find some other forum to vent on. 

Not once have any of these people spamming our issue tracker ever acknowledged my arguments, showed any amount of sympathy, or even shown interest to be cooperative. This is the reason you are not getting what you want, and the reason we are so completely disinterested in doing things for those who wrongly try to speak for the "community."

I'll continue to work with the modpack authors who actually show some consideration for the projects they extend from, for which there are many... but my interest in dealing with people like you is honestly more than gone at this point.
