### ISSUE TITLE
Game looks grainier/more pixelated with sodium than without

### ISSUE THREAD

**Issue by RechercheRaptor** [jellysquid3/Sodium#1777]
### Version information

v0.44+build1.8

### Expected Behavior

Models will have smooth, clean edges.

![image](https://github.com/CaffeineMC/sodium-fabric/assets/131301693/3880e843-b8ad-41c7-a01e-666d5819cc38)

### Actual Behavior

Models have jagged, aliased edges and get very crunchy the farther away they are.

![image](https://github.com/CaffeineMC/sodium-fabric/assets/131301693/2a3a2d78-ebe6-4d74-b1ba-a613c9c165e6)

### Reproduction Steps

I hadn't used Sodium until today. I've installed it as part of a modpack made by a friend for a Cobblemon server, along with Lithium, Indium, MoreCulling, SodiumExtra, and Reese's Sodium Options. I loaded a creative world I'd been testing in, and found that all of the textures were much rougher than they were before I had Sodium.

Video settings used for the above screenshot-
Graphics- Fancy
Entity Distance- 100%
Entity Shadows- On
Smooth lighting- On
Mipmap Levels- 4x (maximum)

I'm not currently using any shaders and I'd like to avoid having to use one since I've always thought the game looked fine in the past.

### Java version

1.19.2

### CPU

Apple M1

### GPU

Apple M1

**Comment by Felix14-v2** [comment]
Your screenshots are taken in different resolutions — 2048x1536 and 1024x768. Obviously, they will have different degrees of detail.
If you want to save the quality with halved resolution, you can use shaders with Temporal Anti-Aliasing. For example, [VanilAA](https://modrinth.com/shader/vanillaa)  or [SimpleTAA](https://rre36.com/projects/simpletaa-release). TAA even can restore sub-pixel details using data from multiple frames.

**Comment by pajicadvance** [comment]
Please upload your game log.

**Comment by jellysquid3** [comment]
The problem isn't with Sodium. It's something to do with the game launcher or your system configuration, which is running the game at non-native resolution. I can't speculate what exactly it is, since I don't have a Macintosh and are unsure how this behavior is controlled.

**Comment by intergrav** [comment]
I'd assume this is because you have Sodium Extra installed, which contains a setting to halve the resolution of the game if running on a retina display under MacOS. Do you have that setting enabled by any chance? It should be under the "Extras" section. As @Felix14-v2 said, running on a lower resolution will cause the detail to decrease.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/42325132/174fa53c-ba5d-49c3-aa4e-ba99e3adccb3)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/42325132/f9893121-ff5b-45f4-a793-06fc85d992a5)
*Edit: I hadn't realized this issue was over a month old, oh dear*
