### ISSUE TITLE
More render distance

### ISSUE THREAD

**Issue by DedMaxim** [jellysquid3/Sodium#178]
**Is your feature request related to a problem? Please describe.**
Too much fps that I can't take advantage of, so...

**Describe the solution you'd like**
...increase maximum render distance to 48 or 64 or more

**Comment by np22-jpg** [comment]
32 chunks is hard-coded into threadedanvilchunkstorage, as well as a few other places.
Not sure how OF gets around it.

**Comment by jellysquid3** [comment]
This is not being considered. The game can't even properly handle a 32 chunk render distance on a reasonable computer.

**Comment by bready2die** [comment]
maximum settings aren't meant for potato computers. my laptop can easily handle 32, and could probably handle even higher than 64 if you people bothered supporting it.

**Comment by Barkells** [comment]
But with mods like nvidium now about, I feel like this should be possible without relying on c2me as the only option in single player, Bobby override only works on bobby saved chunks.

**Comment by jellysquid3** [comment]
C2ME is required because getting the integrated server to send more chunks is impossible without significant modification, as the limit of 32 chunks is hardcoded into many parts of the chunk management system. Even if you *could* do it (by just modifying the limit), the time complexity increases greatly with render distance, and performance scaling would be absolutely terrible, so you still need another mod to implement things in a better way.

Sodium does not permit increasing the render distance because that would require server modifications, which it _cannot do_ as a client mod. We will never change this.
