### ISSUE TITLE
[Enhancement]Remove the Unimplemented method.

### ISSUE THREAD

**Issue by nikam14** [jellysquid3/Sodium#1789]
### location
- src/main/java/me/jellysquid/mods/sodium/client/gl/arena/staging/FallbackStagingBuffer.java
line - 34

### Description 
- The method do not  have any code, removing it will increase the code quality.

### Screenshot - 
![sodium-1](https://github.com/CaffeineMC/sodium-fabric/assets/55378196/40a87eb4-5b9d-4981-b45c-4f6b9ce9b797)

**Comment by Altirix** [comment]
I suspect this is intentional as it saves needing to explicitly check what staging buffer is being used in RenderRegonManager. That method is defined by the interface StagingBuffer (both FallbackStagingBuffer and MappedStagingBuffer which has logic, implement this method).

**Comment by jellysquid3** [comment]
This user just runs automated tools across GitHub and spams projects with incorrect suggestions. Their post history will quickly point that out. This is the consequence of GitHub deciding to be a social media platform rather than just a code repository.

For anyone wondering about the actual code, it's implementing an interface which requires this method, and it's a NO-OP in this specific implementation. There is no issue, and if a human was involved, they would have actually attempted to validate their assumption, just to notice it immediately produces a compile error instead.
