### ISSUE TITLE
I turned off explosion particles in the settings and my game dont open no more

### ISSUE THREAD

**Issue by DxlqXD** [jellysquid3/Sodium#1793]
### Version information

sodium-extra-0.4.16mc1.19.2-build.90.jar

### Reproduction Steps

ok so basically I went to my settings, and went to particle (the mods im using are: lithium + sodium + sodium extra + reese sodium options) and I turned off the explosion particles and my game crashed, i was on 1.19.3... my game crashed and i couldn't reopen it... i tried reinstalling feather + repairing it and it did not work... then I switched to 1.19.2 and all my mods work other than sodium extra, it legit crashes when i try to open it... mc opened with all the mods on and it would just loop the feather logo that transitions into main menu at start of launch of MC... and so now I legit cant even open minecraft with sodium extra.. AND I REALLY NEED IT NGL, anyways please help me out

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11656953/latest.log)

### Additional information

i own many minecraft servers and I really need to be active... please I need help (Dxlq#8357) is my discord if u want to contact me

**Comment by Timolino456** [comment]
Sodium Extra is not made by the CaffeineMC team, you would need to report that [here](https://github.com/FlashyReese/sodium-extra-fabric/issues). I also don't recommend using Feather because it's known to cause problems.
But you might be able to fix this by deleting "sodium-extra-options.json" in .minecraft/config (or whatever folder structure Feather has). You will lose all the other settings from Sodium Extra this way though. You could probably also search for the explosion particles option in there and set it back to "true".
