### ISSUE TITLE
1.19.2 array out of bounds log spam.

### ISSUE THREAD

**Issue by netcore10** [jellysquid3/Sodium#1921]
### Bug Description

I'm getting array out of bounds for rendering. Sometimes i get an invisible chunk and it's the only thing i can surmise that's tied to it. 

### Reproduction Steps

no idea

### Log File

https://paste.atlauncher.com/view/23703759-b067-4385-b5ca-668ea1fbe1d3

### Crash Report

n/a

**Comment by netcore10** [comment]
![image](https://github.com/CaffeineMC/sodium-fabric/assets/181536/450c556d-4977-4c63-940d-5cb6f078e429)

**Comment by pajicadvance** [comment]
Does disabling the mod "Unofficial Sodium Biome Blending Fix" help?

**Comment by netcore10** [comment]
I disabled it, hard to tell because this problem seems so intermittent but destructive at the same time

**Comment by netcore10** [comment]
It did not help, i crash and the chunk errors still happen, but there's no log spam

**Comment by netcore10** [comment]
https://mclo.gs/ENiWZe3

**Comment by netcore10** [comment]
this is the crash/ log

**Comment by netcore10** [comment]
something about a hashmap is when the blank chunks happen
[message (1).txt](https://github.com/CaffeineMC/sodium-fabric/files/12222103/message.1.txt)

**Comment by jellysquid3** [comment]
The problem has nothing to do with Sodium. The crash is coming from "Unofficial Sodium Biome Blending Fix" (which seems to just be completely broken?), which all of your logs clearly point to. If the problem is still happening with that mod _removed_, then you need to upload a crash log demonstrating that, and ask for this issue to be re-opened.
