### ISSUE TITLE
Blocks delay

### ISSUE THREAD

**Issue by EymerickThibaut** [jellysquid3/Sodium#1966]
### Bug Description

Hello, I'm in my 2 weeks minecraft addiction, I created a new world, with sodium and a few other mods.

Issue :

When I break/place a block, it takes a few seconds to render (nothing happens visually except the block border being removed : minecraft knows the block isn't there anymore but it doesn't want to show it to me).

Once broke/placed and being rendered once, the bug doesn't happen anymore during the actual session.

Is it really Sodium ?

I've removed every mod, and my texture pack, except sodium and the fabric loader and it still happens, that's why I think it's sodium.

### Reproduction Steps

Install fabric and sodium on a 1.20.1 minecraft version and create a new world.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12285273/latest.log)

### Crash Report

[crash-2023-08-07_22.58.43-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12285271/crash-2023-08-07_22.58.43-client.txt)

**Comment by Julienraptor01** [comment]
Try to disable always defer chunk updates setting in sodium

**Comment by jellysquid3** [comment]
In order to prevent this, you have to disable `Video Settings > Performance > Always Defer Chunk Updates`. However, this option is broken in Sodium 0.5.0...

[This commit](https://github.com/CaffeineMC/sodium-fabric/commit/b2ffbb8801f6757e7411f743388c951e66603dd8) fixes the problem though you'll have to wait until the next release before you can use it.
