### ISSUE TITLE
Latest Version of Sodium causes a crash

### ISSUE THREAD

**Issue by Dragonsrule3194** [jellysquid3/Sodium#1983]
### Bug Description

Anytime I run the game, it opens but as soon as I join any server or singleplayer world, it saves and crashes. I reverted back to the older version of Sodium along with Sodium Extra and Reeces Sodium options and the crash didn't happen.

### Reproduction Steps

1. Launch the game with the latest version of Sodium
2. Attempt to join a server or a singleplayer world
3. Crash

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12325700/latest.log)

### Crash Report

[crash-2023-08-11_18.05.23-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12325707/crash-2023-08-11_18.05.23-client.txt)

**Comment by jellysquid3** [comment]
No, your other mods are broken. They are trying to modify internals of Sodium which changed in the recent version. This is not stable code and never has been.

Remove "Sodium Occlusion Culling Fix" -- it trashes performance and isn't necessary in Sodium 0.5 since we fixed the problem it was trying to workaround, anyways.

**Comment by Dragonsrule3194** [comment]
> Member

removed it, still crashes. which mods are the broken ones then?

**Comment by Altirix** [comment]
> > Member
> 
> removed it, still crashes. which mods are the broken ones then?

Recommend disabling mods untill you find the cause. You may read your logs for errors to narrow it down, it's likely the incompatible mod fails on a mixin for a target that is not present in sodium 0.5.0. Otherwise id recommend you should be using a modpack that has been curated by someone who is able to pack compatible mods together. Issue trackers are usually not intended as a general support forum

**Comment by purple512** [comment]
Cull Leaves - incompatible with Sodium 0.5, remove it
Cull Less Leaves - does nothing under Sodium 0.5, remove it
