### ISSUE TITLE
Problem with yacl and modmenu

### ISSUE THREAD

**Issue by BroPro40** [jellysquid3/Sodium#1987]
### Bug Description

The game just crashes, when I am trying to open mod menu

### Reproduction Steps

1. install sodium, mod menu, fabric api and yac
2. start minecraft
3. Press button "Mods" on the main menu

### Log File

1

### Crash Report

1

**Comment by purple512** [comment]
A log file is required to diagnose whatever is going on. It can be found as `latest.log` in the logs dir under the game dir.

**Comment by pPingu7** [comment]
I have the same issue, but it's probably because of incompatibility between sodium's newest version and another mod. With older sodium versions it works, but not with 0.5.0. I have tested it (I'm playing with Quilt): Created a new installation and copied the 4 mods modmenu, quilted fabric api, sodium and yet another config lib to the mod folder of the new instance. The game starts and doesn't crash, when I'm opening the mod menu. I'm now looking for the mod, which causes the crash on my normal minecraft installation.
Here is the crash report file, which was generated directly in the installation's folder [hs_err_pid67993.log](https://github.com/CaffeineMC/sodium-fabric/files/12327991/hs_err_pid67993.log)  (there was nothing in the crash-reports folder) and the [latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12327990/latest.log)

And here is my mod list
![Screenshot_of_my_mods](https://github.com/CaffeineMC/sodium-fabric/assets/136745649/bd112585-693b-48be-9e79-7233ebbd5115)

**Comment by jellysquid3** [comment]
@pPingu7 Read the log file...

`[19:54:33] [Render thread/WARN]: Mixin apply for mod faster_entity_animations failed`

It's not an issue with Sodium. Someone else is trying to modify our internal code and that is going to break when we make changes.

**Comment by pPingu7** [comment]
Thanks for the help! I've removed the mod, but unfortunately it doesn't fix my problem... It still crashes, when I open the mod menu and gives me the same file as crash-report and says nothing helpful in the log. I guess I'm gonna play Minecraft now without configuring my mods until the problem gets solved.

**Comment by skunkmommy** [comment]
> I have the same issue, but it's probably because of incompatibility between sodium's newest version and another mod. With older sodium versions it works, but not with 0.5.0. I have tested it (I'm playing with Quilt): Created a new installation and copied the 4 mods modmenu, quilted fabric api, sodium and yet another config lib to the mod folder of the new instance. The game starts and doesn't crash, when I'm opening the mod menu. I'm now looking for the mod, which causes the crash on my normal minecraft installation. Here is the crash report file, which was generated directly in the installation's folder [hs_err_pid67993.log](https://github.com/CaffeineMC/sodium-fabric/files/12327991/hs_err_pid67993.log) (there was nothing in the crash-reports folder) and the [latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12327990/lates
t.log)
> 
> And here is my mod list ![Screenshot_of_my_mods](https://user-images.githubusercontent.com/136745649/260250275-bd112585-693b-48be-9e79-7233ebbd5115.png)

I got a similar crash in Controlify on my Steam Deck and the crash dump indicates it's an issue with the GPU driver.
I made an issue isXander/Controlify#142 and I was told that it's something to do with YACL image previews.
But I'm now told it doesn't happen on Sodium 0.4.10. So that makes me think Sodium could be involved too.

This seems to be a combination of Sodium, YACL, and the Deck's GPU drivers causing this.
**IT IS NOT CAUSED BY FASTANIM.**
I didn't even have that mod when I crashed, you can check my logs.

You need to reopen this issue; it's still an issue.

**Comment by jellysquid3** [comment]
@spudpiggy None of the crash logs or heap dumps indicate there is a problem with our code (or the Java VM for that matter.) Furthermore, we didn't make any changes between version 0.5.0 and 0.5.1 of Sodium which even affected the graphics stack, so it's not possible this behavior is any different.

More likely than not, another mod is doing bad things, and the fact that Sodium 0.5.0 uses an "No Error Context" by default is likely turning what would've been an error into a crash. You can try disabling the option via `Video Settings > Performance > Use No Error Context` but it won't actually fix the problem, maybe just stop it from crashing.

**Comment by skunkmommy** [comment]
> @spudpiggy None of the crash logs or heap dumps indicate there is a problem with our code (or the Java VM for that matter.) Furthermore, we didn't make any changes between version 0.5.0 and 0.5.1 of Sodium which even affected the graphics stack, so it's not possible this behavior is any different.
> 
> More likely than not, another mod is doing bad things, and the fact that Sodium 0.5.0 uses an "No Error Context" by default is likely turning what would've been an error into a crash. You can try disabling the option via `Video Settings > Performance > Use No Error Context` but it won't actually fix the problem, maybe just stop it from crashing.

i misspoke when i said 0.5.0, i meant 0.4.10
> More likely than not, another mod is doing bad things

to quote someone on discord, "you can test with just zoomify/controlify, yacl and [sodiun] / the crash happens when it's trying to draw an image"

**Comment by pPingu7** [comment]
I dont know why, but now it works. I have updated sodium to 0.5.2 and maybe that version has done the fix or the problematic other mods have fixed the problem in between.
