### ISSUE TITLE
Minecraft crush with sodium

### ISSUE THREAD

**Issue by MoninGG** [jellysquid3/Sodium#2014]
### Bug Description

After installing Sodium on a clean version (Fabric+Fabric API), minecraft crashes

### Reproduction Steps

While connect on server minecraft close

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12339119/latest.log)

### Crash Report

[hs_err_pid15160.log](https://github.com/CaffeineMC/sodium-fabric/files/12339115/hs_err_pid15160.log)

**Comment by Altirix** [comment]
~~according to the log file this is not a clean install, one issue that sticks out to me is the use of iris 1.6.6 and sodium 0.4.10 on minecraft 1.19.4~~

~~iris 1.6.6 is for sodium 0.5.1 and that version of iris has broken shader support. both are for 1.20.1~~

~~id personally recommend using a modpack for anyone who doesnt want to be validating mod compatibility.~~

turns out iris 1.6.6 supports multiple version

**Comment by MoninGG** [comment]
![1111111111](https://github.com/CaffeineMC/sodium-fabric/assets/88363446/c7e64d43-f08b-464e-9ac1-fc5a1e5507f3)
why it crushes? all 1.19.4

**Comment by jellysquid3** [comment]
Because you didn't read the [Known Issues](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility#nvidia-gpus). Your graphics drivers are out of date and broken.

```
[22:42:39] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[22:42:39] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
[22:42:39] [Render thread/INFO]: OpenGL Version: 3.3.0 NVIDIA 531.79
```
