### ISSUE TITLE
Sodium Create Mod Bug

### ISSUE THREAD

**Issue by Crafty1340** [jellysquid3/Sodium#2045]
### Bug Description

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with:
		 - sodium 0.5.2
Unmet dependency listing:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Reproduction Steps

I don't know.

### Log File

Can't acess it.

### Crash Report

From me closing the game probaly from me closing the game while it was inisaling the game.

**Comment by Lolothepro** [comment]
update Sodium

**Comment by Timolino456** [comment]
Their Sodium is already up to date. I just tested it with Sodium 0.5.2 and Create 0.5.1-d and it gives the same error. Create 0.5.1-d seems to have Sodium 0.5.0 and later under "breaks" in their fabric.mod.json. Most likely because Flywheel, which Create depends on, seems to have problems with Sodium 0.5.0+: https://github.com/Jozufozu/Flywheel/issues/198 & https://github.com/Fabricators-of-Create/Create/issues/1039
A solution would be to use Sodium 0.4.10 instead, but depending on how many mods you have that interact with or depend on Sodium, picking versions of them that work with it could be a bit annoying.

**Comment by ZIDI228** [comment]
Попробуйте версию Create 0.5.1-c вместо -d
Банально понизьте версию 

Try Create version 0.5.1-c instead of -d
Corny downgrade the version
