### ISSUE TITLE
NVIDIA_THREADED_OPTIMIZATIONS - Fix NOT needed! Explanation below

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2061]
### Request Description

This "bug" is EASILY fixed by going to Nvidia Control Panel and turning OFF Threaded Optimization in the Manage 3D Settings -> General tab. And if that isn't enough, run the game and load up Task Manager to find your java instance location for Minecraft/or look for "C:\Program Files\Java\jdk-17\javaw.exe" (For 1.20.1), and add that to your Programs in Nvidia Control Panel and just turn off the Threaded Optimization there.

It's a really easy fix :D No need for work arounds at all!

**Comment by Lolothepro** [comment]
You think it's easy to ask all Sodium users to do this?

**Comment by ghost** [comment]
Yes, it should be, it's suuper easy and you should know how to use your computer. At the very least, make that "fix" optional for those who do know how to properly work their computers to get the most out of it :) It upsets me as I need everything I can get for my own personal resource packs and mods :)

**Comment by ghost** [comment]
P.S.: It's literally something that comes with the driver of your Nvidia card. It's literally 3 clicks. You really have no need to search for the javaw.exe, just turn it off in General tab :D

**Comment by jellysquid3** [comment]
This does not work, and it was the first thing we asked users to do.

We reverse engineered the NVIDIA driver and found that it forcefully enables Threaded Optimizations regardless of the control panel settings. This is because there is no way for these settings to only target Java processes running "Minecraft" (as all Java applications use the same executable file), so they instead need to hardcode the detection logic into the driver itself. Fundamentally, it's a hack they put in to workaround limitations of their DRS profiles, which requires it to ignore whatever the control panel has configured in the first place.
