### ISSUE TITLE
Game Crashes When Pistons are activated

### ISSUE THREAD

**Issue by S1icedLIVE** [jellysquid3/Sodium#2090]
### Bug Description

Whenever A piston is activated game will crash

### Reproduction Steps

Not sure

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12718815/latest.log)

### Crash Report

[crash-2023-09-25_15.44.01-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12718810/crash-2023-09-25_15.44.01-client.txt)

**Comment by pajicadvance** [comment]
Update your mods.

**Comment by JayRPlayz** [comment]
same happens for me, but what mods am i supposed to update?

**Comment by Poopooracoocoo** [comment]
@JayRPlayz I can only guess since you didn't provide a crash report or log and **_this isn't a support forum_**. I'm guessing you've got a mod like Continuity. Make sure you've got Indium so that Sodium can work with it.

If you're on Minecraft 1.20.1, note the marked Fabric API version compatibilities of Indium. If you use Sodium 0.5.3 and Indium 1.0.27, you can use the latest versions of Fabric API. If you're using an older version of Indium and Sodium, you'll need to downgrade Fabric API to 0.88.1. 

In this case, this user had an older version of Indium that didn't support Fabric API 0.89 and above. They were able to fix this by updating Sodium and Indium.

**Comment by JayRPlayz** [comment]
thanks, thats probably the problem, but using sodium extra and disableling piston redering fixes it too

**Comment by JayRPlayz** [comment]
thanks, indium actually fixed it!
