### ISSUE TITLE
Sodium Freezing My Screen

### ISSUE THREAD

**Issue by Charaaa123** [jellysquid3/Sodium#2096]
### Bug Description

This is fairly new to me as for some reason all versions of sodium 0.50 and up will un-fullscreen and window my game and will freeze my game upon alt tabbing. The weird part of it is the screen is still interactive you can press things and it will work but it won't change the screen. Say if I alt tabbed when I'm in the main selection screen and if I clicked on where the option will be I can hear the clicking sound effect but the screen remains frozen. The problem with this is that it doesn't crash my game so I don't have a crash log or report. 

### Reproduction Steps

Using any version of sodium 0.50+ will cause this problem to occur when alt tabbing. 

### Log File

There is no log file

### Crash Report

There is no crash report

**Comment by Poopooracoocoo** [comment]
You sure there's no logs? You're looking for a latest.log in your logs folder. It'll contain information about your GPU and graphics driver version. Also be aware that if you've got an overlay RivaTuner Statistics (RTSS), it'll cause issues. Your logs will uncover all kinds of issues, really. Logs aren't the same as a crash report, and are always generated.

**Comment by Charaaa123** [comment]
Ahh sorry I'm so dumb, very new to this sorry. Here's the log file.

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12774754/latest.log)

**Comment by jellysquid3** [comment]
This problem is not fixable on our part. We have to apply hacks to make the NVIDIA driver stop breaking our code (see https://github.com/CaffeineMC/sodium-fabric/issues/1816 and https://github.com/CaffeineMC/sodium-fabric/issues/1830), and for whatever reason this causes bugs in hybrid graphics situations like your own. NVIDIA will not communicate with us and ignores bug reports, so I doubt this problem will ever go away.
