### ISSUE TITLE
Text Offset 1.20.2

### ISSUE THREAD

**Issue by olehrstm** [jellysquid3/Sodium#2109]
### Bug Description

Text offset https://imgur.com/a/UWPBIzS
Version: 1.20.2
Sodium Version: v0.5.3

the offset is also in the chat, tablist and so on

### Reproduction Steps

Download Fabric 1.20.2 and Sodium v0.5.3

### Log File

Nothing special in there

### Crash Report

Nothing

**Comment by douira** [comment]
No, we do need the files that the issue template asks for, because they contain information about your system and what mods you're running. You haven't given us any information about what this image is depicting.

**Comment by olehrstm** [comment]
there is literally nothing about my system in there

**Comment by douira** [comment]
Look, it's nearly impossible to tell what the issue would be possibly caused by if you don't give us more than "text offset" and that screenshot. There's usually a thousand things that cause bugs in complex interactions between potentially multiple mods. Please provide the required files or nobody will be able to fix your issue.

**Comment by Poopooracoocoo** [comment]
More screenshots would help too. 

And have you actually tested to see if it happens with just Sodium? Your steps to reproduce say you tested it but your screenshot shows buttons from LabyMod. I wasn't able to reproduce this issue.

I did a quick google for "sodium text offset" and saw that https://www.labymod.net/en/idea/13981 exists
