### ISSUE TITLE
Zink

### ISSUE THREAD

**Issue by iMonZ** [jellysquid3/Sodium#2120]
### Request Description

Implementing Zink would be awesome.
The Game would run on Vulkan without Code rewrite. (I already see that native Vulkan isnt very popular with Devs here)
Especially on macOS, where the latest OpenGL version is 3.Something
It would be an awesome boost combined with OpenGL.
But other platforms would also benefit from it.
So this is the perfect solution and make all shader features compatible with different plattforms

**Comment by TheUserCreated** [comment]
Zink is a program (this is an oversimplification) that can be installed and enabled by the end user. It isn't something you "implement" in Sodium. Sodium and Zink have actually worked correctly together at times in the past, and if there are any bugs preventing you from using this configuration those might be worth making an issue for (either for Zink or Sodium depending on whose issue it is). Note that Zink on MacOS then needs to go through a second translation layer (MoltenVK) since MacOS doesn't support Vulkan, so MacOS issues would likely still not receive much support here (I can't say for certain since it's not my decision).

**Comment by iMonZ** [comment]
Zink+MoltenVK would still increase the Framerate drastically then using the Legacy old OpenGL.
Even on non macOS Device Zink would still overcome OpenGL since OpenGL is not really optimized with modern hardware

**Comment by jellysquid3** [comment]
No. It wouldn't. You don't know what you're talking about.
