### ISSUE TITLE
Resource packs cannot replace the textures of Leaves Blocks

### ISSUE THREAD

**Issue by northagen** [jellysquid3/Sodium#2160]
### Bug Description

I was using a texture pack called "Faithless" and everything was going great until I realized that the leaves from the texture pack don't show up and instead show the default ones.

### Reproduction Steps

-Have a texture pack
-Use Sodium 0.5.3

### Log File
[Moderator edit: Log file was converted to a file attachment]
[log.txt](https://github.com/CaffeineMC/sodium-fabric/files/13373135/log.txt)

**Comment by jellysquid3** [comment]
Another user reported this [on our Discord server](https://caffeinemc.net/discord) in [this support thread](https://discord.com/channels/602796788608401408/1174568806350340206/1174596668239388684). 

For context, we replace a few textures (notably for leaves) in the default resource pack in order to fix some issues with our shader code. These textures are broken (missing color values for transparent pixels) and it wasn't really feasible to solve in another way.

I guess Fabric doesn't handle this perfectly, and custom resource packs end up not being able to override our mod's resources.

**Comment by jellysquid3** [comment]
This has been confirmed to be user error, at least with current versions of the Fabric API. If you are having this problem, you must make sure that your resource pack ordering has "Fabric Mods" _beneath_ your resource pack.

For example, your resource pack list should look like this, from top to bottom:

- [Custom Resource Pack]
- Fabric Mods
- Minecraft
