### ISSUE TITLE
Fix vanila bug MC-193656 in Sodium, or make the Fabric API fix compatible with Sodium

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2175]
https://github.com/embeddedt/embeddium/issues/110

Sodium+Fabric API:

https://github.com/CaffeineMC/sodium-fabric/assets/68275908/9e5f6558-e013-411b-bf8d-db9597c470fc

Fabric API:

https://cdn.discordapp.com/attachments/394433849251332096/1176601861537669160/2023-11-21_20-14-51.mp4

https://github.com/CaffeineMC/sodium-fabric/assets/68275908/4d179059-364c-4a7e-8088-d55977ac6417

Note: No github template was used, because I don't know if it's a bug or a feature request.

**Comment by embeddedt** [comment]
The issue might be that [Fabric API's mixin](https://github.com/FabricMC/fabric/blob/1.20.3/fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/OverlayVertexConsumerMixin.java) does not take effect on Sodium's call to `Direction.getFacing` here:

https://github.com/CaffeineMC/sodium-fabric/blob/0ae058b7b078b182fafc57c12de5059b22e088a0/src/main/java/me/jellysquid/mods/sodium/mixin/core/render/immediate/consumer/OverlayVertexConsumerMixin.java#L88

If that is the case, the best solution is probably for Sodium to ship its own version of the fix (suitably optimized, since Fabric still uses the dot product rather than comparing magnitudes).

EDIT: The cause is more nuanced than this, as replacing the `getFacing` call with Fabric's implementation manually does not fix the issue.

**Comment by jellysquid3** [comment]
The problem is caused by how we apply transformations to the packed normal data of each vertex. In vanilla, these transformations happen _before_ the values are compressed/truncated. But with Sodium, we apply the transformations to the already truncated values, which means there is very little precision left at that point (only 8 bits per component). This is why the behavior you are seeing is so unstable.

I don't see an easy way to fix this without radically altering how the VertexBufferWriter works. We would have to move the encoding step to the very end (before it's written into a buffer), and have it only consume full-precision normals. This would break any other mods relying on Sodium's interface, and it would probably come with a performance penalty.

**Comment by Lolothepro** [comment]
fixed in 24w05a
https://bugs.mojang.com/browse/MC-193656

**Comment by Lolothepro** [comment]
The fix is in 1.20.5-rc1

**Comment by Lolothepro** [comment]
Fixed in 1.20.5
