### ISSUE TITLE
Part of the world starting to crash

### ISSUE THREAD

**Issue by minisbett** [jellysquid3/Sodium#2194]
### Bug Description

The bug is already described in https://github.com/PepperCode1/Continuity/issues/342; It doesn't seem to be continuity related though, which I first thought. We were able to narrow it down to a few chunks where the error occurs everytime we reload the chunks, aka. joining the server or changing the render distance.
I'm also getting different errors, sometimes smth with sprite is null, sometimes adjState is null, maybe something about a palette, pretty weird.

### Reproduction Steps

no idea

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13536430/latest.log)

### Crash Report

[crash-2023-12-02_14.40.45-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13536427/crash-2023-12-02_14.40.45-client.txt)

**Comment by minisbett** [comment]
Okay I think updating to 0.15 fixed it. It seems the latest sodium is incompatible with 0.14.24?

**Comment by minisbett** [comment]
We tried removing all mods, including sodium, and it still occurs. It's really mod, we have no idea what's going on and whether there might be some corrupted chunks or whatever.

**Comment by jellysquid3** [comment]
The problem is not with any of your mods. You have a corrupted chunk which contains a `null` entry within the block palette, and everything is crashing on it because that's not a valid state.

The chunk in question is `chunk (88, 4, 85) from (1408, 64, 1360) to (1423, 79, 1375)`. You will have to use third party tools to try and fix the data manually. An NBT editor could possibly be used to replace the null entry in the block palette, or you can try to use a tool to delete the problematic chunk.
