### ISSUE TITLE
Sodium does not display a resource pack compatibility warning when JSON files are replaced 

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2215]
### Bug Description

Sodium does not display warnings in some cases (Core shaders)

### Reproduction Steps

Apply [Energy Shaders](https://modrinth.com/shader/energy-shaders-java)

### Log File

Not useful

### Crash Report

Not useful

**Comment by jellysquid3** [comment]
Sodium can't detect if mods are mixing into our code and replacing shaders. This isn't fixable, or at least, I don't want to fix it.

**Comment by jellysquid3** [comment]
Some people on Discord let me know this is actually two problems:
- The resource pack relies on a mod which mixins to Sodium's internal, in order to allow it to load custom shaders.
- The resource pack modifies the JSON to load shader files from non-standard paths.

We can fix the latter issue by seeing if a resource pack provides any `.json` files in the shader directory, or something.

**Comment by jellysquid3** [comment]
Also, for future reference, **please stop omitting the log files.** We need them even if you think they are not relevant.

**Comment by jellysquid3** [comment]
Resolved with https://github.com/CaffeineMC/sodium-fabric/commit/eec838060656c861c9f64dd18ad2f5073dc57184.
