### ISSUE TITLE
オオカミが装備している防具の音を検知

### ISSUE THREAD

**Issue by kayuri1** [jellysquid3/Sodium#2219]
### Bug Description

sodium0.5.5または0.5.4で次回のアップデートで追加されるはずの狼の防具の音を検知しそれによってロード画面でクラッシュします
![スクリーンショット 2023-12-25 170312](https://github.com/CaffeineMC/sodium-fabric/assets/154793330/5c9862bf-4b57-423b-91af-6970443991df)

### Reproduction Steps

sodium0.5.5または0.5.4を追加する

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13765185/latest.log)

### Crash Report

クラッシュレポートは作成されませんでした

**Comment by Moulberry** [comment]
Are you sure you downloaded the variants of Sodium that are intended for 1.20.2?

There are multiple jars for Sodium 0.5.5/0.5.4

![image](https://github.com/CaffeineMC/sodium-fabric/assets/12858993/ed997212-e08f-43db-ad40-057c7a56acdc)

**Comment by kayuri1** [comment]
もう一度1.20.4のものをダウンロードしました、しかしゲームがクラッシュしました

**Comment by kayuri1** [comment]
![スクリーンショット 2023-12-26 080028](https://github.com/CaffeineMC/sodium-fabric/assets/154793330/6fe0d26e-bd99-460c-b9e1-b365dc85e4ca)
この画面で止まってしまいます

**Comment by jellysquid3** [comment]
[機械翻訳](https://github-com.translate.goog/CaffeineMC/sodium-fabric/issues/2219?_x_tr_sl=en&_x_tr_tl=ja&_x_tr_hl=en-US&_x_tr_pto=wapp#issuecomment-1869227549)

---

I don't speak Japanese. My ability to understand you is very limited. This text is written to help computers translate it better.

Your log file contains OpenGL errors. But the log file does not show that Sodium is installed. This means your problem is unrelated to Sodium.

My guess is you have an "Intel HD 4000" series graphics card, and that the installed graphics drivers are incompatible with Minecraft. You can usually fix this problem by updating the graphics driver (see instructions in #899). This may be an incorrect guess, because we don't have the crash report file. You will need to check what hardware is installed in your computer to be sure it is the right solution.

If you do not have that hardware, or updating the graphics driver does not fix your problem, we cannot help you.

**Comment by kayuri1** [comment]
あなたが言っている通りグラフィックドライバーを更新することで問題は解決しました。すみませんでした。
