### ISSUE TITLE
Sodium does not work on 1.19.4

### ISSUE THREAD

**Issue by Lunacharskytho** [jellysquid3/Sodium#2300]
### Bug Description

Running through modrinth, no window ever opens I just get a notification that minecraft has crashed. A few other threads said to update my graphics drivers so I updated to the latest NVIDIA game ready drivers and it did nothing. I'm at a loss. Appreciate the help.

Log without sodium installed, running and exiting the game as normal:

https://mclo.gs/NsAci3R

Log with sodium installed:

https://mclo.gs/TSJBTga

### Reproduction Steps

install sodium on 1.19.4, tadaaaaaa

### Log File

https://mclo.gs/TSJBTga

### Crash Report

https://mclo.gs/TSJBTga

**Comment by Poopooracoocoo** [comment]
I noticed that for the crash report field you put your log again.

Did you make sure to check your instance's crash-reports folder for a crash report? 

I ask because I know Modrinth's notification says you can "visit the logs page to see a crash report" but it is incorrect.

You need to get Indium for Sodium to work with mods such as Supplementaries https://modrinth.com/mod/indium/version/1.0.19+mc1.19.4

You would not experience a crash with just Sodium on 1.19.4 if adding Indium is all it takes to fix it in your instance, so your steps to reproduce would be incorrect.

**Comment by Lunacharskytho** [comment]
> I noticed that for the crash report field you put your log again.
> 
> Did you make sure to check your instance's crash-reports folder for a crash report?
> 
> I ask because I know Modrinth's notification says you can "visit the logs page to see a crash report" but it is incorrect.
> 
> You need to get Indium for Sodium to work with mods such as Supplementaries https://modrinth.com/mod/indium/version/1.0.19+mc1.19.4
> 
> You would not experience a crash with just Sodium on 1.19.4 if adding Indium is all it takes to fix it in your instance, so your steps to reproduce would be incorrect.

never been so embarassed lol I cant believe I forgot indium
