### ISSUE TITLE
Blocks or Chunks (still) flickering when a Block is broken or placed, even with the Newest Graphics card. (Intel Integrated graphics issue.) 

### ISSUE THREAD

**Issue by JeffisaGuy** [jellysquid3/Sodium#2343]
### Bug Description

I've decided to play Minecraft again after not playing for a Few days, until suddenly the Block / Chunk flickering Issue has Re-appeared. (The one where It only happens to Intel Graphics Users), I was confused since I already Installed the Latest drivers for my Laptop, I even checked the Intel Driver Support Assistant to see If I have any Outdated drivers, and I even Installed the Latest Fabric version, API, and even the Latest version of Sodium and still no luck.

### Reproduction Steps

Simply: Break or Put a block, then the Chunks randomly flicker in a Short moment. (Happens at specific Coordinates or Areas.)

### Log File

[2024-02-17-7.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/14318011/2024-02-17-7.log.gz)

### Crash Report

[crash-2024-02-17_15.04.46-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14318021/crash-2024-02-17_15.04.46-client.txt)

**Comment by TheUserCreated** [comment]
the log file you've attached is not the correct one.

**Comment by jellysquid3** [comment]
```
	Processor Name: Intel(R) Pentium(R) Silver N6000 @ 1.10GHz
	Identifier: Intel64 Family 6 Model 156 Stepping 0
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x4e71
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9079
```

Nope! Your drivers are still out of date, because Intel's "Driver Support Assistant" does not show the latest updates.

You have an _Intel Pentium Silver N6000_, which is a _Japser Lake_ part using Gen11 graphics (which we mention as being problematic on the wiki, as you found.) You must install the latest drivers from the file located [here](https://www.intel.com/content/www/us/en/download/776137/intel-7th-10th-gen-processor-graphics-windows.html) to fix the problem.
