### ISSUE TITLE
Allow disabling of occlusion culling

### ISSUE THREAD

**Issue by jbritain** [jellysquid3/Sodium#2349]
### Request Description

Sometimes, when using in combination with Iris and moving large portions of terrain in the vertex shader, terrain which is now visible to the player is culled because the occlusion culling is calculated before the vertex offsets.

It would be nice if it was possible to disable occlusion culling to prevent this.

I have disabled block face culling and fog occlusion, and in the shader code disabled frustum culling, leaving only occlusion culling to be a possible explanation for this.

**Comment by douira** [comment]
This seems more appropriate as an issue for Iris than Sodium.

**Comment by jellysquid3** [comment]
Sodium does not support custom terrain shaders (or any customization of the terrain for that matter), so it doesn't make sense why you would want to disable this. If you are writing custom shaders for Iris, then you should ask them to provide that functionality, since they control the behavior of occlusion culling.

**Comment by TI-Bayonex** [comment]
I agree, sodium's culling also causes issues for me in vs_clockwork
