### ISSUE TITLE
Sodium for Holy Gl4es

### ISSUE THREAD

**Issue by TomXD1234** [jellysquid3/Sodium#2393]
### Request Description

Please make a version of sodium with support holy Gl4es because Pojavlauncher fps problem

**Comment by Felix14-v2** [comment]
Holy GL4ES is a compatibility layer, you won't get the native performance with it. Please, read [this](https://github.com/CaffeineMC/sodium-fabric#opengl-compatibility-layers) info about it. And this is not about "making a version" — you have to rewrite the entire Sodium rendering system to make it compatible with OpenGL ES. The best solution is to run Minecraft with VulkanMod, because almost all modern Android smartphones have proper Vulkan support. But the PojavLauncher community has done everything to get the VulkanMod developers to drop Android support.

**Comment by MCRcortex** [comment]
> best solution is to run Minecraft with VulkanMod

This is no longer supported by VulkanMod either
