### ISSUE TITLE
sodium dosent work in PojavLauncher

### ISSUE THREAD

**Issue by RelaxingNostalgia** [jellysquid3/Sodium#2399]
### Bug Description

The Game/Launcher crashes whenever i load/create a new world,and it dosent render any chunks.

edit 
sodium also dosent work with vulkanmod,version tested 1.20.2 issue being it opens the game but stays with black screen infinitely.

Hardware:Snapdragon 680 4GB Ram 

video showing the issue
https://youtu.be/ptE-pGxMoKE

### The log file and images/videos

no file

### Steps To Reproduce

```markdown
start pojav have fabric and sodium installed,create world
```

### Expected Behavior

crash

### Platform

```markdown
- Device model: Motog32
- CPU architecture: Arm
- Android version: 13
- PojavLauncher version: latest
```

### Anything else?

not sure what is the source of the issue sodium or pojavlauncher so i reported the issue for both

### Reproduction Steps

.1

### Log File

.

### Crash Report

.

**Comment by jellysquid3** [comment]
Sodium is not compatible with PojavLauncher. Please read [the hardware requirements](https://modrinth.com/mod/sodium#hardware-compatibility).

**Comment by RelaxingNostalgia** [comment]
> Sodium is not compatible with PojavLauncher. Please read [the hardware requirements](https://modrinth.com/mod/sodium#hardware-compatibility).

weird because i have seen people being able to run sodium in pojav in videos.

**Comment by Fnige** [comment]
> > Sodium is not compatible with PojavLauncher. Please read [the hardware requirements](https://modrinth.com/mod/sodium#hardware-compatibility).
> 
> weird because i have seen people being able to run sodium in pojav in videos.

Theres workarounds for having it run on phones but sodium still doesnt give support for mobile devices

**Comment by RelaxingNostalgia** [comment]
if not asking too much add support for mobile,i m pretty sure everyone would love to play minecraft java in literally any place.

your mod is awesome keep going 👍

**Comment by asumagic** [comment]
You may see some people run Sodium on Pojav, but:

- Official support is not being considered partly because the devices they run on often use many different problematic drivers and compatibility layers which makes dealing with many issues very time consuming or impossible, and often result in poor performance.
- Related to the previous point, lack of hardware availability and the difficulty of debugging makes dealing with such issues even harder.
- Some of the workarounds imply disabling a lot of features that makes the mod useful (which is what some tutorials say to do).

Thus Pojav-specific bug reports and support requests are rejected because it's just way too much complexity for the developers to deal with (plus some reasons I'm omitting). This will probably not change.

See https://github.com/CaffeineMC/sodium-fabric/issues/1916 for technical details.

**Comment by Felix14-v2** [comment]
> i have seen people being able to run sodium in pojav in videos

They disable 80% of Sodium optimisations to do that.

> everyone would love to play minecraft java in literally any place.

You could use VulkanMod to achieve mobile performance even better than in Bedrock in the past, but due to the actions of PojavLauncher community its developers has dropped Android and ARM support.
Due to the lack of OpenGL support, Vulkan is the only PC-compatible way to run Minecraft with native performance on Android.

**Comment by RelaxingNostalgia** [comment]
> > i have seen people being able to run sodium in pojav in videos
> 
> They disable 80% of Sodium optimisations to do that.
> 
> > everyone would love to play minecraft java in literally any place.
> 
> You could use VulkanMod to achieve mobile performance even better than in Bedrock in the past, but due to the actions of PojavLauncher community its developers has dropped Android and ARM support. Due to the lack of OpenGL support, Vulkan is the only PC-compatible way to run Minecraft with native performance on Android.

i m not entirely sure i understood what you said;
but about performance native bedrock has worse performance than java through pojav theres a video i made about that
https://youtu.be/0P0ejEIDtqE

**Comment by RelaxingNostalgia** [comment]
> > i have seen people being able to run sodium in pojav in videos
> 
> They disable 80% of Sodium optimisations to do that.
> 
> > everyone would love to play minecraft java in literally any place.
> 
> You could use VulkanMod to achieve mobile performance even better than in Bedrock in the past, but due to the actions of PojavLauncher community its developers has dropped Android and ARM support. Due to the lack of OpenGL support, Vulkan is the only PC-compatible way to run Minecraft with native performance on Android.

the mobile version is BAD really BAD i could even show you the freezing issue where it freezes from 2-5 seconds if youre simply walking to generates chunks/netities
thats why we mobile users keep begging mojang to fix the performance nonstop,and also emulating other systems,because these run better than native stuff,and that is valid even for emulation.

**Comment by RelaxingNostalgia** [comment]
> > i have seen people being able to run sodium in pojav in videos
> 
> They disable 80% of Sodium optimisations to do that.
> 
> > everyone would love to play minecraft java in literally any place.
> 
> You could use VulkanMod to achieve mobile performance even better than in Bedrock in the past, but due to the actions of PojavLauncher community its developers has dropped Android and ARM support. Due to the lack of OpenGL support, Vulkan is the only PC-compatible way to run Minecraft with native performance on Android.

one usually would think we're begging for performance because mobile hardware is weak,but no.
its simply that native mobile stuff is poorly made.
