### ISSUE TITLE
Reimplement frogspawn translucency thanks to 0.6's translucency sorting

### ISSUE THREAD

**Issue by djmrFunnyMan** [jellysquid3/Sodium#2437]
### Request Description

Frogspawn was meant to have a translucent texture. However due to vanilla Minecraft's own translucency sorting issues, they had to remove that https://bugs.mojang.com/browse/MC-249106

But since sodium 0.6 will have almost flawless translucency sorting thanks to douira it will be possible to reimplement the original vision for this block.

**Comment by mrjasonn** [comment]
I would personally advise to not make Frogspawn translucent until vanilla does so. This is partly because some people might consider it cheating which might cause servers, especially more picky ones to ban Sodium, and it should have better vanilla parity if we wait for vanilla. Another reason is because this changes the look and feel of the vanilla block. But anyway thanks to @djmrFunnyMan for helping bring up that it will probably be an easy change to Sodium if vanilla does so.

**Comment by muzikbike** [comment]
Wouldn't this be out of scope as per #876 and #877?

**Comment by djmrFunnyMan** [comment]
> some people might consider it cheating

How? literally what possible tentative advantage might that give the player.

**Comment by MeeniMc** [comment]
Even if that doesn't give an advantage that would change the look and feel of the block compared to Vanilla.

**Comment by douira** [comment]
We discussed this issue yesterday and consensus between contributors is that this is not a desired change for Sodium.
