### ISSUE TITLE
Fix fog's effects on translucent blocks moved by pistons

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2446]
### Request Description

Vanilla bug https://bugs.mojang.com/browse/MC-248682. Falling block entities representing translucent blocks are also affected: https://bugs.mojang.com/browse/MC-248688

Simply put, translucent blocks being moved by pistons aren't affected by fog in the same way non-translucent blocks moved by pistons are, causing them to stick out very obviously from a distance. Fixing this may be as easy as tweaking vanilla's shaders, but I decided it'd make sense to report here on the basis of it being a common graphical issue.

![2024-05-01_23 27 53](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/3728cd25-0d22-40b3-b06d-4c278c9530fd)

**Comment by jellysquid3** [comment]
For some reason, Minecraft special-cases _translucent_ moving blocks with a separate shader, and nothing else. Why they're doing this is beyond me, because there's no difference between it and the normal translucency shader _other than_ for the fact it doesn't apply fog.

Probably, one could fix this by modifying the `rendertype_translucent_moving_block` render type JSON (with a resource pack) to instead use the `rendertype_translucent` shader. But I don't want to do this in Sodium, since other mods could rely on this behavior or other strangeness it introduces.

**Comment by muzikbike** [comment]
This got fixed in vanilla last year or so, for anyone who comes across this and is still curious.
