### ISSUE TITLE
Possible regression of potted cactus/bamboo/azalea fix

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2455]
### Bug Description

#858 was fixed not too long ago, allowing for the top faces of these four blocks to be culled as expected. However, that fix no longer seems to work, and we have reverted back to the undesirable vanilla behaviour.

![2024-05-02_18 52 47](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/27f73ac7-428c-4bec-9209-c5c1c94fbfff)

### Reproduction Steps

1. Place a cactus, azalea or bamboo in a flower pot
2. Place a full opaque block above the pot
3. Enter that block in Spectator mode

### Log File

[crash-2024-05-02_18.58.46-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/15192242/crash-2024-05-02_18.58.46-client.txt)

### Crash Report

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15192248/latest.log)

**Comment by embeddedt** [comment]
For some context: this was reverted intentionally in https://github.com/CaffeineMC/sodium-fabric/commit/c937156e37d221216f284639fc8c51b30facf91e, because the original fix is too strict and breaks some modded/resource pack models, as well as [altering powder snow rendering](https://github.com/CaffeineMC/sodium-fabric/issues/1913), while not really reducing the amount of vertices being rendered very much.

**Comment by jellysquid3** [comment]
Yes. This change was reverted, as it is produces too many issues for a very negligible gain (essentially none in any real-world scene.) It will not be re-implemented.
