### ISSUE TITLE
UI BUG?

### ISSUE THREAD

**Issue by FaridZC** [jellysquid3/Sodium#2527]
### Bug Description

La interfaz de la configuración del Sodium está bugeada, en todas las opciones dice "sodium.options.pages.(la configuración" o dice "sodium-extra.option.(la opción)". También dentro de un mundo, al activar la opción de ver los "fps", me dice "sodium-extra.overlay.fps" en lugar de dar los FPS. Intenté reinstalando todos los mods (que por cierto son solo de optimización y son requisito del servidor) pero sigue igual. 
Dejo como dato que somos 9 en el servidor con exactamente los mismos mods y soy el único con ese problema, alguna solución? por favor :(.

![image](https://github.com/CaffeineMC/sodium-fabric/assets/163216629/6c084ed3-26e0-42fb-a752-ca2b11936133)

![image](https://github.com/CaffeineMC/sodium-fabric/assets/163216629/2073359b-b92b-4337-a7a9-ec9072e72380)

### Reproduction Steps

Se bugea la interfaz de confiuración.

### Log File

[latest.log](https://github.com/user-attachments/files/15542277/latest.log)

### Crash Report

[crash-2024-06-03_22.51.12-client.txt](https://github.com/user-attachments/files/15542266/crash-2024-06-03_22.51.12-client.txt)

**Comment by rilakuma123** [comment]
For future reference, when you need support for Sodium please head to the Discord server: https://caffeinemc.net/discord

This is likely caused by Language Reload. You may like to replace it with Lazy Language Loader.

I'd ask the Language Reload folks at their [Discord server](https://discord.gg/qZ3SCcc) or their [GitHub issue tracker](https://github.com/Jerozgen/LanguageReload/issues). They'll be able to investigate.
