### ISSUE TITLE
Game crashes on attempting to open (logs told me to report here)

### ISSUE THREAD

**Issue by the-wildguy** [jellysquid3/Sodium#2532]
### Bug Description

the game crashes when attempting to open it

### Reproduction Steps

open the game (i dunno what the error is sodium works on other modpacks)

### Log File

[latest.log](https://github.com/user-attachments/files/15755074/latest.log)

### Crash Report

[hs_err_pid15381.log](https://github.com/user-attachments/files/15755079/hs_err_pid15381.log)

**Comment by FlipperFlopper99** [comment]
omg did you not read the guidelines???
literally the FIRST thing it says is dont make issues if its a crash or something else

**Comment by wahfl2** [comment]
To be fair, it does say to report it on the GitHub. It looks maybe like it's Sodium's fault?

**Comment by jellysquid3** [comment]
I blocked the other user for their abusive remark. That is not an acceptable tone anyone needs to be using on the issue tracker.

But the issue as you have described is not the fault of Sodium. We changed the wording of the "if the game immediately crashes..." to no longer falsely label Sodium as the culprit.

In nearly every case, this is because you are using a Flatpak while having a NVIDIA GPU, which almost never works correctly (for reasons that are beyond me.) You should install your launcher of choice through the distribution's package manager instead of Flatpak, and this issue should resolve itself.

For example, Prism Launcher's website contains [many download options](https://prismlauncher.org/download/linux/) (AppImage, Portable .tar.gz, and packages for most distributions) which should work better than a Flatpak.
