### ISSUE TITLE
Sodium break BedrockWaters mod on 1.20.1

### ISSUE THREAD

**Issue by seryan4ik** [jellysquid3/Sodium#2544]
### Reproduction Steps

Install Sodium, Instal BedrockWaters

### Log File

[latest.log](https://github.com/user-attachments/files/15841818/latest.log)

### Crash Report

[crash-2024-06-14_20.49.34-client.txt](https://github.com/user-attachments/files/15841820/crash-2024-06-14_20.49.34-client.txt)

**Comment by Lolothepro** [comment]
caused by BedrockWaters

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetWaterColor(Lnet/minecraft/class_1959;)I in bedrockwaters.mixins.sodium.json:MixinBiomeColorCache from mod bedrockwaters failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap bedrockwaters-refmap.json
`

**Comment by jellysquid3** [comment]
This is a bug with BedrockWaters mixing into Sodium's code in a manner that's not compatible with current releases. We can't do anything about this unless the authors request an API or something to do what they need.
