### ISSUE TITLE
Sodium should verify the LWJGL installation at startup

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#2561]
Some launchers appear to be using the incorrect version of the LWJGL libraries, which causes problems since LWJGL doesn't follow Semver and makes breaking changes to some public interfaces in point releases.

We should check at startup that Minecraft is using a compatible version of LWJGL to avoid issues like #2560. For the Minecraft versions we currently provide updates for, this is:

- Minecraft 1.20.1: LWJGL 3.3.1
- Minecraft 1.20.6 and 1.21: LWJGL 3.3.3

This will avoid problems where users are given cryptic errors caused by binary mismatches, by instead presenting the user with a clear error message explaining that their LWJGL version is out of date.

Unfortunately (or perhaps fortunately?) many piracy launchers update LWJGL by default and don't provide any option to not do that, meaning the mod will always abort with an error for those launchers. But we're already crashing there, so implementing this check won't make anything worse.

**Comment by jellysquid3** [comment]
Resolved with https://github.com/CaffeineMC/sodium-fabric/commit/ebed80b157e86ee6415a65e6e5ea7ce1564ba587.

We still need to implement a front-end for showing error messages on Linux/macOS, but that's true of all the other early startup checks.

**Comment by IGN-Styly** [comment]
Invalid verification Procedures

**Comment by IGN-Styly** [comment]
Tested on Windows 11 and Arch linux with the latest version of prism launcher.

**Comment by IGN-Styly** [comment]
Prob due to Axiom.

**Comment by jellysquid3** [comment]
@IGN-Styly If you have Axiom installed, then yes, #2585 is relevant and the likely culprit. But you should open a new issue rather than use this one if you are erroneously receiving the error message.

**Comment by IGN-Styly** [comment]
Thanks for the help, it was my mistake. Can you close it?

**Comment by AlphaCraft9658** [comment]
Sodium requires LWJGL version 3.3.1 on my Minecraft instance, while I am actually uses 3.3.3, which prevents the game from launching. When launching with 3.3.1 it freezes the game on startup, which is why I manually set version 3.3.3. This is weird behavior. Is there maybe a different solution?

**Comment by Tsunayoshi** [comment]
Just wanted to share my experience with the LWJGL check.

I understand why the check was added, especially given the problems caused by launchers supplying incompatible LWJGL versions. In my case, however, I'm deliberately using a different version for a different reason.

On Linux, LWJGL 3.3.3 causes severe mouse/input issues for me, including double scroll inputs and the mouse jumping during GUI interactions. This makes the game almost unplayable, especially during combat.

I manually changed the LWJGL version from 3.3.3 to 3.4.1, and the problems completely disappeared. So far, 3.4.1 has been working perfectly fine for me.

I'm very glad there is a way to disable the check. Without that option, I would have been stuck with a version that doesn't work properly for me.

I'd personally be very happy if there was a proper way to choose or override the LWJGL version, ideally with a warning that configurations using a different version aren't supported if problems occur. At the moment I have to manually modify the instance configuration, and repeat that after every modpack update.

I completely understand not officially supporting arbitrary LWJGL versions. I just want to explain that there are legitimate reasons for users to override the expected version, and having an explicit opt-in option for that is a good thing.

Thanks for providing the bypass!

**Comment by jellysquid3** [comment]
In truth, we should just remove our dependency on LWJGL entirely for versions of Minecraft that use Java 25 and later. [Project Panama](https://openjdk.org/projects/panama/) was shipped in Java 22 and it allows us to bind to C APIs without also bundling a platform-specific library to shim it. The dependency on LWJGL was only so that we could avoid this.
