### ISSUE TITLE
Colormap and lightmap suport 

### ISSUE THREAD

**Issue by Doidoo207** [jellysquid3/Sodium#2569]
### Request Description

A great mod increases fps a lot, but it doesn't have colormap and lightmap compatibility and recently I created a resource pack that modifies these things, so I ask the creators of sodium to add this compatibility.

**Comment by Doidoo207** [comment]
I need it to be optifine format, thanks

**Comment by Felix14-v2** [comment]
Optifine color- and lightmap format (and even more) has already been implemented in [PolyTone](https://modrinth.com/mod/polytone), so you can already get the functionality you want. Sodium is a pure optimization mod, it shouldn't have any bloated features. Probably, the developers will not add built-in support, especially because it is already implemented outside of Sodium in a mod compatible with it.
