### ISSUE TITLE
GUI size limited to 4

### ISSUE THREAD

**Issue by MeeniMc** [jellysquid3/Sodium#259]
**Is your feature request related to a problem? Please describe.**
Yes, GUI size is limited to 4, it can be set to much larger values in Vanilla MC.

**Describe the solution you'd like**
GUI size can be set to a large value.

**Describe alternatives you've considered**
Disabling Sodium, setting the gui size with the vanilla interface, and then reloading Sodium lets one select the GUI size, but that is not ideal. However if one touches the gui size slider, then it is not possible to reset it to a larger than 4 value. 

# Workaround

In the Sodium Options screen, use `shift-p` keybinding to change the gui scale using the Vanilla Video Options screen.

**Comment by Madis0** [comment]
Just wondering, does vanilla actually show numbers higher than 4 or does it just upscale it to the max when set to auto?

**Comment by amnotbananaama** [comment]
Can you explain how you are setting the GUI scale to values larger than 4 in Vanilla? According to the Minecraft wiki, the only valid values for `guiScale` are 0-4.

If I edit the `options.txt` file to an arbitrary `guiScale` value (let's say 5), both Vanilla and Sodium load and parse that option. I don't have access to a large enough display to test, can you share screenshots comparing `guiScale` 5 vs `guiScale` 4?

**Comment by abouteiller** [comment]
![2020-08-27_03 08 49](https://user-images.githubusercontent.com/5197733/91408955-b6abf700-e812-11ea-86d7-f456b81a5adc.png)
Fullscreen on a 4k screen. Clicking the button cycles 1-9-Auto. In windowed mode it cycles 1-4-Auto.

**Comment by amnotbananaama** [comment]
So under this enhancement would Sodium just increase the max GUI scale to 9? I’m not sure what the maximum GUI size should be, we need to specify some limit.

**Comment by MeeniMc** [comment]
Looks correct. That's what the Vanilla config does.

**Comment by silversquirl** [comment]
Vanilla appears to change the maximum value based on the size of the window (or the screen resolution in full screen). Perhaps Sodium could implement something similar.

**Comment by nisutec** [comment]
Hello,
Is a fix for this problem current under development.

**Comment by ImperatorStorm** [comment]
no

**Comment by nisutec** [comment]
Ok but the workaround works thx

**Comment by Seegras** [comment]
This is a problem on 4k where the GUI is either way too big, or much too small (I use 6 for a near "auto on 1080p"-feeling) 

Especially when streaming or doing videos, where you want to have big bold GUI, but one that still does show everything with no overlapping elements.

**Comment by 0AA55H** [comment]
I just write to confirm that editing/setting `guiScale` to 6 in `options.txt` works. Just tested on Minecraft 1.18.1 with fabric/sodium and 4k. BTW, my monitor is 1920x1200, but i use nvidia DSR factors to force the game to render in 4K and then it is downsampled to native resolution. This puts a lot of pressure on the GPU of course, but the result is fantastic 😊

**Comment by MeeniMc** [comment]
pr #1013

**Comment by aschoettler** [comment]
Like many people, I occasionally play Minecraft on my laptop. But I also sometimes play using an external monitor. I have a "retina" macbook pro which has a 2880x1800 resolution display on a 15-inch screen. On the external monitor I use `guiScale 3` but I would like to see GUI scale options that go above 4 on my laptop since the gui elements are too small for me to see clearly at that scale. This is all to emphasize that I believe anyone using sodium on a macbook pro made in the last 7ish years may be affected by this issue.

The best workaround I have found is to manually open `options.txt` in a text editor and change `guiScale` to 5. This prevents having to launch the client 3 times per sitting (as in the other workaround), reducing it to 1x if I remember to change the file first.
I was also able to implement the 1-line change in the PR mentioned above (#1013) which works perfectly, and it would be nice to see this added to the main branches.

**Comment by IMS212** [comment]
This was fixed in 0.4.3.
