### ISSUE TITLE
Waterlogged double slabs and stairs have Z-fighting when rendered next to water

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2606]
### Bug Description

https://github.com/CaffeineMC/sodium-fabric/commit/3d4cf6a957b0065e57518a5f188c23deaaa1bf7f 

I suspect that this commit causes undesirable side effects with waterlogged double slabs.

Sodium:

![image](https://github.com/user-attachments/assets/1560ca3e-625e-4998-9e94-ff98033caf4a)

Vanilla:

![image](https://github.com/user-attachments/assets/b97181e6-297e-4631-9a20-1696a7f17594)
‎ 
‎ 
‎ 
It causes Z-Fighting with Sodium
i.e:
![2024-07-16_23 56 33](https://github.com/user-attachments/assets/71f2e038-0d82-4739-8771-8af291dc78bf)
![2024-07-16_23 56 31](https://github.com/user-attachments/assets/e6a23934-38e8-42de-b437-c2c6f7e95398)

### Reproduction Steps

Make a wall of waterlogged double slabs
Switch to spectator mode
Go into the wall or move away from the wall

### Log File

https://mclo.gs/wS0lUP4

### Crash Report

*

**Comment by douira** [comment]
Vanilla's rendition of this scene is objectively worse.

**Comment by Lolothepro** [comment]
> Vanilla's rendition of this scene is objectively worse.

Yes, but it causes Z-Fighting

**Comment by douira** [comment]
There's Z-fighting in both images

**Comment by Lolothepro** [comment]
> There's Z-fighting in both images

Both images are with Sodium

**Comment by douira** [comment]
Oh I see

**Comment by MeeniMc** [comment]
presumed root cause is https://github.com/CaffeineMC/sodium-fabric/commit/bc38d5638d391d3dfd1a928f6c7981116a7510f7 : that code changed the test on `isFaceSturdy` on the `pos, dir` to the `adjPos, dir.getOpposite()`. It makes sense for the case when the water is occluded by a neighbor block, but that removed the test for water being occluded by the faces of the waterlogged block itself.

This also causes z-fighting on full-faces of waterlogged stairs.
