### ISSUE TITLE
Fog: off

### ISSUE THREAD

**Issue by private-effort** [jellysquid3/Sodium#262]
Could you add the ability to turn off the fog

**Comment by amnotbananaama** [comment]
Users will be able to disable the Overworld fog in the next release. For other kinds of fog, users can install another mod

**Comment by Tommeh1** [comment]
You can use NoFog although there is an issue on sodium's side that results in the client always rendering the max server render distance that has yet to be fixed.

**Comment by jasikpark** [comment]
What is the bug forcing max render distance? I would like to use Sodium since it gives me better FPS than Optifine, but rendering at max server view distance would kind of do the opposite for me.

**Comment by amnotbananaama** [comment]
@jasikpark I don't know if this is tracked properly on a specific issue, but it is a known bug. This bug *only* occurs when using other mods in conjunction with Sodium, and *never* with Sodium itself.

Sodium uses fog for determining which chunks should be rendered or not. Using another mod that hides the fog (for example NoFog) confuses Sodium and makes it think EVERYTHING possible should be rendered. This means that it will attempt to render the max view distance possible (server render distance)

**Comment by jasikpark** [comment]
So would turning off the fog culling setting fix this possibly?

**Comment by Excigma** [comment]
In short, no.

Sodium takes advantage of the fact that (vanilla Minecraft's) fog will be at different distances with different render distances. This means Sodium can use vanilla's fog to control how much to render and also not render chunks completely hidden by fog (ie chunks out of your render distance).

This is called fog culling. 
You want fog culling on, not off as there is no point rendering stuff you cannot see.

The problem is that you are disabling fog, meaning that there are no chunks hidden by fog, _as there is no fog_.
This means Sodium will not be able to use fog to cull anything and will render the max server render distance.

By installing a mod that removes fog, you're essentially turning off fog culling _because you are turning off fog_.
_Fog culling does not work without fog._

**Comment by jasikpark** [comment]
Ok - well thanks a lot for your help!

**Comment by amnotbananaama** [comment]
Re-opening this issue after [discussion](https://discord.com/channels/602796788608401408/602805971391217683/851208732703981658) in the discord server. 

Sodium will **not** be adding an option to disable fog, but instead add a compatibility mode when fog is disabled by another source (such as another mod).

**Comment by jasikpark** [comment]
What would the compatibility mode look like? This definitely seems like the way to go though!
