### ISSUE TITLE
Add missing renderer configuration options

### ISSUE THREAD

**Issue by douira** [jellysquid3/Sodium#2700]
Indigo renderer creates a `indigo-renderer.properties` config file in which various rendering options can be configured. Sodium's implementation lacks these options which means users who previously used this to change the appearance of path blocks can no longer do so. Furthermore users are unable to install indium which adds these options itself. There's also other options in this config file, but they seem less relevant to the user experience.

The Sodium Shadowy Path Blocks mod doesn't exist for NeoForge, so this is either a problem of adding the config options to sodium itself or porting SSPB to forge. SSPB adds back darkened path blocks but with some improvements. Porting SSPB would leave the other options unimplemented, I don't know how important those are.

It should be noted that embeddium has apparently re-added this configuration file.

**Comment by PepperCode1** [comment]
Most of the options that Indigo provides are toggles for smooth lighting fixes. Considering one of Sodium's advertised features is smooth lighting fixes, I don't think they should be configurable, or at least not as configurable as in Indigo. Indium removed most options to match this; the only two options left are "always tessellate" and "AO mode". In Sodium, all block buffering already goes through FRAPI, so the former is unnecessary. AO mode allows switching to the vanilla smooth lighting pipeline, which is slow and full of bugs, or disabling enhanced lighting, which may break modded models. I don't see a reason that the user should have the ability to alter smooth lighting so much and disable bug fixes so easily.

I disagree with using SSPB as a reason to re-add these options; if this functionality is meant to be configurable within Sodium, then the name(s) and behavior of the corresponding option(s) should reflect this instead of specific and internal properties that most users won't understand. Furthermore, these option(s) should be part of the regular config and accessible from in-game.

**Comment by douira** [comment]
Thanks for the explanation, then I think it's best if we just rely on SSPB to provide vanilla-like (but better) lighting on path blocks. A port should probably be made then to give users the option to have vanilla-like path lighting on forge too.
