### ISSUE TITLE
Resource Pack checks don't work at all in 0.6.0

### ISSUE THREAD

**Issue by mapleexists** [jellysquid3/Sodium#2709]
### Bug Description

As of 0.6.0, none of the resource pack checks implemented previously work. This includes letting the user know of any errors caused by usage of core shaders on top of the "ignored_shaders" field within the pack.mcmeta

### Reproduction Steps

Download a pack that uses shaders (i.e., Brush-Up!), load it in game, observe the broken shaders on items
There is a list of shaders that should be ignored within the pack's metadata, however this does not affect the shaders
Additionally, observe how sodium no longer reports issues with core shaders

### Log File

[latest.log](https://github.com/user-attachments/files/16733672/latest.log)

### Crash Report

[crash-2024-08-23_17.08.58-client.txt](https://github.com/user-attachments/files/16733683/crash-2024-08-23_17.08.58-client.txt)

**Comment by mrmangohands** [comment]
Reproduced with 0.5.11

**Comment by mrmangohands** [comment]
Also 0.5.9, guess this broke a good while ago

**Comment by mrmangohands** [comment]
Looks like it was introduced in 0.5.8

**Comment by pajicadvance** [comment]
This issue is not reproducible on the 0.6 beta for 1.21 on Fabric Loader. I've tested the waving leaves pack from Vanilla Tweaks, both without the added ignores and with added ignores. Without the ignores, Sodium shows a resource pack error, with them, the shaders are ignored correctly and no error shows up.

Resource packs used for testing:
[VanillaTweaks_r701544_MC1.21.x-ignored.zip](https://github.com/user-attachments/files/16826758/VanillaTweaks_r701544_MC1.21.x-ignored.zip)
[VanillaTweaks_r701544_MC1.21.x.zip](https://github.com/user-attachments/files/16826759/VanillaTweaks_r701544_MC1.21.x.zip)

Seeing that the original issue report is made with Quilt Loader, it's worth checking if this problem is caused on their side.
