### ISSUE TITLE
License vote?

### ISSUE THREAD

**Issue by diaphragm-workplace** [jellysquid3/Sodium#2737]
**Before one marks this as invalid, hear me out.**

Closing previous discussions about licensing to collaborators only has made it more difficult for the broader community to share their opinions. As a result, people are forced to seek other platforms: other websites, proprietary messaging services, IRC channel archives and mailing lists. I am aware that this will be difficult to moderate, but this will keep talks in a singular place for everyone to look at and will benefit everyone involved.

The new license not allowing "competing solutions" (forks) might at first sound like a great idea with the best of intentions. However, the previous LGPL 3.1 license allows them for a reason: to allow contributions to get upstream. And now there are many forks based on the older license that we can't use. ~~Regarding the consent stuff, ***as far as I am aware*** contributors were only told to "say that you agree". They *could* research it further, however I am pretty sure many agreed out of trust and because they just were asked nicely.~~

## I suggest holding a public vote about the future licensing of this project. It doesn't even have to be one of those we used before.

I recognize that switching the license and getting everyone to consent was already a headache and this would introduce another one. However, it might be worth hearing not only what the those behind the code but also from the community that relies on it.

Before anyone asks, no. This wasn't AI generated.

**Comment by TheUserCreated** [comment]
Please read https://github.com/CaffeineMC/sodium-fabric/issues/2400 carefully, as all the contributors with copyrightable contributions were already contacted and agreed to the license change. Further, you have *several* of the facts of the situation wrong. Embeddium was not made "in response to the license change", the license change came after embeddium announced it wanted to target fabric. The details are in the previously linked issue.

**Comment by diaphragm-workplace** [comment]
My bad on Embeddium, will remove it from the issue body

**Comment by TheUserCreated** [comment]
Insinuating that contributors "were only told to say they agree" is also wrong. You can plainly see in the linked issue. 

This entire issue comes off as trying to misconstrue the facts intentionally, so that people who are entirely uninvolved with the project and have never contributed can again threaten the author with their own work (do what we want or we'll fork). Once again, please read issue #2400

**Comment by diaphragm-workplace** [comment]
Ok

**Comment by jellysquid3** [comment]
The community doesn't get a "vote" on software they didn't help write in any capacity. The fact you keep using language like "we" and "ours" when you have zero contributions to the project is ridiculous. [Open source is not about you](https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9), and unfortunately it's always the people who preach it who act in this way.

We contacted each contributor to the project and asked for permission. I had extensive conversations with many of those contributors about the licensing terms and at every point made sure that people who were agreeing to the terms were fully informed about what they were.

The fact that you are even _insinuating_ that others were manipulated into accepting a license change is reason enough to ban you from the issue tracker. Because you don't know what you're talking about, and you're continuing to spread misinformation that is harmful to me and others, simply because it fits your narrative.

**Comment by jellysquid3** [comment]
Also, to be abundantly clear:

- These forks of Sodium for legacy versions of Minecraft are implementing optimizations generally only relevant to those versions, if they are implementing optimizations at all. We aren't interested in legacy versions of the game so there was likely never going to be a lot of upstreaming in the first place.
- There is no reason why those people could not submit a pull request to upstream with a license grant for us to use it. Copyright holders retain the original ownership of their work and can license it under as many different terms as they want, without restriction. We do not ask for people to transfer their copyright to us (and never will), we just ask for it to be provided under terms we can use.

**Comment by diaphragm-workplace** [comment]
> The fact you keep using language like "we" and "ours" when you have zero contributions to the project is ridiculous. 

So if I change some locale strings and bump some random dependency are we even? /j

> The fact that you are even insinuating that others were manipulated into accepting a license change is reason enough to ban you from the issue tracker.

I never said they were manipulated. I thought what happened was "yeah sure whatever". When I was told that's not what really happened I crossed that out from the issue body.

> and you're continuing to spread misinformation that is harmful to me and others

That's why I used the "as far as I am aware..." language.

I am sorry if this made you feel this way and I respect your choice.
