### ISSUE TITLE
Custom block render layers

### ISSUE THREAD

**Issue by Entropy159** [jellysquid3/Sodium#2774]
### Request Description

It would be very nice if there was an API or something for mod developers to add custom block render layers without crashing the game. I'm trying to make a block with a shader, but due to Sodium I can't.

**Comment by jellysquid3** [comment]
There are no plans to add this functionality currently. The first step would be for mod loaders to begin supporting custom render types in Minecraft, since every mod is otherwise forced to apply mixins to the game, which are impossible for Sodium to handle. 

That said, the rendering methods and shaders used in Sodium are _very_ different, and subject to constant changes and improvements. Even if this API was provided, mods using it would likely break with every update, and there is nothing we can reasonably do to prevent that.
