### ISSUE TITLE
Incompatible with vanilla tweaks..

### ISSUE THREAD

**Issue by Rashmin47** [jellysquid3/Sodium#2776]
### Request Description

When vanilla tweaks and sodium is added it is incompatible.

**Comment by pajicadvance** [comment]
Some Vanilla Tweaks resource packs don't work with Sodium because they use core shaders. This is clearly shown on their website when selecting resource packs, for example wavy water:
![image](https://github.com/user-attachments/assets/bc37e774-e02c-458c-adbf-aff925686d67)

**Comment by ADPlayz19** [comment]
I am using an older version (maybe that being the issue at hand) but in 1.20.1 even when I don't choose options that might be incompatible with Sodium/Optifine the resource pack still refuses to load. When I remove Sodium the resource pack works perfectly fine. Like I said, it could be because I am working with an older version but I also did choose resource packs for specifically 1.20. I attached a file containing all the resource packs that I added. If anyone could tell me which ones are incompatible I'll remove them and try again.

[VanillaTweaks_r383660_MC1.20.x.zip](https://github.com/user-attachments/files/22868892/VanillaTweaks_r383660_MC1.20.x.zip)

**Comment by davepusey** [comment]
It's likely `CloudFogFix`

**Comment by davepusey** [comment]
The VT website will also tell you which ones don't work with Sodium when you hover over them.

For example on Full Bright...
<img width="206" height="162" alt="Image" src="https://github.com/user-attachments/assets/628e24f3-c6eb-4f60-8baa-d866c45d8db9" />

**Comment by jellysquid3** [comment]
Sodium will not "prevent" any of your resource packs from loading. We very frequently get reports about this, but it has been determined in all cases that a resource pack is incompatible with that version of Minecraft or specific graphics card driver.
