### ISSUE TITLE
Sodium crashes in all 1.16(.x) versions with no explanation.

### ISSUE THREAD

**Issue by TheoMusicGR** [jellysquid3/Sodium#282]
When I have sodium installed, my game will crash with no explanation. I use fabric.

**Comment by amnotbananaama** [comment]
Please use the issue template, it exists for a reason. Please attach the crash log, either in a code block
\`\`\`
like this
\`\`\`
or as a link to a paste site such as a GitHub gist, hastebin or pastebin.

**Comment by Kanive** [comment]
> Please use the issue template, it exists for a reason. Please attach the crash log, either in a code block
> ```
> like this
> ```
> or as a link to a paste site such as a GitHub gist, hastebin or pastebin.

Thanks for your help, amnotbananaama! I'm glad we all worked together to clear up this issue.

**Comment by aestheticccccc** [comment]
hey, I have the same problem, here is the error that I get on the launcher after the crash : https://pastebin.com/vwBXq8GT

**Comment by henriz** [comment]
Verified. Same issue here. Also worth to note; downgrading to a version which previously worked fine on 1.16.1, yields the same crash.

**Comment by jellysquid3** [comment]
Are any other mods being used here? Can you upload a client log file (not the crash file)?

**Comment by Tommeh1** [comment]
Seems like a broken config to me

**Comment by henriz** [comment]
I use fabric api, lithium  phosphor, wl-zoom and voxelmap. All latest versions. Will upload the log when im back at computer.

**Comment by henriz** [comment]
Removing the old config files from configs/ did not resolve the issue.

Here the logfile: https://pastebin.com/T0YDkgaR

**Comment by amnotbananaama** [comment]
@aestheticccccc Your crash log is incomplete. Underneath the `Stacktrace:` section, there should be a `-- System Details --` section. This is one of the most crucial parts of the crash log, as it contains important configuration information such as Minecraft version, Fabric version, and what mods you are using. See [here](https://pastebin.com/raw/dmB7Vr0d) for an example. 

Please attach a full crash report, and note that the preferred location for support is `#tech-support` in Jelly's discord.

**Comment by henriz** [comment]
This is the complete contents of the latest.log file. There is no more.

Also, interesting to note is that this crash also happens with ONLY sodium as mod (so no other files in the mods folder)

And, with all due respect, stop tring to put this crash on the user. The logfile I provided gives a clear error. I am a developer myself.

All versions are latest release versions. 

Minecraft 1.16.2
sodium-fabric-mc1.16.1-0.1.0

**Comment by amnotbananaama** [comment]
@henriz We can't help you, you're using an unoffical build for 1.16.2. You'll need to either contact the author of your unofficial fork for support, or use the official build for 1.16.1.

**Comment by henriz** [comment]
@amnotbananaama You mean you won't help me. Note that I'm not the only one reporting this issue.

I AM using the official build, not an unofficial fork. Downloaded it here:
https://github.com/jellysquid3/sodium-fabric/releases/tag/mc1.16.1-0.1.0

If your goal is just to say it's user error, please stop and let the developer reply.

**Comment by jellysquid3** [comment]
@henriz Hi. Developer here. I bring people onto my team because they're well educated and can speak on my behalf.

In this case, they are correct.
- You are using Sodium for Minecraft 1.16.1 on Minecraft 1.16.2.
- Regardless of you using the official build on the wrong version-- which they could have only derived after you edited your messages to include such critical information-- we don't support Minecraft 1.16.2.
- You uploaded a file other than what was asked. There is a difference between the crash log and log file, and you uploaded the latter.

Please take your attitude elsewhere in the future or you will be barred from using this issue tracker. There is no place for rudeness towards any of the collaborators here.

**Comment by FlashyReese** [comment]
@henriz If you haven't noticed you're trying to use the 1.16.1 version on 1.16.2 which isn't supported yet.

**Comment by jellysquid3** [comment]
I meant to hide that comment -- not delete it. GitHub apparently doesn't ask confirmation for it. Apologies.

Regardless, this issue is too vague and doesn't represent any one issue. The crashes reported have been caused by different things which should have issues filed separately. In particular, the one which occurs when a corrupted config is encountered is tracked in #219.

@TheoMusicGR Please update this issue with the requested information so that it can be addressed and re-opened if necessary.

**Comment by henriz** [comment]
@jellysquid3:

They are not correct. There are 3 different people reporting the same issue.

First off; I reported I was using last versions of everything. Unedited. They could have derived that I was using the latest version. Also, they flatout stated I was using an unofficial fork, which I was not.

You yourself asked for the client log, which was exactly what I uploaded.

Apologies if I come across rude, that's what you get if you don't take the time to actually read what people are saying, like you just did again.

Bar me what you want. I have fixed the issue myself in the mean time, and can confirm it's a bug in the code, or rather, a change in code which makes sodium do something wrong. This should also affect 1.16.1, but I haven't tested that.

Have a good one.
