### ISSUE TITLE
Sodium is decreasing fps not increasing

### ISSUE THREAD

**Issue by JackP-07** [jellysquid3/Sodium#2873]
When I use sodium I get around 200-300 fps which is still a lot but in vanilla I get like 400-500 fps sometimes even higher and I don't know why. I do have some other mods and resource packs but not any that would drastically decrease performance mostly just quality of life mods like better grass, better leaves, fast leave decay and stuff of that sort and the resource packs like fresh animations, vanilla tweaks, a few texture changes and simple stuff like that. I am playing in 1080p and my specs below.

GPU: GTX 1660 Super
CPU: i7-8700
RAM: 16GB 2666Mhz 2x8GB
Storage: 512Gb NVME SSD

If there is any way you can help I would appreciate it!

**Comment by Felix14-v2** [comment]
Please, send some screenshots of a test scene with and without Sodium for comparison with the debug screen (F3) opened. The vanilla renderer has less overhead and sometimes works faster in some cases, but in heavily loaded scenarios like higher render distance or a high number of entities Sodium generally performs noticeably better.

**Comment by vogon-poetry** [comment]
"bushy leaves" mods and resource packs like Better Leaves do have a large performance impact because of the additional geometry involved. Regardless, for these sorts of support issues you should go to the Discord support forum, not the issue tracker.

**Comment by JackP-07** [comment]
The first picture is vanilla and the second one is sodium. I was getting more fps in this new world that I made but I still have less fps in vanilla than in sodium 

![2024-11-11_00 59 38](https://github.com/user-attachments/assets/e508ccdf-c60e-49eb-afc5-24d78d48fed4)
![Sodium](https://github.com/user-attachments/assets/1d64adf7-5bcb-47b6-8a76-f9dccaa10838)

**Comment by jellysquid3** [comment]
Your screenshots indicate no problem. Looking at the peak frame rate is not a helpful metric and it doesn't represent anything important about the performance of the game. And besides, you have a bunch of other resource packs and mods which are going to decrease performance (even more so when the game has so little work to be doing with such a short render distance.)

In other words, you are worrying about the wrong things. Consider increasing your graphical settings (i.e. render distance) and set a frame rate limit so that your computer can focus on the more important things in the game, rather than rendering useless frames you can't see or benefit from.

**Comment by jellysquid3** [comment]
And, to be clear, the peak frame rate in very lightly loaded scenarios like this _will be worse_ on NVIDIA GPUs, because we have to apply workarounds to disable broken functionality in the NVIDIA Graphics Driver. They could fix their driver, but they don't, because our mod isn't big enough and they don't care.

But this limitation should not ever matter unless you are using very short render distances on very powerful computers. In real scenarios, it doesn't matter.

**Comment by JackP-07** [comment]
Thanks for the help, I did try removing all the other mods I had beside sodium an lithium and I increased chuck render distance and I did get better performance guess the mods i had decreased performance more than I thought
