### ISSUE TITLE
Potions do not render correctly with "Faithless" resource pack 

### ISSUE THREAD

**Issue by AngryFIlly888** [jellysquid3/Sodium#2885]
### Bug Description

Potion item textures in the Faithless Pack are completely broken when using any version after 0.5.11

![Sodium 5 11 1 21](https://github.com/user-attachments/assets/609f2a0e-1397-4848-a4b0-736b3cbea837)

![sodium 0 6 0+ 1 21 x](https://github.com/user-attachments/assets/45ba4d50-3ba4-4d27-94d2-3a0f1338c7fb)

### Reproduction Steps

Install any version of sodium after 0.5.11 and enable Faithless texture pack for relevant game version.

### Log File

[latest.log](https://github.com/user-attachments/files/17792986/latest.log)

### Crash Report

[crash-2024-11-17_18.20.12-client.txt](https://github.com/user-attachments/files/17792989/crash-2024-11-17_18.20.12-client.txt)

**Comment by douira** [comment]
Have you tried using the official non-beta release?

**Comment by AngryFIlly888** [comment]
Yes. That is one of the screenshots. The first screenshot is 0.5.11

**Comment by douira** [comment]
Your log indicates you're using sodium 0.6-beta2

**Comment by AngryFIlly888** [comment]
that is because I took the log from the broken one. Why would I give the log of the working version?

**Comment by douira** [comment]
The latest release is 0.6, and the question is whether it's still broken on that version. The issue might have been fixed between 0.6 beta-2 and 0.6.

**Comment by AngryFIlly888** [comment]
yes, it is still broken

**Comment by AngryFIlly888** [comment]
[latest.log](https://github.com/user-attachments/files/17793060/latest.log)
![lastest](https://github.com/user-attachments/assets/83c15dd5-ac1b-4608-b231-243f8b5ec1d5)

**Comment by jellysquid3** [comment]
The resource pack is modifying Core Shaders (see file `rendertype_entity_translucent_cull.vsh`), [which are not supported.](https://github.com/CaffeineMC/sodium/wiki/Resource-Packs)

Unfortunately, because the author also disabled the warnings for incompatible shader packs, Sodium did not correctly warn you that things would render incorrectly.

You can fix the problem yourself by modifying the resource pack's config file `assets/minecraft/shaders/config.txt` and disabling the option `Potion_Variants`.

**Comment by AngryFIlly888** [comment]
So this problem with never be fixed?

**Comment by douira** [comment]
With Minecraft 1.22 there is a better way of doing this that doesn't involve core shaders.
