### ISSUE TITLE
RTX HDR doesn't work on 0.6.2 for 1.21.4

### ISSUE THREAD

**Issue by VindSole** [jellysquid3/Sodium#2908]
### Bug Description

RTX HDR stopped working when in fullscreen mode when using Sodium 0.6.2 for 1.21.4 and 1.21.3.

Previous version is working correctly. I suppose it also affects the "Auto HDR" function in Windows 11.

### Reproduction Steps

1. Add a profile for Java.exe in Nvidia Profile Inspector and enable RTX HDR for it with the NvTrueHDR app.
2. Open Minecraft 1.21.4 with the latest Sodium update.
3. Switch to Fullscreen, it should trigger RTX HDR.

### Log File

[latest.log](https://github.com/user-attachments/files/18001448/latest.log)

### Crash Report

[crash-2024-12-03_19.40.42-client.txt](https://github.com/user-attachments/files/18001456/crash-2024-12-03_19.40.42-client.txt)

**Comment by jellysquid3** [comment]
Sodium intentionally tries to evade detection by the NVIDIA graphics driver due to a number of severe bugs that have not been getting fixed. This logic [changed in Sodium 0.6.1](https://github.com/CaffeineMC/sodium/commit/5e7c8ac4d78d7085041f3c8d477774480dba7dd4) because recent driver updates broke our workarounds, but the new solution makes it so user-specified profiles no longer work.

Please contact [NVIDIA Support](https://www.nvidia.com/en-us/support/) and make a bug report if you need this functionality... we cannot do anything to fix the problems with their driver.

**Comment by jellysquid3** [comment]
There might be hope in the future that Sodium can install custom profiles into the NVIDIA Control Panel (see our experimental code [here](https://github.com/CaffeineMC/sodium/commit/37af6225b71ccaacad705c150114da33f9936813)) but we haven't found a way to override the profile it chooses to use, since they hardcoded the detection of Minecraft into the OpenGL driver.

**Comment by VindSole** [comment]
AutoHDR seems to be working though until this gets fixed.

**Comment by melgu** [comment]
Auto HDR does not work for me in 1.21.7

~It works for the Launcher, but not the game itself.~
It only works when the game is windowed.
