### ISSUE TITLE
Bright lines at block borders in enclosed spaces

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#302]
Would have expected that this brightness would be greater in area, but it appears mostly localised to the edges of blocks. Perhaps the ambient occlusion from walls is too extensive?

![2020-09-10_18 30 47](https://user-images.githubusercontent.com/52297970/92773195-4ebdea80-f394-11ea-8449-c61f06ce75dc.png)
![2020-09-10_18 33 40](https://user-images.githubusercontent.com/52297970/92773201-4fef1780-f394-11ea-95ea-91542a3407de.png)

**Comment by NoComment1105** [comment]
For me on the latest commit the lines were faintly visible at 100% brightness.
![2021-03-17_06 23 09](https://user-images.githubusercontent.com/67918617/111424161-464ebf80-86e9-11eb-892d-822a8c0634bc.png)

**Comment by muzikbike** [comment]
Still present in 0.3.0:
![2021-08-28_00 27 08](https://user-images.githubusercontent.com/52297970/131197870-c76470ff-b649-4989-9158-4f0b1a527ab1.png)

**Comment by MeeniMc** [comment]
Can replicate in 0.4.10, but Vanilla is a whole lot uglier actually. I'd call the reported behavior an improvement.

**Comment by jellysquid3** [comment]
This is not solvable without completely reworking how lighting works. These artifacts are not a bug, they are a limitation of the current approach of per-vertex colors, and how colors get interpolated across surfaces. The only way to solve this would be to use a special tap filter and light map textures, rather than per-vertex colors. Doing so is not completely outside the realm of possibility for us (as it may have performance advantages), but right now it's not being considered.
