### ISSUE TITLE
Are support for later versions of OpenGL planned? (OpenGL 4.5 or 4.6)

### ISSUE THREAD

**Issue by CalXee** [jellysquid3/Sodium#312]
I've always been so in awe at how effective Sodium is. It encouraged me to research more on OpenGL and it turns out that OpenGL 4.6 is the latest version. I'm not sure whether upgrading OpenGL would optimize the game even further, but I hope it would.

**Comment by jellysquid3** [comment]
Using a newer version of OpenGL doesn't improve performance, and the game already requests a forward-compatible context (which in effect means the game is always using the latest OpenGL version supported.) If there turns out to be additional features we can use in OpenGL 4.5+ to improve performance, we can of course look into those when they come up.
