### ISSUE TITLE
Allow gamma values outside the default range (0-100)

### ISSUE THREAD

**Issue by nij5** [jellysquid3/Sodium#347]
The nether is typically dark, so either increasing the slider range or allowing users to click the number that displays gamma value and input a different value could be helpful.

**Comment by silversquirl** [comment]
I don't think this is a good fit for Sodium. There are already "full bright" mods out there that allow this. If you want, you can also modify the configuration file manually to override the in-game limits.

As for why I don't think it's a good fit: Sodium is an optimization mod, that also happens to fix a few graphical issues. This limited scope makes it very attractive for people who want to play on low-spec machines but with an experience very close to, if not exactly the same as, vanilla.

For example, Sodium is allowed in the speedrunning community, while OptiFine is not due to its additional features. Adding something to Sodium that could be considered a cheat, such as allowing a higher gamma value, is not only out of scope, but could also sabotage the goodwill Sodium has in communities such as those.

**Comment by CalXee** [comment]
Very well said, @vktec 
If you want you can simply modify the gamma value in options.txt for the same result.
One of Sodium's main attractions is it's FPS boosting capabilities without any additional "gameplay" features that give players a minor yet present advantage over vanilla players. As vktec said, adding features such as this very much could make this mod less appealing to that audience.

**Comment by jellysquid3** [comment]
This is not being considered, and for me personally it falls into cheat functionality. Sodium is an optimization mod, not a features mod.
