### ISSUE TITLE
Game keeps crashing when using ReplayMod (sometimes not)

### ISSUE THREAD

**Issue by zxcdevlop** [jellysquid3/Sodium#351]
Sodium doesn't work with ReplayMod. Whenever I try to render a video, the game freezes, until I have to force quit it. Sometimes I don't even have to run ReplayMod at all! It happens to me randomly when I'm playing single-player. Please, fix this problem. I want to continue using it.

**Comment by altrisi** [comment]
This is a known issue with ReplayMod, currently it's not possible to render a video with Sodium installed, but you can still record it without problems. In theory, ReplayMod should notify you, but it seems that may not work.
See ReplayMod/ReplayMod#150
You just have to temporarily remove Sodium when rendering the video, but you can have it while recording.

If the game crashes without ReplayMod or in another context, then that's another issue.
Are you using the latest version of both?

**Comment by dbechrd** [comment]
I've encountered this ReplayMod issue with other mods installed, even when not having Sodium installed. I had to disable all other mods to fix ReplayMod. This is almost certainly not Sodium's issue to fix.

**Comment by Johni0702** [comment]
> I've encountered this ReplayMod issue with other mods installed, even when not having Sodium installed. I had to disable all other mods to fix ReplayMod. This is almost certainly not Sodium's issue to fix.

No, this issue is specific to ReplayMod+Sodium and we already know exactly what the cause is and what needs to be done to fix it (see the issue on ReplayMod's repo linked above).

There may of course be other compatibility issues, those are unrelated to this one though. If they do match the OP's description, then please report them cause I've only every heard of this exact issue with Optifine (which I have worked around a long time ago) and Sodium (which this issue exists for).

**Comment by IMS212** [comment]
Fixed since Sodium 0.4.4.
