### ISSUE TITLE
Entities in water disappear at certain angles (when outside of water)

### ISSUE THREAD

**Issue by SekoiaTree** [jellysquid3/Sodium#354]
(Note: this is not my video, the person who's video it is wanted someone else to open the issue)
If the player is outside of water and there are entities in the water, the entities disappear at certain angles.

Video:
https://cdn.discordapp.com/attachments/602805020861267968/766655976543223828/HIiPRNcDxZ.mp4
Imgur link (so you don't have to download):
https://imgur.com/pEjte0c

Note 2: spacey claims to have the same problem in the discord. I'll send over the video once I get it

**Comment by SekoiaTree** [comment]
![image](https://user-images.githubusercontent.com/51149447/96271023-acb1a380-0fcc-11eb-844b-3bb00861a8f6.png)
A pretty good image by spacey. Probably pretty useful considering it's not the entity itself getting culled but the actual texture
A video, also by spacey.
https://youtu.be/ssvLvLENB0Y

**Comment by amnotbananaama** [comment]
~~We've had conflicting reports in the [Discord](https://jellysquid.me/discord) about this bug report. One user is [saying](https://discordapp.com/channels/602796788608401408/602805020861267968/766678978357755964) that they can reproduce this issue in vanilla (without Sodium). Another user is [saying ](https://discordapp.com/channels/602796788608401408/602805020861267968/766694149830737980) this is probably caused by another mod that spacey is using.~~

Regardless, I feel comfortable saying this is not caused by Sodium. I'm going to mark this as a feature request for now. ~~Can you provide a full list of mods (with versions) that spacey is using as well as an F3 screenshot?~~

**EDIT:** This has been confirmed to be a vanilla bug. No need to send any mod information.

![image](https://user-images.githubusercontent.com/6319658/96304133-90f8ce00-0fc9-11eb-8853-369519a3fad6.png)

I'm leaving this open as a feature request, it's ultimately up to Jelly if this is within the scope of Sodium to fix.

**Comment by Spacebarium** [comment]
Attaching clearer videos by fancyflacko for clarity
[With Sodium](https://imgur.com/a/9zGimCX)
[Without Sodium](https://imgur.com/a/Edd82Zh)
