### ISSUE TITLE
Game Crashing with Sodium

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#385]
### Reproduction Steps
1. Sodium is placed into mod folder.
2. The game crashes if Sodium is present.

### Crash Report File
[GitHub Gist](https://gist.github.com/windows-virus/873998a661e3144da6754d5115a955ba) 

### Additional Information
The game does not crash if Sodium is not present so most likely a mod/s is conflicting is with Sodium (I have like 150+ mods, so finding the culprit mod/s would not be an easy task). Not Enough Crashes show that Sodium is conflicting with the Fabric Mod Loader.

**Comment by LambdAurora** [comment]
This crash is caused by the library mod Geckolib which is present in the crash report you sent, this is a known issue which has been already reported on geckolib bernie-g/geckolib#26.

This issue is caused by something used in Geckolib (access widener) which badly conflicts with Sodium as it changes something in the code which Sodium doesn't expect to. This can't really be fixed by Sodium and has to be fixed by Geckolib, in the linked issue the author said the compatibility problem will be fixed in a newer version of Geckolib which is not yet released.

**Comment by ghost** [comment]
Thank you for the quick response. Crashing has stopped.
