### ISSUE TITLE
i dont have any idea about what is this

### ISSUE THREAD

**Issue by Lucioo1** [jellysquid3/Sodium#387]
![image](https://user-images.githubusercontent.com/74187651/98539759-eb6e0d00-229d-11eb-9bf4-d029e40562af.png)

- Java Version: 1.8.0_241
- CPU: Intel(R) Core(TM) i5-4210M CPU @ 2.60 Hz
- GPU: NVIDIA GeForce 840M

**Comment by amnotbananaama** [comment]
1) It looks like Minecraft is using your integrated GPU instead of your discrete GPU. This is a support issue instead of a bug, you should join [the discord](https://jellysquid.me/discord) for help with that.

2) Because Minecraft is using your integrated GPU, you are experiencing #179. You can workaround this by going to Options -> Video Settings -> Advanced and setting "Chunk Renderer" to 3.0 or 2.1. This would fix your issue, but ideally you want to actually use your graphics card.
