### ISSUE TITLE
Block lines visible even when anti aliasing is entirely turned off

### ISSUE THREAD

**Issue by campbebj** [jellysquid3/Sodium#404]
### Expected Behavior
No extra lines between blocks

### Actual Behavior
https://bugs.mojang.com/browse/MC-1794 is the best explanationof the behavior im seeing

### Reproduction Steps
1. Install sodium
2. load any world
3. look at the edges.
(happens on both of my machines, i have anti aliasing turned off, and it only happens when i have sodium loaded)

### System Information
Machine 1
Ubuntu 18.04
(dont have the stats at the moment)
mediocre laptop with integrated GPU

Machine 2
Windown 10 64bit
java 1.8.0_261
geforce 2080
i9-9900k

**Comment by dbl7id** [comment]
I think this issue is being caused by Compact Vertex Format. Try turning that off in sodium's settings.
I've had this happen even when all my driver graphics settings were set to off, mainly caused by a 3rd party texture pack that seemingly doesn't modify any existing block texture and only adds item textures. Turning off CVF fixes this for some reason and I might look into it when I have the time.

**Comment by campbebj** [comment]
Thanks a ton, that was it.

**Comment by MeeniMc** [comment]
This has been resolved for a long time (anyway, can't replicate in 0.4.10).
