### ISSUE TITLE
GUI Incompatible

### ISSUE THREAD

**Issue by timelady-victorious** [jellysquid3/Sodium#414]
Sodium changes the Options menu A LOT. 
This makes it completely incompatible with a lot of mods (any adding options to the vanilla options tab). Optifine does not do this, thus people are more likely to download optifine. If you change this I think more people will download your mod

**Comment by silversquirl** [comment]
Most Fabric mods I know of use ModMenu for configuration. The settings of any mod that does add options to the vanilla graphics settings can still be accessed using shift+p in sodium's menu.

**Comment by amnotbananaama** [comment]
Jelly has already written [an extensive write up](https://discord.com/channels/602796788608401408/651120262129123330/736290022734561302) in the [discord](https://jellysquid.me/discord) about why the Video Settings GUI is redesigned by Sodium.

> This makes it completely incompatible with a lot of mods (any adding options to the vanilla options tab).

See vktec's comment above. The [plan](https://discord.com/channels/602796788608401408/651120262129123330/733759179495571506)—as far as I'm aware—is to expose an API for other mods to add their own options to Sodium's GUI.

Constructive feedback on the design, functionality, and layout of the GUI is always welcome.

**Comment by timelady-victorious** [comment]
I'm sorry for being so rude, I was just starting GitHub and modded Minecraft. I know see how rude I was.

**Comment by milkev** [comment]
is it possible for an config option that simply has vanilla-style buttons? not the full menu, just the individual buttons so they look more like 
![image](https://user-images.githubusercontent.com/22010128/132775896-b8a05a3a-be8c-4f4f-85e8-54a406042830.png)
rather than
![image](https://user-images.githubusercontent.com/22010128/132775908-0227c6a2-2ce6-4c28-859d-c75ae44447f4.png)
i actually like your menu layout, but the odd semi-transparent button boxes are... odd
i mostly just dont like that the menu buttons are different from every other menu in minecraft, including other modded menu's. I also understand that this menu allows you to see the world while editting settings, however i personally dont care for that feature.
