### ISSUE TITLE
Missing vanilla graphics settings

### ISSUE THREAD

**Issue by Madis0** [jellysquid3/Sodium#46]
### Expected Behavior
Expected all vanilla graphics settings to be available in Sodium.

### Actual Behavior
The following graphics settings are missing:

- [ ] Fullscreen Resolution
- [ ] Distortion Effects
- [ ] FOV Effects
- [x] Entity Shadows
- [x] Entity Distance

### Reproduction Steps

1. Open Minecraft with Sodium, Settings > Video Settings...
2. Open vanilla Minecraft, Settings > Video Settings...
3. Compare the settings

### Attachments
N/A

### System Information

- Java Version: 14.0.1 64bit
- CPU: i7-1065G7
- GPU: Mesa Iris Plus Graphics

**Comment by Vixtron** [comment]
ctrl + shift + p

**Comment by Kroppeb** [comment]
Just `shift+p` works too.

**Comment by amnotbananaama** [comment]
That shortcut does work, but it is not documented leaving new users confused. The ideal solution for me would be either adding a new tab in Sodium's settings with "working vanilla settings" or something, or a button to take you to the vanilla settings screen.

Regarding Jelly's concern that users shouldn't be interacting with the vanilla settings screen because much of it is disabled, we *could* add some kind of tooltip that many of the vanilla options aren't working, or disable clicking on them outright

**Comment by Madis0** [comment]
I thought the goal is to simply transfer all of the vanilla settings to Sodium? Which it mostly already has done, just a few settings to go as outlined in the issue.

**Comment by vichvich4444** [comment]
Also no GUI scale if I remember

**Comment by Madis0** [comment]
GUI scale exists in 0.1.0

**Comment by Miros77** [comment]
> Just `shift+p` works too.

Tha

> That shortcut does work, but it is not documented leaving new users confused. The ideal solution for me would be either adding a new tab in Sodium's settings with "working vanilla settings" or something, or a button to take you to the vanilla settings screen.
> 
> Regarding Jelly's concern that users shouldn't be interacting with the vanilla settings screen because much of it is disabled, we _could_ add some kind of tooltip that many of the vanilla options aren't working, or disable clicking on them outright

add the button minecraft Graphics !!!!

**Comment by Eiion** [comment]
Going back to this issue since for two years it still didn't get implemented:

Please either put a simple line of text, something like:
"To change screen resolution, press Shift+P to open Vanilla settings. But DO NOT make any other changes than resolution since some settings might not work with Sodium"
Or add a resolution slider to the Sodium settings.

Also, from what I recall about the settings, there's also no "Fullscreen" checkbox, yet.

I feel like of all the vanilla settings not included, yet, those are the two most important ones, as these issues are what every new user will immediately - obviously - run into when the game only runs in low resolution window mode and there is no hint about how to make changes to that... other than googling for a solution.

Thanks for considering.

**Comment by ghost** [comment]
A year later, came here to bump because still not implemented and I still google everytime I have a fresh install how to come to the classic menu.

**Comment by jellysquid3** [comment]
The options for "Distortion Effects" and "FOV Effects" will not be added to the Video Settings screen, as these already exist in the Accessibility menu and do not need to be duplicated.

We will also likely not be adding an option to change the fullscreen resolution of the game, and instead will replace it with a "borderless fullscreen" implementation (https://github.com/CaffeineMC/sodium-fabric/issues/2359). This has numerous benefits, but most importantly, it means users will always get the expected behavior by default (the game keeps the existing monitor settings) with better performance and fewer bugs. Doing so also makes implementing support for VRR and HDR much easier.

For people who still _really_ need to change the render resolution (such as to improve performance), we will also be implementing a render scale option (https://github.com/CaffeineMC/sodium-fabric/issues/2362), which has the game render at a lower resolution, while still keeping the monitor configured to the user's settings. Notably, this makes the implementation of advanced upscaling technologies (such as FSR, DLSS, XeSS, etc) possible.

**Comment by jellysquid3** [comment]
Seeing that we have other issues open for each of the remaining use cases which otherwise ask for a fullscreen resolution option, this issue is closed.

**Comment by Eiion** [comment]
> For people who still _really_ need to change the render resolution (such as to improve performance), we will also be implementing a render scale option (#2362), which has the game render at a lower resolution, while still keeping the monitor configured to the user's settings. Notably, this makes the implementation of advanced upscaling technologies (such as FSR, DLSS, XeSS, etc) possible.

You keep forgetting those users that idle farms while AFK (as some hardware/software doesn't allow to turn screen off while in use). Rendering full screen will cause unnecessary GPU load. We switch to a tiny resolution and window mode to do that instead using full screen.

**Comment by Fnige** [comment]
> You keep forgetting those users that idle farms while AFK (as some hardware/software doesn't allow to turn screen off while in use). Rendering full screen will cause unnecessary GPU load. We switch to a tiny resolution and window mode to do that instead using full screen.

Windowed mode isnt getting removed so im not sure what youre on about
