### ISSUE TITLE
FPS ISSUE!!!

### ISSUE THREAD

**Issue by r-rajaneesh** [jellysquid3/Sodium#490]
### Expected Behavior
should have had more FPS than normal (25-30 FPS)

### Actual Behavior
getting only 10-15 FPS =(

### Attachments

![image](https://user-images.githubusercontent.com/75080457/105567877-56869600-5d5b-11eb-99c4-9b70a9e95abb.png)

**Comment by r-rajaneesh** [comment]
Looking up in the sky gives solid 30-35 FPS
![image](https://user-images.githubusercontent.com/75080457/105567922-b7ae6980-5d5b-11eb-8f40-119cb86c5889.png)

**Comment by r-rajaneesh** [comment]
Minecraft on a small window!
![image](https://user-images.githubusercontent.com/75080457/105567938-d280de00-5d5b-11eb-8206-7a649f287d78.png)

**Comment by jellysquid3** [comment]
This issue tracker is not for support inquiries, and this is not a bug report. Your graphics card (an Intel G41) is simply too weak to run the game well, and Sodium is unlikely to ever run well on it.

**Comment by r-rajaneesh** [comment]
But With Optifine i get about 25-30 FPS

**Comment by ReperakDev** [comment]
You can always ask for help [on the Discord](https://discord.com/invite/dQkmETa).

**Comment by jellysquid3** [comment]
Sodium rewrites large portions of the game's rendering engine to use modern techniques that generally only improve performance on hardware made in the last 10-11 years. The Intel G41 is very low-end integrated graphics card from 2008, and it is notorious for the poor support of OpenGL it offers, along with the very lacking performance... It's really only meant for the most basic desktop use, not games, and hasn't been supported by Windows or Intel for the longest time.

This is *expected behavior* and we can't do nothing about this -- your GPU is simply unsupported. Most likely, it's just falling back to software-based rendering because the GPU isn't actually capable of doing what it's being asked, resulting in abysmal performance.

The official Discord server (as linked above) might be able to offer workarounds, but you shouldn't hold out. We can only do so much to speed up the game.

**Comment by r-rajaneesh** [comment]
hmmm......
ok then..
=(
