### ISSUE TITLE
Stop render too much chunks on server

### ISSUE THREAD

**Issue by SnooComics9452** [jellysquid3/Sodium#503]
Every time i enter server and settlings set to 2 chunks, but server always force my pc render over 2 chunks

This feature ignore server render chunk settlings so makes no lags

It just make when we enter any server no more lag

**Comment by JustAMinecrafter** [comment]
The server makes your minecraft to run at a certain render distance, so u cant change it, so u cant increase or decrase the render distance as it is controlled by the server itself. If u own the server, u can change the render distance to be lower.

**Comment by SnooComics9452** [comment]
but why optifine can but sodium cannot

**Comment by Kroppeb** [comment]
> The server makes your minecraft to run at a certain render distance, so u cant change it, so u cant increase or decrase the render distance as it is controlled by the server itself. If u own the server, u can change the render distance to be lower.

That is not true. If you have a lower render distance than the server, you still get the chunks sent to you but the client shouldn't render. 
This seems like a bug to me.

**Comment by JustAMinecrafter** [comment]
> > The server makes your minecraft to run at a certain render distance, so u cant change it, so u cant increase or decrase the render distance as it is controlled by the server itself. If u own the server, u can change the render distance to be lower.
> 
> That is not true. If you have a lower render distance than the server, you still get the chunks sent to you but the client shouldn't render.
> This seems like a bug to me.

I dont understand

**Comment by LucilleTea** [comment]
Sodium uses fog and fog occlusion culling to prevent rendering chunks from beyond your render distance. If you use another mod to remove sodium's fog then Sodium has no other way to reduce render distance below the server's setting, and will render the full distance.
I'm not sure about the status of whether this is intended or a bug, but the best solution for now is to use fog.

**Comment by Snivine** [comment]
I don't understand this issue/suggestion at all, can you please explain it more and also provide examples?

You client will still get the chunk data from the server, but they'll not render, making it so that you only have network lag, if you're getting issues with this I would recommend trying to use get the server owner to lower the render distance, or not playing in the server at all, there's nothing you can do about it because the client has no way of communicating it's render distance to the server, a solution would be a mod that does that, but that's out of the scope of Sodium :P

**Comment by SnooComics9452** [comment]
may be, i installed no fog
