### ISSUE TITLE
Game crashes when mining emerald block

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#520]
### Crash Report File
https://pastebin.com/twVHJTx9

### Additional Information
nope

**Comment by magneticflux-** [comment]
It's because of this broken mixin in Portal Crafter that tries to inject into `getMaterial` but actually injects into `getHardness` for some reason: https://github.com/PalgamingHD/End-Portal-Creater/blob/610c16de25ac0da1415a7703bc1ac76cf802b1bd/src/main/java/net/portalcrafter/mixins/BlockMaterialMixin.java#L14

Not an issue with Sodium AFAIK.

**Comment by LucilleTea** [comment]
Reproduced the issue with Portal Crafter (and Fabric API) alone, so closing as an external issue. Thanks for looking into that.
