### ISSUE TITLE
Open GL 4.3 Missing

### ISSUE THREAD

**Issue by yoshmaster123** [jellysquid3/Sodium#531]
My friends with lower cards such as 3070s are getting over 900 fps, yet I'm getting only 300 fps with a 6900xt and an i9 10900KF. My only options for Chunk Rendering are Open GL 2.0 and 3.0, while they have 4.3. Please help, since I have no idea why it's not showing up.

**Comment by magneticflux-** [comment]
The first step you should take is to make sure you have the latest AMD drivers for your 6900XT. Second, make sure Minecraft it set up to use that GPU (since you have a KF processor, I assume you don't have any other GPUs so it should just work).

The code that checks for OpenGL 4.3 support is here: https://github.com/CaffeineMC/sodium-fabric/blob/27347710b3483cb5f02111e6dd344e45911f38c9/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/backends/gl43/GL43ChunkRenderBackend.java#L344-L360

From that, we can see that your 6900XT must not have support for at least one of the `GlFunctions` mentioned at the end (since it isn't ruled out immediately as a broken Intel model/driver). If you believe that it _does_ have support, you can try disabling the check but be warned: that mode of operation isn't supported.

**Comment by LucilleTea** [comment]
In the 0.1.0 release of Sodium AMD Windows drivers are blacklisted from using the OpenGL 4.3 renderer due to #24 
This is worked around in development versions of Sodium, the fix is not yet released.

**Comment by yoshmaster123** [comment]
Thank you so much for the quick response. I thought something was wrong
with my CPU and GPU.
