### ISSUE TITLE
Shulker boxes cause calamitous bugs on multiplayer server. 

### ISSUE THREAD

**Issue by toErIpNid** [jellysquid3/Sodium#554]
### Expected Behavior
Shulker boxes should work normally without problem. 

### Actual Behavior
Upon using a shulker box in my multiplayer server, the person trying to open it has their game become non-responsive. Everyone who enters the area after it has been placed experiences chunk-corruption-like issues including their games glitching or not repsonding. 

### Reproduction Steps
In multiplayer, place down/use a shulker box. 

### Attachments
Modlist: [https://imgur.com/a/mhU8d15](url) Raw link: https://imgur.com/a/mhU8d15

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: [fill me in]
- CPU: [fill me in]
- GPU: [fill me in]

**Comment by amnotbananaama** [comment]
Thank you for the report. A few notes:

1) I'm assuming this is a modpack. At least 5 or 6 of your mods only work on a server, and are not needed on a client. There may be more, it is much harder to determine from an image as opposed to text. Especially since you are experiencing freezing, it would be best to remove unneeded mods since they are taking away resources from the others.

2) Is there anything that leads you to believe this issue is caused by Sodium? Does the issue still occur if you disable Sodium? (E.g. rename the file to `sodium-fabric-mc1.16.3-0.1.0.jar.disabled`)? It's very unlikely this is caused by Sodium, given that other players experience the issue and the quantity of mods you have installed.

3) We just don't have enough information to help you further. Please provide the [latest.log](https://stickypiston.co/account/knowledgebase/130/How-do-I-find-my-Minecraft-Folder.html) file  and an [Alt + F3 ](https://youtu.be/KWl7Zwfam_4) screenshot from while you place a shulker box. Additionally, because it's almost certain that your issue is serverside please provide a full server log if you have access to that.

Again, your issue is almost certainly **not** caused by Sodium, this is just to confirm that and more importantly as a courtesy to help you determine the real cause of the issue.

**Comment by Ecorous** [comment]
This happens to me, but only with ppl who have sodium

**Comment by amnotbananaama** [comment]
@ExoPlant Can you give us more information please? A list of client mods, server mods, client and server logs, etc. Just telling us you are experiencing a bug doesn't help us with solving it.

**Comment by amnotbananaama** [comment]
Closing after 4 months without response, and limited diagnostic information. If this can be properly reproduced, the issue will be reopened
