### ISSUE TITLE
Crashes On Startup With Lithium, Phosphor

### ISSUE THREAD

**Issue by ripnonfegames** [jellysquid3/Sodium#566]
Minecraft Crashes on Startup with Lithium and Phosphor,
Steps:
1- Download
[Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium/files/3067101), [Lithium](https://www.curseforge.com/minecraft/mc-mods/lithium/download/3215441), and [Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor/download/3202749).

No crash report file, (I think, I don't know how to get crash report files either than C:\Users\namehere\AppData\Roaming\.minecraft\crash-reports\

So I'm trying to play Minecraft, using the original launcher, download lithium, Phosphor, Sodium, Fabric, Fabric API,
And it crashes on startup giving me Exit Code: 0

Heres The No-Debug info,
Debug is too much for me to handle because in the output log you can only copy what you see and not what you cant see.
[here it is, hopefully, you can help, if it's the wrong debug file or something please tell me and tell me how to actually get the crash report.](https://ghostbin.co/paste/zveqq/raw)

**Comment by pajicadvance** [comment]
There should be a latest.log file in C:\Users\namehere\AppData\Roaming\minecraft\logs. Upload it here

**Comment by crunge776** [comment]
Try to run with Minecraft but with java 15.

**Comment by LucilleTea** [comment]
From what you have provided it looks like Java is failing to start completely. You may have set incorrect JVM arguments? Or something else is wrong with the command being constructed to run the game. There are a few less likely options, eg. maybe the fabric jar isn't installed correctly or compatible with the original launcher.
A support request like this is [better suited to our Discord server](https://jellysquid.me/discord) than the issue tracker. 
In this case, your problem is not caused by our mods.
