### ISSUE TITLE
Crash when flying to negative Y

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#587]
### Reproduction Steps

1. Try to fall/fly under bedrock (negative Y)
2. The game crashes

### Crash Report File
[Crash report](https://gist.github.com/normannn/01a4bc2ecadfbf74486614155457b282)

### Additional Information
Compiled from next branch at [commit](https://github.com/CaffeineMC/sodium-fabric/commit/07c4cc1fd6a5b67f6fe08ee18db05d254a5051c4).

**Comment by Leo40Git** [comment]
I've replicated this crash... kind of. The error message is different (trying to access an index that's too big rather than a negative one), but it's the same idea:
1. In Hypixel Skyblock, go to the Deep Caverns area
2. Get to one of the lower levels - I replicated the crash in Slimehill and initially encountered it in Obsidian Sanctuary
3. Wait - I'm unsure of what actually _triggers_ the crash, but it seems to happen around these areas
4. The game crashes

[Here's the crash report.](https://gist.github.com/Leo40Git/d254bb87fa0bdb056b67afe513f604a0)
