### ISSUE TITLE
Disabling guis from texture pack

### ISSUE THREAD

**Issue by andreasdc** [jellysquid3/Sodium#640]
You can't disable custom guis from texture packs.

**Comment by jellysquid3** [comment]
We provide issue templates that we (generally) expect users to fill out when submitting new issues. It's not clear from the single sentence you've provided what the problem is, why it would be an enhancement instead of a bug, or how Sodium is preventing what you're trying to describe.

If you have additional information, please update this issue and request for it to be re-opened.
