### ISSUE TITLE
random block chunk 

### ISSUE THREAD

**Issue by jacesthing** [jellysquid3/Sodium#649]
Im not sure how to explain it, but i joined minecraft, with sodium, lithium and phosphor, and i went on my friends and my server and there was a big chunk of blocks i was inside, like jungle leaves and bamboo. i could walk through it and it follows me everywhere.

I narrowed it down to sodium after checking all the plugins on my server and removing lithium and phosphor. i then removed sodium and it stopped. It would be much appreciated if this would be solved as i rely on sodium to be able to play minecraft. as i dont have a good computer ( a chromebook dont make fun of me it was a gift) 

https://drive.google.com/file/d/14KyFs-a6MpjXfq9ohaFAGnTgh2ReiGaG/view?usp=sharing
i was in spectator and flew up to try and escape it

im not that smart btw

**Comment by LucilleTea** [comment]
The multidraw renderer cannot work correctly with your graphics driver due to incomplete feature support. This is similar to #179 or #24, though in your chromebook's case the broken driver is a different one again.
You can work around it by going to settings > advanced, then setting the chunk renderer to Oneshot (GL 3.0)

I suppose I should leave this issue open until we blacklist this driver too. There's an F3 screenshot here in the discord: https://discord.com/channels/602796788608401408/602805971391217683/837505446835257364
