### ISSUE TITLE
Unable to compile, "No 'minecraft' dependency was specified!"

### ISSUE THREAD

**Issue by Sirbucket** [jellysquid3/Sodium#657]
### Version Information

Unable to get version number due to inability to compile but this is the most recent build.

### Expected Behavior

Should compile

### Actual Behavior

Won't compile

### Reproduction Steps

Install the most recent build and run ./gradlew build and wait for it to fail with "No 'minecraft' dependency was specified!"

### System Information

> - Java Version: 14 Adoptjdk
> - CPU: Ryzen 3 3300U
> - GPU: Vega 3
> Linux Mint 21.04

### Other Information
https://scans.gradle.com/s/b3vhrrujcp4xk Gradle scan

Terminal view (Using kitty)
![compile_failure](https://user-images.githubusercontent.com/51178809/117871509-75a62680-b26b-11eb-8c06-58f756f2ee76.png)
![compile_failure_scan](https://user-images.githubusercontent.com/51178809/117871724-c158d000-b26b-11eb-85b2-ddfc0674f2ab.png)

I have no idea why it won't compile, your other mods don't have this issue, just sodium.

**Comment by Sirbucket** [comment]
Been trying to fix this on my own for the last week and I've had no luck.

**Comment by jellysquid3** [comment]
You need to clone the Git repository. Downloading a source tarball from GitHub will not work and is not supported.

**Comment by Sirbucket** [comment]
Ahh gotcha, thanks! I'm a dope, is this specified in the readme?

**Comment by Sirbucket** [comment]
Well, guess it's specified that it won't be answered, got it.

**Comment by jellysquid3** [comment]
We don't specify it in the README because _generally_ downloading a source tarball should just work (we actually have a [fallback path](https://github.com/CaffeineMC/sodium-fabric/blob/1.16.x/next/build.gradle#L71) in case the Git repository isn't available), but it's not really supported either way since it means your build will be missing metadata that makes debugging issues easier.

I just pulled a clean source tarball from GitHub and didn't have any issues building (even with the Git repository information missing) -- so the issue is likely specific to some kind of circumstance you've come across.

**Comment by Sirbucket** [comment]
Probably, I think it's just something strange to my machine, I did your recommendation and it worked fine.
