### ISSUE TITLE
Game Crashes When Joining the World

### ISSUE THREAD

**Issue by pluto7073** [jellysquid3/Sodium#671]
### Version
>
> 1.16.3-0.1.0
> 
### Reproduction Steps
>
> Not exactly sure. I just joined a world, and when I went to move around, the game just crashes.
>
### Crash Report File
> 
[hs_err_pid6384.log](https://github.com/CaffeineMC/sodium-fabric/files/6592507/hs_err_pid6384.log)
>

### Additional Information

> It happens with most worlds and servers, I tried singleplayer, hypixel, and a skymining server. All crashed. I also removed every mod besides Sodium, and it still crashed. But using Optifine, Vanilla, or any mod that isn't sodium it doesn't crash so I don't know.

**Comment by LucilleTea** [comment]
The crash is in your graphics driver, so you should consider updating that driver. At least, if you're meant to be using intel graphics. If you have a dedicated GPU, you need to configure your system to use it for Java.

A possible other workaround could be going to video settings > advanced, and setting the chunk renderer to a different setting?

Either way a graphics driver crash like this is usually out of our hands. Since we don't get this one regularly I suspect the issue is with your particular driver version, or some other configuration thing.

**Comment by MeeniMc** [comment]
This is old, should close because stale.
