### ISSUE TITLE
Braswell and Skylake iGPUs show as incompatible with multidraw but they aren't (1.16)

### ISSUE THREAD

**Issue by Snivine** [jellysquid3/Sodium#699]
### Version Information

Sodium 0.2.0-build.4
Minecraft 1.16.5
Fabric Loader 0.11.6

### Expected Behavior

Multidraw is available by default on Braswell iGPUs

### Actual Behavior

Multidraw is not available by default on Braswell iGPUs, so you have to disable driver blacklist

### Reproduction Steps

1. Use a Braswell CPU with an integrated GPU (In my case Intel Celeron N3060)
2. Go into the sodium settings > advanced
3. Find that Multidraw can't be enabled by default

### System Information

- Java Version: 16.0.1
- CPU: Intel Celeron N3060
- GPU: Intel HD Graphics 400

### Screenshots

Multidraw can't be enabled:
![2021-06-18_19 50 33](https://user-images.githubusercontent.com/72054019/122627799-28d61c80-d06f-11eb-8343-700eb82849dc.png)

Multidraw forcefully enabled by disabling driver blacklist:
![2021-06-18_19 55 15](https://user-images.githubusercontent.com/72054019/122627843-78b4e380-d06f-11eb-8fb6-1b68b09d7061.png)

Edit: haha funny number

**Comment by XArchE1** [comment]
Seems to be the case with Skylake IGPs as well. Even though they support multidraw they seem to be blacklisted.
![2021-06-19_13 02 18](https://user-images.githubusercontent.com/72723795/122636807-6b940500-d100-11eb-83b6-925e9905c3b8.png) 


![2021-06-19_13 04 15](https://user-images.githubusercontent.com/72723795/122636819-79e22100-d100-11eb-8ab7-98c802c7fa67.png)

**Comment by jellysquid3** [comment]
The current blacklist is conservative and only supports XX.XX.100.XXXX and newer because we do not have a clear idea of what drivers do and don't work. We've seen some Ivy Bridge/Gen7 GPUs work on Windows 7 (10.18.10.4358), and other Skylake/Gen9 GPUs fail on Windows 10 (21.20.16.4550). The pattern doesn't make sense, and Intel's versioning is a nightmare.

If someone could identify what driver version fixed these issues (rather than what drivers do/don't work) it'd go a long way towards refining the list.

**Comment by Snivine** [comment]
when I get my new PC I might try to debug multiple version of drivers on my laptop but we'll see

**Comment by jellysquid3** [comment]
This is no longer relevant as Sodium for Minecraft 1.16 is no longer actively developed, and newer versions for Minecraft 1.17 have since replaced the multi-draw renderer with a much more performant and compatible version which doesn't suffer from this issue.
