### ISSUE TITLE
IllegalArgumentException: Chunk is not loaded at class_4076{x=20, y=0, z=-3}

### ISSUE THREAD

**Issue by Octol1ttle** [jellysquid3/Sodium#705]
- [x] I did look for the error on this issue tracker and did not find any mention of it

### Version

Minecraft: 1.17
Fabric loader: 0.11.6
Sodium: mc1.17-0.3.0+build.428

### Reproduction Steps

None. I was just playing when the game randomly crashed

### Crash Report File

https://paste.gg/p/anonymous/539761e737924fd886a4d23b6cecc2d9

### Additional Information

This happened during normal gameplay on a dedicated Fabric 1.17 server running Lithium, Starlight, Krypton and LazyDFU
Client mod list is:
Dark Loading Screen 1.6.5
LazyDFU 0.1.2
Lithium 1.17-0.7.2
Sodium 1.17-0.3.0+build.428
Starlight 1.0.0-RC2 1.17.x

**Comment by amnotbananaama** [comment]
This is a known issue. Despite the version bump, **Sodium has not yet been released for 1.17, and it is not ready for production use.** Testing and development of 1.17 is ongoing, see pinned issue #674 for more.

> The problem is that chunk unload events cause updates to propagate neighbors, who begin building and then get unloaded before they finish

**Comment by jellysquid3** [comment]
Reporting issues for staging branches isn't an issue. I prefer it over Discord. We just need to make sure they're labeled correctly.

**Comment by embeddedt** [comment]
Hi, I experienced the same crash - completely understandable given that I was using the `dev` branch.

[crash.txt](https://github.com/CaffeineMC/sodium-fabric/files/6704824/crash.txt)

Thanks for your continued efforts to make Minecraft playable on older PCs. :slightly_smiling_face:

**Comment by hk21702** [comment]
I have a similar crash on the same build. Happens when going into unloaded chunks between the overworld and nether on a server. Seems to not happen when the chunks are already loaded. Can't reproduce when teleporting within the same dimensions into unloaded chunks. I can't really reproduce it in single player. Could be because of rendering distance differences or I'm just not replicating the situation well. I doubt its the datapacks on the server though.

Client has these other mods:
fabric-api-0.35.2+1.17
itemscroller-fabric-1.17.0-0.15.0-dev.20210608.211652
litematica-fabric-1.17.0-0.0.0-dev.20210616.033538
malilib-fabric-1.17.0-0.10.0-dev.22+beta.1
minihud-fabric-1.17.0-0.19.0-dev.20210609.185508

[crash.txt](https://github.com/CaffeineMC/sodium-fabric/files/6705653/crash-2021-06-23_21.18.06-client.txt)

**Comment by Octol1ttle** [comment]
Closed by https://github.com/CaffeineMC/sodium-fabric/commit/c0135a67ff7ae388a9e318de1c3ccc79332f1091
(GitHub didn't close this for some reason)
