### ISSUE TITLE
Visual bugs

### ISSUE THREAD

**Issue by TinyMandalorian** [jellysquid3/Sodium#774]
### Version information

sodium-extra-mc1.17.1-0.3.3

### Expected Behavior

Shouldnt cause visual glitches

### Actual Behavior

Causes visual glitches heres screenshots
![2021-07-18_09 29 28](https://user-images.githubusercontent.com/67829574/126069438-0b8a48a1-dd73-44c5-8023-15c2e6415ca7.png)
![2021-07-18_09 29 37](https://user-images.githubusercontent.com/67829574/126069443-a37e8ad7-1c95-45ec-a724-52773319c72b.png)
![2021-07-18_09 29 10](https://user-images.githubusercontent.com/67829574/126069446-ff25d3f3-94aa-46cd-8fe7-91725d1dad36.png)

### Reproduction Steps

Launch the game

See visual glitches

### Java version

(build 1.8.0_261-b12 Version 8 so java 8 i think

### CPU

amd e1-2500 apu with radeon(tm) hd graphics

### GPU

AMD radeon HD 8240

### Additional information

i am using Sodium Extras with this.

**Comment by SdrawkcaBstI** [comment]
Adding to this thread in order to avoid duplicate issues
Visual bugs for me appear to show either the magenta polygons or an item/texture map(?), both when running Sodium alone or with other mods.

Sodium mc1.17.1-0.3.0+build.5
Java 16.0.1 2021-04-20
AMD A8-6500, Radeon R7 240

![2021-07-17_23 32 50](https://user-images.githubusercontent.com/18900239/126073322-9602b7fa-3524-4836-8f95-080260c03103.png)
![2021-07-17_23 32 57](https://user-images.githubusercontent.com/18900239/126073323-959a634c-b30f-4e38-9e74-cf7da3813648.png)
![2021-07-17_23 32 29](https://user-images.githubusercontent.com/18900239/126073319-eaa135bb-98f8-41c4-8263-08f4690dff08.png)

**Comment by TinyMandalorian** [comment]
Yeah it sometimes shows items for some weird reason but yeah exact same bug. sometimes it just a purple blob and sometimes its just item textures for some reason

**Comment by TinyMandalorian** [comment]
Developer of sodium do you got any idea whats going on?

**Comment by jellysquid3** [comment]
Not sure. We're seeing a lot of problems with older AMD GPUs. Needs investigation.

Making this issue a parent of #779 for tracking.

**Comment by TinyMandalorian** [comment]
ok Ty bro

**Comment by YoFoNL** [comment]
I have the same issue with a  ''amd a6-5200 apu with radeon(tm) hd graphics''

**Comment by jellysquid3** [comment]
This should be fixed with [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1).
