### ISSUE TITLE
Game crashing with weird error on world join

### ISSUE THREAD

**Issue by chemicalursine** [jellysquid3/Sodium#775]
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5

### Reproduction Steps

Launch the game, create a world and the game crashes the moment the world renders.

### Crash Report file

[crash-2021-07-18_19.02.06-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6836649/crash-2021-07-18_19.02.06-client.txt)

### Additional information

I know that this error might be linked to the fact that I have quite a lot of mods in total but this error diseappears when uninstalling Sodium and it's been 2 versions in a row that I keep having it, I'd like to know if someone could give a bit of help.

**Comment by amnotbananaama** [comment]
> it's been 2 versions in a row that I keep having it

What is the other version you are referring to? If not 0.2.0, **please give us the exact commit or filename**. I'd like to know if it was after 5444aeb when support for `fabric-rendering-fluids-v1` was added.

`class_3621.method_15776` is `WaterFluid#randomDisplayTick()` so that's my initial suspicion. We'll need to figure out which of your mods add modded fluids to determine if my suspicion is correct

**Comment by chemicalursine** [comment]
Okay, I found the mods source since one of the author updated it recently mentionning the fact that his mods was making the game crashes with Sodium, if you have any more people asking about this issue, it's coming from DripSounds and they need to update to last version.

**Comment by Mistyttm** [comment]
Hi I'm having this issue now. I've had to move to sodium from Optifine. Minecraft Crashes only when Sodium is installed

here's the crash report
[crash-2021-08-27_21.01.38-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7066526/crash-2021-08-27_21.01.38-client.txt)

**Comment by MeeniMc** [comment]
Probably an incompatible mod, very old, issue is stale.
