### ISSUE TITLE
Sodium spams error in game log

### ISSUE THREAD

**Issue by linkthehero1234** [jellysquid3/Sodium#793]
### Version information

0.3.0+build.5

### Expected Behavior

The game should launch normally without errors

### Actual Behavior

The game launches and runs normally but spams the error`OpenGL debug message: id=2, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM in glTexParameter(param=0x2900)'` in the log and eventually locks up the whole computer

### Reproduction Steps

1. Launch game
2. Go into world/server

### Java version

Java 16

### CPU

AMD Ryzen 7 2700

### GPU

AMD Radeon Vega 56

**Comment by jellysquid3** [comment]
What other mods are you using? We don't call `glTexParameter` anywhere. It's probably a fault somewhere else.

**Comment by jellysquid3** [comment]
This might be fixed in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1), and as such, I'm going to close this issue. If the problem still occurs, please ask for this issue to be re-opened, and provide a new log file.

**Comment by NyaomiDEV** [comment]
It is still very much here, sadly. For now I am redirecting the whole logs folder to `/dev/null` on my Linux system.

Using Ryzen 7 3800XT, on a Radeon RX 580, using Mesa drivers. Please re-open the issue.

**Comment by silversquirl** [comment]
@AryToNeX Please provide a log file

**Comment by NyaomiDEV** [comment]
Testing in my super minimal setup (just Sodium and VoxelMap) did still spam the console; however, it just so happens that people are quick to blame Sodium because it "deals with OpenGL stuff". The real culprit was VoxelMap, or some sort of incompatibility between the two mods.

I do not have logs aside from literally the same line that OP posted, spammed over and over again; but I guess that at this point in time this should serve as enough of a reason to avoid VoxelMap and use other minimap mods.

**Comment by panigrc** [comment]
@NyaomiDEV indeed your are right! I deactivated VoxelMap and the logs didn't reappear.

**Comment by MeeniMc** [comment]
No such error present in 0.4.10 with Voxelmap 1.12.7 (a fork available on Modrinth). Performance of this mod is horrible though (not Sodium's fault, it's got a bug with access out of range in an image).

**Comment by jellysquid3** [comment]
Not an issue with Sodium. We don't call these functions anywhere, it's some other mod or overlay software which is injecting into Minecraft.
