### ISSUE TITLE
Breaking animation is rendered in front of lava fog

### ISSUE THREAD

**Issue by CalXee** [jellysquid3/Sodium#807]
### Version information

0.3.0

### Expected Behavior

The animation is not visible as it is behind fog.

### Actual Behavior

It is visible.

### Reproduction Steps

1. Go under lava
2. Mine something

### Java version

Java 16

### CPU

i7 8750H

### GPU

GTX 1050 Ti

### Additional information

![2021-07-29_13 00 04](https://user-images.githubusercontent.com/68349758/127534413-98cf10af-ee52-43f9-9e63-6a945bb90b59.png)

**Comment by MeeniMc** [comment]
Issue still present 0.4.10

**Comment by TheUserCreated** [comment]
This issue seems to no longer be valid. Vanilla and sodium seem to match now, see attached screenshots.
![2023-12-03_00 22 05](https://github.com/CaffeineMC/sodium-fabric/assets/47259856/26f26918-2185-44f1-a33c-9237b59e9ae5)
![2023-12-03_00 22 45](https://github.com/CaffeineMC/sodium-fabric/assets/47259856/3a374206-3155-4a73-a544-5cf3801ce4c9)

**Comment by Lolothepro** [comment]
Note: https://bugs.mojang.com/browse/MC-224704
