### ISSUE TITLE
Sodium mod low fps in linux

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#831]
### Version information

mc1.16.5-0.2.0+build.4

### Expected Behavior

Higher fps than optifine or any other performance mod for optifine i got 100+ fps. but when i got sodium i got 30+ which is very low and when the game starts the fps drops to 5. sometimes the fps is ony 20+

### Actual Behavior

very low fps in sodium. optifine give more fps than sodium

### Reproduction Steps

don't know it perfectly but install arch linux in intel hd 3000 and run minecraft

### Java version

Java-8-openjdk tried switching to 16 still no difference but i don't know the correct java version but i think it is java-8-openjk

### CPU

intel core i3-2350m

### GPU

intel hd 3000 desktop

### Additional information

i use minecraft 1.16.5 with no other mods

**Comment by LucilleTea** [comment]
this is a support inquiry rather than a bug report, so is better suited to the discord server. i see you did ask there and you were advised to add more optimization mods eg. lithium and phosphor, which you said you weren't already using, but you didn't follow up by adding them.
please report back on results from adding lithium and phosphor alongside sodium in the #mod-support channel
