### ISSUE TITLE
Allow top face culling for potted cacti, bamboo and azaleas

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#858]
Vanilla has this disabled as a kludge fix for MC-195461. Sodium could probably do a better job, re-enabling cullface for these blocks and fixing the original bug properly in the first place.

![2021-08-28_00 35 30](https://user-images.githubusercontent.com/52297970/131198335-0720994a-dd8f-40f8-b249-5b7f4051104d.png)

https://bugs.mojang.com/browse/MC-208189
https://bugs.mojang.com/browse/MC-226540

**Comment by amnotbananaama** [comment]
Thank you for the detailed issue, in particular describing vanilla's fix for MC-195461. [It's not clear](https://discord.com/channels/602796788608401408/752637878462578778/863012516053385216) if the culling issue is still present in Sodium or not, I've been far too busy to test.

Regardless, this helps immensely figuring out how the issue was "fixed" in vanilla. Originally I wanted to make sure we mirrored vanilla behavior, but it seems like that isn't necessary

**Comment by muzikbike** [comment]
fYI, the above screenshot (as well as all my recent screenshots posted here) was taken with Sodium active.

**Comment by muzikbike** [comment]
Fix confirmed:
![2022-02-03_11 21 49](https://user-images.githubusercontent.com/52297970/152333708-3a1a77f9-8160-4b1b-8089-5052b7cca9d0.png)
