### ISSUE TITLE
Fix tripwire string not being translucent when connected to tripwire hooks

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#877]
Very similar issue to #876 and probably has the same cause - the tripwire hook block just needs to be set as able to support translucency in textures.

![2021-08-30_23 03 06](https://user-images.githubusercontent.com/52297970/131411817-df3e5691-c7a8-45d4-8c06-1bec75f87781.png)

**Comment by jellysquid3** [comment]
We can't really fix this without providing a resource pack replacement and some sort of mechanism for allowing block models to provide per-quad render layers. This is because by default a block can only render on a single layer, and the tripwire hook model chooses the solid layer (which obviously doesn't support the semi-transparent string in the same model.) There are some projects for Fabric which extend the JSON model format to support this, but right now, we don't currently support those APIs.

I'm also not sure this is the sort of thing we should be going out of our way to fix. While it is true that Sodium fixes some graphical issues, it mostly solves problems where assets (such as a model) aren't rendered correctly, not problems with the assets itself.
