### ISSUE TITLE
Invisible Modded Block

### ISSUE THREAD

**Issue by EkutoruSama** [jellysquid3/Sodium#897]
### Version information

release forge-36.2.0

### Expected Behavior

All the blocks must be visible

### Actual Behavior

Modded Blocks are invisibles like Water Wheel ( Create Mod ). Some ores be invisible. 

I using Ragnamod VI

### Reproduction Steps

1. place Water Wheel
2. I See informations with What I´m Looking At and the block is working
3. The rendering not working

### Java version

Java 8

### CPU

I5-9600k

### GPU

Nvidia rtx2080S FE

**Comment by eshankiyer** [comment]
Sodium isn't made or designed for Forge, its designed specifically and only for FabricMC (fabricmc.net) Unless your using something like Chlorine, which CaffineMC probably won't provide support for since its unofficial, you should always use the fabric-loader-xxxx profile in your launcher to use Sodium.

2nd, the reason the create mod blocks are not visible is that Sodium hasn't added support for that particular mods blocks in the game, thus not rendering them, thus not showing them. Unfortunatly, until the CaffineMC devs decide to add support for that mod, your outta luck

**Comment by EkutoruSama** [comment]
Esganepickfighter

Okay, thank you very much <3

**Comment by jellysquid3** [comment]
Like the other user mentioned, we have nothing to do with any Forge port of our mods, so you need to take the issue up with them.
