### ISSUE TITLE
sodium cause unstable fps

### ISSUE THREAD

**Issue by ppmaks** [jellysquid3/Sodium#908]
### Version information

mc 1.17.1

### Expected Behavior

stable fps

### Actual Behavior

unstable fps fom 70 to 30 when loading new chunks on 8 view distance

### Reproduction Steps

jsut run the mod 

### Java version

java 16

### CPU

intel core i3

### GPU

intel hd graphics 

### Additional information

dd

**Comment by jellysquid3** [comment]
This is lacking any information to actually diagnose the problem. Since you'd rather go around on our issue tracker is complain about how this is an "unfinished mod" with "no useful purpose", I'm going to close this instead of giving our usual kindness where we keep issues open for months, hoping we'll eventually be able to fix the problem described, while we wait for users to give us the bare minimum of information.
