### ISSUE TITLE
Entities can ignore being affected by fog at certain angles.

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#94]
### Expected Behavior
Entities don't ignore fog and all get the same result on the fog distance.

### Actual Behavior
Entities don't ignore fog and hide based on the camera position.

### Reproduction Steps
Spawn an entity, move away until its starting to get into the fog, then move the camera around

### Attachments
![Entity ignoring fog](https://user-images.githubusercontent.com/36578995/87625916-54cb7e00-c6f9-11ea-8646-3c69b154cd0d.png)
![Entity not ignoring fog](https://user-images.githubusercontent.com/36578995/87625919-572dd800-c6f9-11ea-824d-a09f7bcc6bee.png)

### System Information
- Java Version: bundled jre, java 8 b51
- CPU: amd ryzen 3 3200u
- GPU: amd radeon vega 3

**Comment by jellysquid3** [comment]
The problem here is caused by entity rendering still using the old fixed-function pipeline, which doesn't use the same distance calculation as Sodium because it only exists as a proprietary NVIDIA extension. We'll have to extend our shaders to cover entity rendering in order to fix it, but that might help performance anyways.

**Comment by mrmangohands** [comment]
As of 1.17 all systems have radial fog and this issue doesn't occur anymore.
