### ISSUE TITLE
random crashes which possibly related with AE2

### ISSUE THREAD

**Issue by AmonRay** [jellysquid3/Sodium#942]
### Version information

0.3.2+build.7

### Reproduction Steps

random

### Crash Report file

[crash-2021-10-18_23_52_04-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7369085/crash-2021-10-18_23_52_04-client.txt)

**Comment by AmonRay** [comment]
probably related with https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5534

**Comment by jellysquid3** [comment]
This looks to be the fault of another mod which is modifying the map of entities from outside the main thread, since we're only reading this map, and we're on the main thread when we do so. I can't determine which mod is at fault from the crash report, so you'd be best off narrowing down mods one by and one, and reporting it to their authors.

**Comment by AmonRay** [comment]
@jellysquid3 I spent about a week to investigate which of the mods leads to such issue. Im sure for 90% - its AE2. Tried to remove his from my modpack - everything works as expected. Thanks for clarify, I hope this info will help AE2 devs to solve this

**Comment by shartte** [comment]
You're iterating the map, but you call methods on the block entities (`getRenderAttachmentData`), which can in theory interact with the world and cause additional chunks to be loaded (which could lead to modifications of the map you are currently iterating, leading to the aforementioned exception).

I think we might even be doing this under certain circumstances, no other threads involved.
