### ISSUE TITLE
Looking for custom sodium version that works with Indium

### ISSUE THREAD

**Issue by BowBoy1** [jellysquid3/Sodium#965]
I am currently putting together a 1.16.5 modpack that has a mod that uses the immersive portals engine. I found a custom sodium version that works with the immersive portals but I can't seem to find any version of indium that works with it, and I need indium because another one of the mods uses an advanced rendering program. Is there a version of sodium for 1.16.5 that can use a custom indium version with it and work with immersive portals?

**Comment by eshankiyer** [comment]
Uh first of all I don't think any such version of indium that exists. Most likely you'll probably have to learn java and fork the Indium repository. 

Second, ensure your using the latest 1.16.5 builds of both Indium and Sodium and if that doesn't work out you could open a new issue on the Indium repository (https://github.com/comp500/Indium) with the content of the crash log. 

Third, since Caffeine isn't part of the development of Indium, Caffeine can't really provide support.

**Comment by amnotbananaama** [comment]
Closing this as a question, as this is asking for help with forked/unofficial versions of Sodium, and the bug tracker is not the place for this.

See the answer above, my suggestion is to ask nicely for help in the `#lounge` channel of [our Discord](https://caffeinemc.net/discord), or another Fabric-related Discord server.
