### ISSUE TITLE
Optifine and Vanilla ability to disable clouds and fog

### ISSUE THREAD

**Issue by ValidUser2147483647** [jellysquid3/Sodium#97]
As the title says - Sodium removes the vanilla setting of being able to disable clouds, which I usually religiously play without. The same goes for fog.

I'd really like to see these settings being added back / into sodium.

**Comment by Kroppeb** [comment]
Check the general tab

**Comment by LOuroboros** [comment]
> 
> 
> As the title says - Sodium removes the vanilla setting of being able to disable clouds, which I usually religiously play without. The same goes for fog.
> 
> I'd really like to see these settings being added back / into sodium.

I also missed it just like you, but the toggle to disable Clouds can be found in the General tab and it's separate from the Cloud Quality option, for whatever reason.

I do agree it'd be cool to have the ability to disable the Fog though. That's an option Sodium does not have right now, but Optifine does.

**Comment by ghost** [comment]
overworld terrain fog can already be disabled in the latest commit, as jelly sees the other fog rendering as a game mechanic (nether fog, water fog, etc)

**Comment by jellysquid3** [comment]
You can already disable clouds. The option is split because players wanted a faster way to disable them while building, but maybe we'll move it since people can't seem to find it.

As for fog, there will be an option in Sodium 0.1.1 to disable fog in the overworld only. As asbyth points out, the fog is used in other dimensions/while underwater as a gameplay mechanic, and allow people to disable it would arguably compromise on Sodium's goals. If you really want to remove other sources of fog, you can install the ClearView mod, which gives you many more fog options.
