### ISSUE TITLE
plzz merge sodium lithium phosphor hydrogen into one mod

### ISSUE THREAD

**Issue by gwrayeeed** [jellysquid3/Sodium#979]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by K0-RR** [comment]
You didn't even explain why you want these mods to be merged.

Not everyone uses/wants to use Phosphor.
About Hydrogen - this is from the readme "Hydrogen relies on rather egregious hacks in order to load some code into the game, primarily because the Guava library developers really do not want people re-implementing their interfaces. These hacks are "safe" in the sense that the game will simply fail to start if a problem occurs, but are really rather not suitable for the standards which Lithium intends to promote. In other words, this mod could be looked at as "things too dirty to put in Lithium.""

The reason these mods are standalone is they optimize completely different parts of the game. I believe it's also easier to maintain them this way.

**Comment by Kroppeb** [comment]
Hydrogen also has a few mod incompatibilities, and sodium isn't a mod you'd install on a server, unlike the others

**Comment by jellysquid3** [comment]
no.
