### ISSUE TITLE
Game freezes, after trying to relaunch the whole computer freezes

### ISSUE THREAD

**Issue by Yadokingu** [jellysquid3/Sodium#98]
After playing for a while (anywhere from 10 to 40 minutes) the game freezes and I have to force close it in the task manager. 
If I try to start it again I get this error message:
![sodium error](https://user-images.githubusercontent.com/11133215/87783695-4bdfc700-c835-11ea-813a-722b1a661cd9.png)
If I now even just open the minecraft launcher, the whole computer freezes

There was no crash log, but maybe the last two logs can be helpfull:
[2020-07-17-7.log](https://github.com/jellysquid3/sodium-fabric/files/4937678/2020-07-17-7.log)
[latest.log](https://github.com/jellysquid3/sodium-fabric/files/4937679/latest.log)

- Java Version:  happens with JRE 14 and the included JRE 8
- CPU: Core i5-2450M (Sandybridge)
- GPU: Nvidia Geforce GT 630M

It may be also notable that this is a Laptop and so most stuff runs on Intels integrated graphics but the game is being rendered on the Nvidia GPU.

**Comment by smonnnn** [comment]
This seems to be an issue with your graphics card drivers, make sure they are up to date and maybe google around a bit for possible solutions.

**Comment by Yadokingu** [comment]
They are as up to date as they get. 
I have never encountered something like this in the 8+ years I have this computer...
But I will google a bit.

**Comment by jellysquid3** [comment]
We can't damage the Minecraft launcher, so if you're experiencing problems there, something else is wrong. You can try re-installing it, or try using an alternative launcher such as MultiMC.

As for the issue here, your game is using the wrong GPU when Fabric is present because of poor application detection. Essentially, the NVIDIA/Intel drivers expect a Java process started with a given class name, and Fabric changes this class name. You can usually work around it by right-clicking the Minecraft Launcher and clicking "Launch with high-performance graphics processor" or whatever other verbage.

To make matters worse, the Intel HD 2xxx doesn't work correctly with Minecraft without specific hacks that break after Java 8u25, resulting in the error you see when using the integrated GPU.

If that doesn't exist, take a look at your driver(s) control panel and configure the Java/Minecraft processes to run on your dedicated GPU.

**Comment by Yadokingu** [comment]
The game is running on my Nvidia GPU. That's not the problem. The problem is, it runs fine for 10-40 minutes, then freezes, I have to kill the process and when I try to launch it again, I get the above error.
I googled a bunch and nobody has described that error as a result of a freeze/crash. Either they had it or they didn't.
Kinda seems like after the freeze the OpenGL.DLL can't be accessed again until the whole computer is rebootet. Why that would be I have no idea. Any speculations here?
Edit: Just to show the game runs on the Geforce: 
![2020-07-17_17 36 58](https://user-images.githubusercontent.com/11133215/87804446-2dd58f00-c854-11ea-911e-73f101ed26da.png)

**Comment by luximus-hunter** [comment]
It does not seem to be an issue with Sodium tho

**Comment by Yadokingu** [comment]
> It does not seem to be an issue with Sodium tho

It seems to me like Sodium crashes the Nvidia graphics driver. I have no other explaination for the behaviour. Not sure if that is sodiums fault or Nvidias fault, I can just say that I have never seen that happen before.

If there is nothing to be done, there is nothing to be done, but it seems @jellysquid3 didn't actually understand the problem before closing this...

**Comment by smonnnn** [comment]
She does understand what the issue is here, but there's nothing she can do about it. It is entirely possible that a certain gl function being used by Sodium causes this crash, but this would still be the fault of bad drivers or a broken driver installation. It is very likely unfixable from Sodium's end.

**Comment by Yadokingu** [comment]
>She does understand what the issue is here

She does seem to think lthat the issue is that my game is running on the Intel GPU:

>As for the issue here, your game is using the wrong GPU when Fabric is present because of poor application detection. Essentially, the NVIDIA/Intel drivers expect a Java process started with a given class name, and Fabric changes this class name. You can usually work around it by right-clicking the Minecraft Launcher and clicking "Launch with high-performance graphics processor" or whatever other verbage.

But that is simply not the case, as seen in the screenshot above. The game runs on the Nvidia GPU.
So I'd say no, she doesn't understand what the issue is here.
I mean that can happen to anybody, reading in a hurry and not getting the core problem, but getting the issue closed because of that is a bit frustrating.

**Comment by jellysquid3** [comment]
I initially closed this issue on the assumption that your game was crashing in driver code, and that it was causing your Intel GPU to be used as a fallback, which would then fail because the HD 2xxx is not properly supported.
