### ISSUE TITLE
Sodium gets the view distance directly instead of using the getter method

### ISSUE THREAD

**Issue by IMS212** [jellysquid3/Sodium#994]
This causes Vanilla to not run the server view distance check, and returns the client distance even if the server distance is smaller which is unintended behavior as of 1.18.

**Comment by HybridEidolon** [comment]
Is this as simple as calling `GameOptions#getViewDistance` here instead of reading the field directly?

https://github.com/CaffeineMC/sodium-fabric/blob/838c07eb0639aeb7fc026abf4d32205d124e623c/src/main/java/me/jellysquid/mods/sodium/client/render/SodiumWorldRenderer.java#L161

https://github.com/CaffeineMC/sodium-fabric/blob/838c07eb0639aeb7fc026abf4d32205d124e623c/src/main/java/me/jellysquid/mods/sodium/client/render/SodiumWorldRenderer.java#L241

**Comment by IMS212** [comment]
Should be.

**Comment by tbejos** [comment]
Seems like that should work (tested locally and everything seemed fine), @HybridEidolon don't forget to change the usage here as well!

https://github.com/CaffeineMC/sodium-fabric/blob/838c07eb0639aeb7fc026abf4d32205d124e623c/src/main/java/me/jellysquid/mods/sodium/client/render/SodiumWorldRenderer.java#L210

**Comment by filips123** [comment]
Would it be possible to have an option to switch between "chunks outside the server render distance should remain loaded until they are also outside the client render distance" (something like pre-1.18 behavior) and "the client render distance is capped by the server one" (1.18)?

**Comment by Leisterbecker** [comment]
Can I work on that issue, if its not done yet?

**Comment by IMS212** [comment]
#1050

**Comment by tbejos** [comment]
Looks like it wasn't linked but now that #1050  was merged this should be able to be closed
